### ISSUE TITLE
Table: auto scroll (scrollToRow) doesn't scroll to the needed row

### ISSUE THREAD

**Issue by medikornov** [iTwin/iTwinUI#1003]
#### Describe the bug (actual behavior)
Auto scroll is not working properly. 
When your needed row is below the viewport, auto-scroll scrolls to the row. And that row is either cut (just a half or less of it is visible) or it is 1 row below (not visible at all).
When the needed row is above the viewport,  auto scroll works perfectly.

#### Expected behavior
Auto-scrolled row should be fully visible.

The best would be if there was an option to choose to have the auto-scrolled row at the beginning of the viewport. Now it is either the beginning or the end of the viewport.
Same feature implemented in `itwin/ui-components` using `react-window`. Has a good api on how to scroll:
"auto" | "smart" | "center" | "end" | "start" 
https://github.com/iTwin/itwinjs-core/blob/912f966315168c861a33da4aaf41e86668c5cf11/ui/components/src/ui-components/tree/controlled/component/TreeRenderer.tsx#L86

#### Reproduction
`iTwinUI-react: 1.48.1`: https://codesandbox.io/s/itwinui-react-example-forked-6ud3uo?file=/src/App.tsx
`iTwinUI-react: 2.2.1`: https://codesandbox.io/s/itwinui-react-example-forked-0stjvo?file=/src/App.tsx

##### Steps to reproduce
1. Scroll to the top of the table
2. In `input` field enter number (e.,g. 150) you want to scroll to and press `scroll to row` button
3. The last visible row is 149 instead of 150

#### Additional information
`react: 16.14.0`

`iTwinUI-react: 1.48.1`
![image](https://user-images.githubusercontent.com/75395229/212541232-85afafc9-17c9-4a0b-8f44-46800575c0da.png)
`iTwinUI-react: 2.2.1`
![image](https://user-images.githubusercontent.com/75395229/212541257-aa64e9fa-0ba3-455b-ae09-adf5fd99d54f.png)

**Comment by GintV** [comment]
Any progress with this one? We also are having this issue.

**Comment by gretanausedaite** [comment]
Hi @GintV, the work has not been started yet.
You can look at our backlog and express you opinion on what we should prioritise next in iTwinUI-react biweekly community meeting (happening on Tuesdays).
We also highly encourage our users to contribute to this library! PRs are always welcome.

**Comment by elephantcatdog** [comment]
@FlyersPh9 #473 is not related.

**Comment by elephantcatdog** [comment]
@medikornov @GintV I investigated this issue and found that it's just a little problem with your `scrollToRow` function. The function returns the index of the item in the table (starting at 0), but the table starts at 1. You just need to add one to the result of `findIndex` so the table scrolls as you expect.

Here's an updated version of the repro: https://codesandbox.io/s/fixed-itwinui-autoscroll-example-p392me?file=/src/App.tsx

I did check our code and confirmed that it works like it's supposed to.

**Comment by medikornov** [comment]
@elephantcatdog maybe I didn't understand you, but I think it doesn't fix the issue. If I scroll down manually and enter "1" (or something that's above) in the input field and then press "scroll to row", I get this: 
![image](https://user-images.githubusercontent.com/75395229/217474666-7de56cf8-6b66-4410-aecd-4cdde5db3c94.png)
row with `elementId: 1` is not visible.

**Comment by elephantcatdog** [comment]
Yeah, I'll look at it again. Sorry for the confusion.
