### ISSUE TITLE
v3: allow Alert's "clickable text" to be a `<button>`

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#1013]
## Preface

The recent addition (#1006) of `as` prop to `Anchor` was driven by the need to encourage proper usage of `<a>` vs `<button>` elements. The goal is simple:
- if it's an `<a>`, it should navigate somewhere and must have a proper `href`
- if it's a `<button>`, it should perform an action such as opening a modal

See https://ashleemboyer.com/blog/should-i-use-a-button-or-a-link

## Problem

I noticed that the `<Alert>` react api makes it hard to use the `clickableText` as a button because it hardcodes the `a` tag.

https://github.com/iTwin/iTwinUI/blob/926e6d592a05a1234250aa17cd4d72acfa7e9211/packages/itwinui-react/src/core/Alert/Alert.tsx#L82-L88

So usage often ends up with `<a>` used without `href` but with `onClick`, which is not ideal.

This can kinda be worked around by passing the desired element as a child.
```jsx
<Alert type='positive'>
  my alert
  <button className='iui-alert-link' onClick={() => {}}>Learn more</button>
</Alert>
```

## Suggested solution

A nicer react API should be provided. Maybe a subcomponent.
```jsx
<Alert type='positive'>
  my alert
  <Alert.Action as='button' onClick={() => {}}>Learn more</Alert.Action>
</Alert>
```

After that, we could also deprecate `clickableText` and `clickableTextProps`.

**Comment by FlyersPh9** [comment]
Related to #904.
