### ISSUE TITLE
Clicking on anchors also selects row in Table story

### ISSUE THREAD

**Issue by elephantcatdog** [iTwin/iTwinUI#1019]
#### Describe the bug (actual behavior)
On the table story "Disabled Rows", clicking (or tabbing + entering) on the anchors "Click me!" also selects the row.

#### Expected behavior
I think that clicking on the anchors should only do the anchor actions and not select the row.

#### Reproduction
This occurs in storybook on the table story "Disabled Rows": https://itwin.github.io/iTwinUI/react/?path=/story/core-table--disabled-rows
*when #1018 is merged

##### Steps to reproduce
1. Click or tab+enter an anchor. The row is selected.

**Comment by mayank99** [comment]
This is not a bug in Table. To prevent selection, the user will need to call  `stopPropagation`. We already demonstrate this in multiple stories:
https://github.com/iTwin/iTwinUI/blob/3ac13328b3ff877566a2fa54baeb0edd6a5871b2/apps/storybook/src/Table.stories.tsx#L185
https://github.com/iTwin/iTwinUI/blob/3ac13328b3ff877566a2fa54baeb0edd6a5871b2/apps/storybook/src/Table.stories.tsx#L261
