### ISSUE TITLE
Full page modal: not opening properly in iTwinUI storybook

### ISSUE THREAD

**Issue by Chrissy-L** [iTwin/iTwinUI#1022]
#### Describe the bug (actual behavior)
When clicking "Full page modal" and going to "Canvas". Modal slides up and disappears from screen:

https://user-images.githubusercontent.com/122555873/213699629-04af2b07-88b8-440e-89ff-88aadb0eca9c.mp4

When switching to "Docs" the animation is a bit jumpy and slides in from top of the screen instead of bottom:

https://user-images.githubusercontent.com/122555873/213699620-21457c09-7d47-4182-852c-a62ccbfd92f4.mp4

Browser: Chrome Version 109.0.5414.75 (Official Build) (64-bit)
Laptop: HP ZBook 15 _(system information will follow)_

#### Expected behavior
Note that the full page modal is working correctly in the CSS iTwinUI library for me:

https://user-images.githubusercontent.com/122555873/213700695-ea489165-b751-4f79-8e2d-704c2568c2b5.mp4

##### Steps to reproduce
1. Open: https://itwin.github.io/iTwinUI/react/?path=/story/core-modal--full-page-modal
1. Make sure the switch in top left is on "Canvas"
1. Click on button to open full page modal

#### Additional information
--

**Comment by Chrissy-L** [comment]
> This is interesting. The animation is a bit jumpy for me but I cannot reproduce it going out of screen completely.

I just noticed that when the bug happened, my Google Chrome was still on version: **Version 108.0.5359.126** (Official Build) (64-bit)

Now it's updated to: **Version 109.0.5414.75** (Official Build) (64-bit) and now the modal doesn't slide out of the screen anymore!
Although the animation is still a bit jumpy.

**Comment by LostABike** [comment]
I can't seem to reproduce this bug either.

Laptop: HP ZBook 15
Chrome version: Version 111.0.5563.65 (Official Build) (64-bit)
Gif:
![modal test](https://user-images.githubusercontent.com/22462084/225971285-ff3c225a-db2c-43cb-a4b3-0865b7bf3e29.gif)

Tested in: regular mode, incognito mode, all different canvas background settings, dark and light mode

**Comment by mayank99** [comment]
@LostABike  it might be more noticeable here: https://itwinui.bentley.com/docs/dialog#full-page

try in firefox as well

**Comment by LostABike** [comment]
@Chrissy-L This issue has been resolved in v2.8.0.
