### ISSUE TITLE
CSS  menu page changes if scrolling is changed in components

### ISSUE THREAD

**Issue by elephantcatdog** [iTwin/iTwinUI#1041]
#### Describe the bug (actual behavior)

Adding another scrolling menu (or removing the scrolling from the scrolling menu that's there) to the top of the `menu.html` file negatively affects some of the components (namely the skeleton and the header examples). It causes some of the parts to be misaligned and no longer centered. This may also affect the added components so that they may be off-centered also.

![image](https://user-images.githubusercontent.com/37936169/215904011-0f2f7eed-2233-4430-ab95-2cbe30aa3a18.png)
![image](https://user-images.githubusercontent.com/37936169/215904899-4cd267a8-adb6-416d-8602-f2b8584da17f.png)
 
This occurs on the html page itself, not just the test images, but as it's difficult to see I included the test images.

#### Expected behavior
Changing the number of components with scrolling should not affect components that come after it, or the components themselves.

##### Steps to reproduce
1. Open a local version of the iTwinUI project.
2. Either copy and paste the scroll demo or remove options 9-14 from the scroll demo. If you do both the error won't occur.
3. Run css visual tests (`cd .\packages\itwinui-css\` and `yarn test --filter=menu` for faster tests) and look at backstop JS report to see differences.
4. Differences can also be seen on the menu.html page in the browser.

#### Additional information
Is this a problem with only the html page or is it an issue with the css components?

**Comment by mayank99** [comment]
Should be fixed by #1106 as I've added `display: block` to the label/description (previously was `inline` which has a tendency to shift vertically depending on surroundings and line-height).
