### ISSUE TITLE
Table Column Filtering only apply to the current displayed page.

### ISSUE THREAD

**Issue by mathieu-fournier** [iTwin/iTwinUI#1043]
#### Describe the bug (actual behavior)
When applying a column filter in the table, only the displayed page is filtered. 

Here I get the message that tells me that no result contains "1009" in the description.
![image](https://user-images.githubusercontent.com/82905333/216370711-c052caf5-f15f-472e-bc3e-21eff800b661.png)
But when going to a different page, "1009" is present in a result. 
![image](https://user-images.githubusercontent.com/82905333/216370989-6dc9ae9c-2101-43d2-aa32-48b5f9df6df8.png)

#### Expected behavior
The filtering should be applied on all the data in the source.  

#### Reproduction
Link to storybook table (02/02/2023) : 
https://itwin.github.io/iTwinUI/react/?path=/story/core-table--with-manual-paginator
1. Navigate to the storybook link shared above - ^
2. Apply a column filter that includes some data from a different page. (Ex: On page one, filter Description = "1009")
3. Notice that the data does not appear in the table.

#### Additional information
A possible resolution would be to fetch the data again, applying a filtering query.

**Comment by elephantcatdog** [comment]
Hello @mathieu-fournier,

I've fixed this issue in the manual pagination storybook example. Because the data is manually manipulated, the table didn't have all the info it needed, and the filtering also needed to be manual. The story is now called "With Manual Pagination And Filter" to reflect this change.
