### ISSUE TITLE
ComboBox: List container of virtualized boxes not shrinking to content after a change to emptyStateMessage

### ISSUE THREAD

**Issue by SpencerWBarnes** [iTwin/iTwinUI#1050]
#### Describe the bug (actual behavior)
A MenuItemSkeleton is visible then replaced by a smaller message. A small gap can be seen below the message item. This gap disappears after additional interactions with the ComboBox.

#### Expected behavior
A MenuItemSkeleton is visible then replaced by a smaller message. No gaps can be seen around the smaller message.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/itwinui-react-example-forked-804s68?file=/src/App.tsx

##### Steps to reproduce
1. Open ComboBox dropdown and observe the MenuItemSkeleton element
1. Wait 1.5 seconds for the delayed update
1. Observe that the "No Results." message is smaller than the previous MenuItemSkeleton element resulting in a gap beneath

#### Additional information
This bug only occurs to ComboBoxes with `enableVirtualization` set to true. Specifically, it is the result of the containing `iui-surface` div added for virtualization not rerendering and resizing to the new content.

**Comment by elephantcatdog** [comment]
Thanks for your contribution! We've put this one in planned this week.

**Comment by LostABike** [comment]
@SpencerWBarnes It looks like this bug happens in React 17 but not React 18, as @mayank99 has tested reproducing both cases here https://codesandbox.io/s/itwinui-react-example-forked-qk7dyt?file=/src/index.tsx
It would be a good idea/solution if you are able to update your project React version to 18. But let us know if you are not able to do so and we will try to fix it for React 17.

**Comment by mayank99** [comment]
@SpencerWBarnes This is fixed in v[2.4.2](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.4.2) 🚀
