### ISSUE TITLE
Table pager buttons cause page to refresh when inside form tag

### ISSUE THREAD

**Issue by mattl-bentley** [iTwin/iTwinUI#1053]
#### Describe the bug (actual behavior)
Clicking the table pager buttons causes the page to refresh when the table is inside a form tag.

#### Expected behavior
Clicking the page buttons changes pages without refreshing the page.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/paging-page-refresh-w0bpoh?file=/App.tsx:2606-2617

##### Steps to reproduce
1. When the page loads, click page "2" and notice the page refreshes instead of changing pages

#### Additional information
This issue exists in itwinui-react@2.4, but not in 1.x. Comparing the html output, 2.x does not include type="button" for the paging buttons.

![image](https://user-images.githubusercontent.com/110254711/217288089-e605f5ea-76c9-46a4-8c53-c9ca85faf36f.png)

![image](https://user-images.githubusercontent.com/110254711/217287996-abb3e802-07e5-4b6f-b2e1-692980dde2ee.png)

**Comment by mayank99** [comment]
Hey @mattl-bentley. That makes sense the button needs `type='button'`, although I would question putting the whole table in a form; it can cause issues with some screen readers)

Do you want to contribute by creating a pull request? The change would go here: https://github.com/iTwin/iTwinUI/blob/4e43e5ca488d998bd7920c9b30fa85e82d65eeb5/packages/itwinui-react/src/core/Table/TablePaginator.tsx#L173-L175

**Comment by mayank99** [comment]
this is now released in [2.4.1](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.4.1) 🎉

**Comment by mattl-bentley** [comment]
Great, thank you!
