### ISSUE TITLE
Virtualized ComboBox miscalculates height of options

### ISSUE THREAD

**Issue by SpencerWBarnes** [iTwin/iTwinUI#1107]
#### Describe the bug (actual behavior)
The bottom of the options list shows a gap below the last option when using a virtualized combobox where the **second option** has a sublabel and a sufficient number of options without sublabels.

#### Expected behavior
The bottom of the options list stops at the last option.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/gracious-pond-ur3c5g?file=/src/App.tsx

##### Steps to reproduce
1. Open the combobox
1. Observe gap below the last option

#### Additional information
This occurs in both scrollable and unscrollable option lists.
It appears the gap is the result of the scrollable distance being calculated as if every option has a sublabel, accumulating all the height differences from all options without sublabels at the bottom.
Testing seems to suggest this only occurs when the second option has a sublabel.

**Comment by gretanausedaite** [comment]
Comment for developer who takes this issue:
Height calculations are done in VirtualScroll.tsx line 421. This function assumes that all middle children heights are the same.

**Comment by mayank99** [comment]
This issue has been finally fixed in [3.13.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.13.0) 🚀
