### ISSUE TITLE
Carousel: Warning when navigating with arrow keys in React 16.X or below

### ISSUE THREAD

**Issue by 6ar8nas** [iTwin/iTwinUI#1113]
#### Describe the bug (actual behavior)
When a carousel is being used with React 16.X or below, a warning after using arrow keys for navigation through the carousel is visible in the console.
![image](https://user-images.githubusercontent.com/86420873/222811693-6bb32733-86dd-4627-a2fd-85c81b15fe04.png)

#### Expected behavior
Warning in the console does not appear.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/angry-dew-1phjuu

##### Steps to reproduce
1. Hold right arrow key

#### Additional information
Looking into the warning, the potential issue is located at https://github.com/iTwin/iTwinUI/blob/main/packages/itwinui-react/src/core/Carousel/Carousel.tsx#L102, while someone's suggested solution to this can be found at https://stackoverflow.com/a/56629758.

**Comment by gretanausedaite** [comment]
Hi!
Thank you for the bug report and initial investigation.

Would you be interested in contributing to our library?  
The best place to start is [Contributing guide](https://github.com/iTwin/iTwinUI/blob/main/CONTRIBUTING.md).

**Comment by 6ar8nas** [comment]
Sure, will further investigate it and try creating a pull request myself.

**Comment by mayank99** [comment]
🚀 This is now available in 2.7.0
