### ISSUE TITLE
iTwinUI V2 `Toaster` breaks V1 styles [Incremental migration]

### ISSUE THREAD

**Issue by Woyken** [iTwin/iTwinUI#1128]
#### Describe the bug (actual behavior)
Every time we trigger a toast that has a close button, parent app using itwin v1 styles break.

#### Expected behavior
Toasts don't assign `.iui-root` class to `body` element

#### Reproduction
<https://stackblitz.com/edit/vitejs-vite-gknvln?file=src%2FV2.jsx>

##### Steps to reproduce
1. Parent app uses itwin V1
2. Add <ThemeProvider/> from V2
3. Render components from V2 (all ok)
4. Trigger Toast with options `{hasCloseButton: true}`.
5. Parent app using V1 styles break.  `.iui-root` was added to `body` element

#### Additional information
"@itwin/itwinui-react@1": "1.48.2",
"@itwin/itwinui-css@0": "0.63.2",
"@itwin/itwinui-react@2": "2.6.0",
"@itwin/itwinui-css@1": "1.7.0",

I assume problem is because toasts are rendered via `ReactDom.createRoot` and not `React.Portal`. Whole provider tree that was before it means nothing to it. It lives in it's own react world. And when time comes to `useTheme` it doesn't find anything up the tree, so it assigns new theme to `document.body`
It will probably ignore dark theme from the provider too

@mayank99 This might be major block for incremental migration <https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v2-migration-guide#incremental-migration>

**Comment by mayank99** [comment]
Hey @Woyken, thanks for the issue.

To fix the root cause (`createRoot` call creating a separate tree), we would need to change the toaster API. We cannot use `createPortal` because the toaster api is imperative, it doesn't render anything. I'd imagine we could rework it to be a hook (so that it has access to context):
```jsx
const toaster = useToaster();
return (
  <Button onClick={() => toaster.positive('Success!')}>show</Button>
);
```
---

For now, I've created a quick fix that manually checks for the presence of v1 classes. #1130

**Comment by Woyken** [comment]
Thanks for this quick fix, it should help with couple more issues I'm running into too (hard to reproduce in small example).

As for the API, I believe hooks would be the way to go. Less hacks on the itwinui side, and toasts would respect theme styling.
