### ISSUE TITLE
Tooltip: Difficulty using tooltip inside absolutely positioned element

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1137]
Discovered a situation where the `<Tooltip>` is appended to the DOM, but not positioned correctly when adding to an absolutely positioned element inside a `<Modal>` component.

It looks like setting the height on the Modal is a contributing factor as well.

See the full reproducible example here.
https://codesandbox.io/s/tooltip-on-absolute-positioning-k6nbvp

![Tooltip in dialog](https://user-images.githubusercontent.com/15036346/225374850-5c772878-e5d7-4a46-9027-499732c29d11.gif)

**Comment by elephantcatdog** [comment]
Hi Eric, thank you for bringing this to our attention. I've looked into this a bit and haven't found a solution yet, or if this is a bug on our end. 

However, I did find that putting tooltips on buttons within our `ModalButtonBar` works, if that's helpful. Here's an updated sandbox for you to look at: https://codesandbox.io/s/tooltip-on-absolute-positioning-forked-98mp2v

**Comment by mayank99** [comment]
should be fixed in v3 https://codesandbox.io/s/tooltip-on-absolute-positioning-forked-fkck8q?file=/src/App.tsx
