### ISSUE TITLE
LabeledSelect: New property for styling the container that shows the selected elements

### ISSUE THREAD

**Issue by SetropLeo** [iTwin/iTwinUI#1171]
## Feature

Currently, we have parameter options for styling only the outer container (**style** and **selectStyle** parameters) from LabeledSelect. 

What I suppose might be a good feature for this component is creating a new parameter that will allow developers for styling the container that shows the selected elements.

I want to be able to change the styles from the container that handles the selected elements

## Examples
- As default, we have the component with the following styles: 

![LabeledSelect1](https://user-images.githubusercontent.com/77972979/228657187-b54d21dc-4687-4805-9485-641f8724ccb3.jpg)

- We can set styles using the **style** parameter and the result will be that:

![LabeledSelect3](https://user-images.githubusercontent.com/77972979/228657204-26c770ef-45ab-4781-a92a-06c8369ec50d.jpg)

- We can set styles using the **selectStyle** parameter and the result will be that:

![LabeledSelect2](https://user-images.githubusercontent.com/77972979/228657436-e6487ac6-3604-4a0b-b578-79cef2fa8ef7.jpg)

- But I want the following result: 

![LabeledSelect4](https://user-images.githubusercontent.com/77972979/228657887-269ab3fa-5fe1-41d7-8f11-a7461a5e831c.jpg)

Can you guys help me with this? 
Thanks.

**Comment by SetropLeo** [comment]
Hello!

I want to change the style of the container that shows the selected items, not the style of the selected items themselves. 

I need to be able to do that because I'm working on a system revamp and we are moving all of the features to use the iTwinUI trying to keep all of the functionalities working the same way as the legacy project. 
In the legacy project, the user was able to create custom styles for the components that are shown on the screen. 

I already took a look at the StoryBook and tried to implement what we need using all of the available parameter options but none of them allowed us to customize the component in the way we needed.

**Comment by gretanausedaite** [comment]
Could you provide a screenshot of what you are trying to achieve? Or ping us in our Teams channel to have more in depth discussion on what you need.

**Comment by SetropLeo** [comment]
Sure I can! 

Just to clarify, the component we had in the legacy project was a MultiSelect component without any input to filter. It's just a list of elements that the user can select as many options as he wants.

- The pure old component from the legacy project looks like that:
![image](https://user-images.githubusercontent.com/77972979/228854794-9159d5bc-e8e8-4964-a825-93d3eb3c3b3d.png)

- The user was allowed to change the styles of the component using a dashboard from our system and, as an example, the component style could be like that:
![image](https://user-images.githubusercontent.com/77972979/228851513-2e97266c-6fbe-49e4-8151-95ad132b65e6.png)

<br />

Knowing that iTwin doesn't have any component like that, we decided to change to the component that would be the closest in functionality, and the LabeledSelect fills in nicely.

<br />

- This one in the image below is the LabeledSelect from iTwin:
![image](https://user-images.githubusercontent.com/77972979/228856299-f35df6ed-ed1e-4356-a5cf-b207edc16733.png)

<br />

The only problem is: the LabeledSelect component doesn't have any property that allows us to change the style of the input container (On the HTML of the component it is actually a div, but visually it looks like an input).

<br />

- We want to be able to achieve the following result (I made it by editing the page HTML):
![image](https://user-images.githubusercontent.com/77972979/228857936-9d9b3f9d-3104-4c27-b2b4-866055da7bda.png)

- The container in which I need to be able to handle the styles is the one in the image: 
![image](https://user-images.githubusercontent.com/77972979/228859136-26b59adf-4e24-4a8c-9dea-83773c7b2274.png)

<br />

I tried to explain as much of the situation as possible. The focus of this whole issue is that I need to be able to apply styles to the container that I showed above and currently the LabeledSelect doesn't have any property that allows me to edit this. The functionalities of the component work well.

**Comment by mayank99** [comment]
@SetropLeo This is now possible in [v2.10.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.10.0) after #1238 using the new `triggerProps` prop.

You'll be able to pass a custom class and use it in your CSS.
```jsx
<LabeledSelect
 ...
 triggerProps={{ className: 'my-multiselect' }}
/>
```
```css
.my-multiselect {
  background: yellow;
}
```
(You could also pass `style` inside `triggerProps`, but `className` is preferred)
