### ISSUE TITLE
Dispaly Anchor as code

### ISSUE THREAD

**Issue by linasburneika** [iTwin/iTwinUI#1214]
There is a need on documentation pages to show code snippets that also act as links. Prior version v2 it was rendered with proper Anchor color, but styles of Code takes priority in the latest version.
```
<Anchor as="code" href="/my-method.md"><Code>MyMethod</Code></Anchor>
```

**Comment by mayank99** [comment]
@linasburneika This is now fixed in `@itwin/itwinui-react@2.9.1`. You'll be able to do this:
```jsx
<Anchor href='/my-method'>
  <Code>MyMethod</Code>
</Anchor>
```

Note: you do _not_ need `as` prop because you want the underlying HTML to have an `<a>` element (see below). Using `as='code'` would mean it is no longer a link, so clicking on it would *not* navigate.
```html
<a href='/my-method'>
  <code>MyMethod</code>
</a>
```
