### ISSUE TITLE
Sidenav buttons style is overriden by button

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#125]
#### Steps to reproduce
Seems to be depending on the order of css files imports, no easy reproduction steps.

#### Expected behavior
Borders on hover are not this much dark @FlyersPh9 

#### Additional information
Button style overrride sidenav button styles:

![image](https://user-images.githubusercontent.com/1904889/120503552-665d5900-c391-11eb-996c-4b0f5975c1c7.png)

**Comment by mayank99** [comment]
Released in itwinui-css v0.18.1 and already available in [itwinui-react v1.7.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.7.0)
