### ISSUE TITLE
Button Group Overflow at Start

### ISSUE THREAD

**Issue by NancyMcCallB** [iTwin/iTwinUI#1252]
### Discussed in https://github.com/iTwin/iTwinUI/discussions/1089

<div type='discussions-op-text'>

<sup>Originally posted by **NancyMcCallB** February 22, 2023</sup>
When setting the ButtonGroup's overflow to start, the overflow button renders at the beginning of the group, but the buttons overflow from the end of the group. This is counter-intuitive and not likely to be what is desired.</div>

Here's a link to an iTwinjs sandbox to demonstrate. https://www.itwinjs.org/sandboxes/NancyMcCall/Overlay%20Toolbar%20with%20Overflow

**Comment by mayank99** [comment]
@NancyMcCallB I've created a PR #1278, but I think this change could be considered breaking because the updated calculations will affect how many and which items are rendered.
