### ISSUE TITLE
Add "Split Button" type of Header Button

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#128]
#### Feature
Current header buttons are either dropdown buttons (click on the full button and get the dropdown) or simple buttons (click on the button and do something.)

In the header, we would need the "main" part of the button to do something (For example, bring me to the currently "active" project and do something with it) and the drop down part to select a different project and do likely the same thing.

Current connect implementation does this but is rather tricky to click only on the carret image, which does a different thing than the rest of the button.

Not 100% sure of how it should look, but the split button might be a starting point, where the 2 different click targets  highlights separately, I dont know if the current | in the middle of the component would do well

### Basic

![image](https://user-images.githubusercontent.com/1904889/120532652-e5608a80-c3ad-11eb-9b38-68dc830ae423.png)

### Main hover

![image](https://user-images.githubusercontent.com/1904889/120532619-d7ab0500-c3ad-11eb-990d-bd83f0f6c2c9.png)

### Drop down

![image](https://user-images.githubusercontent.com/1904889/120532503-b9dda000-c3ad-11eb-9557-b406db427995.png)

(Examples made by pasting header button code in split button "left" button, so styling is not great)

**Comment by FlyersPh9** [comment]
We already have a [split menu button](https://itwin.github.io/iTwinUI/backstop/minified/button.html#demo-split-menu) component.  You might be able to use the CSS from `.iui-button-split-menu` and `.iui-borderless` to help with this.

What I was originally imagining was something like this:
![bad_header-split-button_1](https://user-images.githubusercontent.com/849817/124025734-cfe77c00-d9be-11eb-956a-60df92124934.png)
![bad_header-split-button_2](https://user-images.githubusercontent.com/849817/124025738-d1b13f80-d9be-11eb-9559-35262bb26442.png)

But I think that looks awful. 🤮 What if we try something more custom just for the header buttons?  How about something like this (pay attention to where the cursor is for hover interactions):
![header-split-button_1](https://user-images.githubusercontent.com/849817/124025818-ea215a00-d9be-11eb-874c-e9f414d07a6e.png)
![header-split-button_2](https://user-images.githubusercontent.com/849817/124025821-eab9f080-d9be-11eb-863b-c254feeedeaa.png)
![header-split-button_3](https://user-images.githubusercontent.com/849817/124025822-eab9f080-d9be-11eb-9749-65861da0a8c0.png)
![header-split-button_4](https://user-images.githubusercontent.com/849817/124025823-eab9f080-d9be-11eb-85b3-3de94d1e904c.png)
![header-split-button_5](https://user-images.githubusercontent.com/849817/124025825-eab9f080-d9be-11eb-9e35-2507fa0dc13a.png)

For the expanding arrow split button portion, we can make something like the red area be the touch target area.  The image below is a quick Photoshop hack job, so we'd want the circle & arrow icon to be centered within the touch target area.
![header-split-button_touch_target_area](https://user-images.githubusercontent.com/849817/124026109-44221f80-d9bf-11eb-8b63-cc3732b30acc.png)
