### ISSUE TITLE
Expandable Block Component: New props to style header and content container

### ISSUE THREAD

**Issue by SetropLeo** [iTwin/iTwinUI#1292]
#### Feature
New properties to handle styles for the Header and Content container. 

#### Examples

Ideally, the idea is to have two separate props for handling styles, one for Header and one for the Content container. 

I want to implement background color, borders, and other styles in each part of the Expandable Block component. 
I'm trying to reach something like that: 
![image](https://github.com/iTwin/iTwinUI/assets/77972979/5e464118-f8da-437b-a1e7-db709f2249ee)

And currently, I am just achieving this:
![image](https://github.com/iTwin/iTwinUI/assets/77972979/0edd15ee-2074-4dbc-8926-8f1bbc17c00c)

**Comment by mayank99** [comment]
@SetropLeo iTwinUI doesn't have a `Section` component. Are you sure this issue has been opened in correct repo?

**Comment by SetropLeo** [comment]
@mayank99 Oh sorry, Iwas referring to the ExpandableBlock component.

**Comment by mayank99** [comment]
@SetropLeo We are currently working on our next major release, and I think we could handle this issue as part of it, by offering subcomponents for header/content.

In the meantime, you should be able to use CSS selectors to target the individual styles.
```jsx
<ExpandableBlock className='my-expandable-block'>...</ExpandableBlock>
```
```css
.my-expandable-block > :first-child {
  // header styles go here
}
.my-expandable-block > :last-child {
  // content styles go here
}
```

Hope that helps
