### ISSUE TITLE
[DropdownMenu] Difficult to select submenu items

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1301]
`.iui-menu` is supposed to have `max-height: var(--iui-menu-max-height)`. However, this does not appear to be defined.

![image](https://github.com/iTwin/iTwinUI/assets/15036346/4e8caece-a497-4a06-8071-59911f5d074d)

In our app, we have defined our own max height to create a scrollbar for long menus. When the scrollbar is manually added, it becomes very difficult to select any submenu items, as the pop up menu usually disappears as soon as the mouse is over the scrollbar area.

![Submenu close](https://github.com/iTwin/iTwinUI/assets/15036346/68a08baa-d7b1-4063-b699-33a56def0ddf)

Looking at the code it seems as if I manually add the `.iui-scroll` class to the dropdown menu, it will calculate a max height for me. However, I don't think as a consumer I am supposed to use the iui classes, and the difficult hover issue is still present.

Reproducible at https://codesandbox.io/s/overflow-dropdown-menu-8sfjx1?file=/src/App.tsx.

**Comment by mayank99** [comment]
Related issues:
- #879
- #653

**Comment by rseydler** [comment]
I'm also faced with a scroll issue.. in that the scroll bars do not appear at all. I have a headerbutton that overflows but no scroll bars show. Sample here - https://codesandbox.io/s/pedantic-chandrasekhar-n7xchg?file=/src/App.tsx

**Comment by mayank99** [comment]
This has been fixed in #1576 and released in [2.11.8](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.8) 🚀
