### ISSUE TITLE
NonIdealState: Svg does not cover whole illustration container 

### ISSUE THREAD

**Issue by 6ar8nas** [iTwin/iTwinUI#1308]
#### Describe the bug (actual behavior)
Component's `NonIdealState` illustration's currently accurately works with `@itwin/itwinui-illustrations-react`, which are of fixed bigger size. However, using any other svg uses its native height and width and doesn't fill the illustration container. 

#### Expected behavior
Component's `NonIdealState` illustration's svg has the height and width inherited from the illustration container.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/little-https-jlzhnt?file=/src/App.tsx

#### Additional information
This might get the job done, although a `size` prop might be needed, as the container is of 3x2 ratio, while the icons are 1x1 and could possibly be expected to be smaller, as [it might seem bloated](https://codesandbox.io/s/cocky-cannon-sjhizo?file=/src/App.tsx)
``` scss
.iui-non-ideal-state-illustration > svg {
  height: inherit;
  width: inherit;
}
```

**Comment by mayank99** [comment]
Hmm, I think the intent was for the wrapping div around the illustration to serve as a sort of "upper bound". It should work fine for any svg that is big enough.

What's the use case for using `NonIdealState` with an icon that's normally 16x16? Scaling that icon up to be giant-size would not look very good.

**Comment by 6ar8nas** [comment]
> It should work fine for any svg that is big enough.

You're correct here emphasizing that any svg **that is big enough** works fine. But the issue was created to suggest addressing that **big enough** part.

> What's the use case for using NonIdealState with an icon that's normally 16x16?

In some situations I personally find the icons more user friendly to be displayed compared to an illustration error svg (especially when the state is non-critical).
E.g.:
- an illustration 403 (Forbidden):
![image](https://github.com/iTwin/iTwinUI/assets/86420873/743b70ef-d131-4bd8-a131-7189ec037566)
- an illustration 404 (Not found):
![image](https://github.com/iTwin/iTwinUI/assets/86420873/16ac6c7d-923b-410b-9c84-6f6e819bafbc)

> Scaling that icon up to be giant-size would not look very good.

Agreed - in the above given examples, I have made the illustration container smaller to tailor better for the requirements of the components. While inheriting would either way help, as in that case the user would only need to adjust the illustration container height and width, this is partially why in the issue I've mentioned some `size` prop as a suggestion.

**Comment by mayank99** [comment]
@6ar8nas Have you tried using the `<Icon>` component? It lets you control the size.

**Comment by 6ar8nas** [comment]
After further testing it out, I found that while `<Icon>` didn't quite cut it, the expected outcome can be achieved by simply applying a className to the svg, hence I am closing this issue. Thanks.
