### ISSUE TITLE
Dialog: positioning

### ISSUE THREAD

**Issue by gretanausedaite** [iTwin/iTwinUI#1313]
#### Feature

Positions for Dialog:
- CSS created in https://github.com/iTwin/iTwinUI/pull/679/files#diff-68df02c08d0adce541e49bba164c2c72d0c346f659f79c8a76495a884769741aR56 but missing React implementation
- Is also needed for: https://github.com/iTwin/iTwinUI/issues/667

#### Examples

An optional `placement` prop can be added to `Dialog`.

```jsx
<Dialog placement='top-left'>
```
```jsx
<Dialog placement='bottom-left'>
```
```jsx
<Dialog placement='top-right'>
```
```jsx
<Dialog placement='bottom-right'>
```

The prop will likely need to be stored in [`DialogContext`](https://github.com/iTwin/iTwinUI/blob/dev/packages/itwinui-react/src/core/Dialog/DialogContext.tsx) (by [`Dialog`](https://github.com/iTwin/iTwinUI/blob/dev/packages/itwinui-react/src/core/Dialog/Dialog.tsx#L46)) and then used inside [`DialogMain`](https://github.com/iTwin/iTwinUI/blob/dev/packages/itwinui-react/src/core/Dialog/DialogMain.tsx#L56) to set the `data-iui-placement` attribute.

**Comment by coderr01** [comment]
@gretanausedaite i would like to contribute on the issue

**Comment by mayank99** [comment]
Hey @coderr01, thanks for your interest, but this issue was actually created for @marashad001 (who also wrote the original CSS for it in #679).

If you are still interested in contributing to iTwinUI, may I recommend #924? Or we can find you a different task depending on your skills and interest.
