### ISSUE TITLE
Tabs: ResizeObserver loop limit error

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#1318]
#### Describe the bug (actual behavior)
In React 17, when a tab is clicked in a `Tabs` component, a "ResizeObserver loop limit" error display in the WebDev server overlay (that most iTwin.js application uses).

#### Expected behavior
No error should be raised as this is the intended behavior.

#### Reproduction
Link to a minimal repro: https://github.com/raplemie/itwinui-tabs-resizer-issue

##### Steps to reproduce
1. Click on tab "B"

![image](https://github.com/iTwin/iTwinUI/assets/1904889/a32acd96-c863-47a9-9ac0-2cffa4e6b6a7)

#### Additional information

see #1317, however in this case, nothing in the UI is actually changing.

**Comment by mayank99** [comment]
Lets track this together with #1317.
