### ISSUE TITLE
Facing issue with "@itwin/itwinui-css": "^1.11.1" and "@itwin/map-layers": "^4.0.0-dev.44",  packages..

### ISSUE THREAD

**Issue by Praful-Bentley** [iTwin/iTwinUI#1332]
Facing issue with "@itwin/itwinui-css": "^1.11.1" and "@itwin/map-layers": "^4.0.0-dev.44",  packages..

The itwinui-css package seems to be missing scss folder and corresponding files required in map-layers package.

Error: import file cannot be resolved: "@import "~@itwin/itwinui-css/scss/style/typography"

 Can you please help?

![image](https://github.com/iTwin/iTwinUI/assets/135814108/f767dc3f-4be5-4472-9461-5937e8c9c4f1)

**Comment by veekeys** [comment]
Please, do not spam all over the places. If you have chosen discussions, leave it there. Creating multiple instances of same question will not fasten up the answers.

Error is clear: map-layers is still using itwinui-react@1 version. That means, you cannot migrate your application to v2 until all your deps have migrated to v2.
[Read more here about incremental migration.](https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v2-migration-guide#incremental-migration)

**Comment by mdastous-bentley** [comment]
Which version of @itwin\map-layers are you using?  version 5.0.0  is using itwinui v2, please give it a try.
