### ISSUE TITLE
Small addition to CONTRIBUTING.md for React Unit tests

### ISSUE THREAD

**Issue by marashad001** [iTwin/iTwinUI#1336]
This is a quick and easy fix:  Add how to run react unit tests for just one component. Currently only mentions how to run unit tests in full.

<img width="922" alt="Screenshot 2023-06-07 150426" src="https://github.com/iTwin/iTwinUI/assets/105806085/d293ccf0-a9e1-4252-b197-f1bad5946d05">

**Comment by mayank99** [comment]
Just submit a PR directly, no need for an issue as it's a small change and doesn't affect our deliverables.

**Comment by mayank99** [comment]
also it's already mentioned in the contributing guide:
https://github.com/iTwin/iTwinUI/blob/dev/CONTRIBUTING.md#running-bespoke-commands

![](https://github.com/iTwin/iTwinUI/assets/9084735/c2f7b45b-91dd-495c-8faa-ac28875cd4e8)
