### ISSUE TITLE
Converting all css to use logical properties

### ISSUE THREAD

**Issue by gretanausedaite** [iTwin/iTwinUI#1366]
E.g. margin-left -> margin-inline-start, etc. 
This lint rule will come in handy: https://github.com/csstools/stylelint-use-logical

To do:
- [x] Install lint rule
- [x] Fix css (in all repo) accordingly
- [x] Run visual tests and make sure everything seems right

**Comment by mayank99** [comment]
Reopening this because there are a bunch of places in our React components, where we use physical properties as inline styles. These still need to be converted to logical properties and linted if possible.
