### ISSUE TITLE
[`DropdownButton`] Add support for "high-visibility" styleType

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1394]
The `<DropdownButton>` component works nicely if adding a `styleType="high-visibility"`, but this isn't supported by the `DropdownButtonProps`.

This works in my source code, but doesn't in code sandbox; unsure why the discrepancy.

**(Local)**
![image](https://github.com/iTwin/iTwinUI/assets/15036346/6b4c169f-c9bb-41be-b7dc-aa292e42fe2d)
![High vis dropdown](https://github.com/iTwin/iTwinUI/assets/15036346/cada71c0-77ff-49f3-8e60-3a3936105406)

**(Code sandbox https://codesandbox.io/s/high-visibility-dropdown-button-mxvlcd?file=/src/App.tsx)**
![Lo vis dropdown](https://github.com/iTwin/iTwinUI/assets/15036346/e5f78f21-e128-4871-a2dd-a8b68583e403)

**Comment by mayank99** [comment]
hey @HaveSpacesuit, this is something we can support, sure.

(as for the CRA, it is not working because you have a typo in `"high-visibility"`)

**Comment by mayank99** [comment]
This is now supported in [`2.12.0`](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.0)!
