### ISSUE TITLE
Table: Column reordering is messed up if columns are defined with header

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#1428]
Columns reordering is messed up. Seems its taking wrong column while dragging and messing up the positions.

https://stackblitz.com/edit/vitejs-vite-rtydzc?file=src%2FV2.jsx,src%2FApp.jsx,src%2FV1.jsx

The fix I accidentally found is to define columns just as simple array. (added as unused const in code sandbox)

**Comment by mayank99** [comment]
> The fix I accidentally found is to define columns just as simple array.

This is the expected format. https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v2-migration-guide#breaking-changes

Don't you get a warning when you use the old format?

**Comment by veekeys** [comment]
> > The fix I accidentally found is to define columns just as simple array.
> 
> This is the expected format. https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v2-migration-guide#breaking-changes
> 
> Don't you get a warning when you use the old format?

Where Im supposed to look for that warning?
According to docs `The old format will also continue to work if you update to version 2.5.0 or later.`. Also, I think you were making some changes so old format will be staying too, no? There were issues with types, from what I remember...

**Comment by mayank99** [comment]
there should be a warning in the browser console.

the old format was re-added mainly for backwards compatibility, but it certainly hasn't been tested with all features, so you'd be better off just using the new format.

the issue with types is weird. i think in v3 we could remove the old columns format and copy the corrected types into our codebase. there is some explanation here: https://github.com/iTwin/iTwinUI/issues/886
