### ISSUE TITLE
Evaluate exporting functionality from itwinui that is currently being used by civil

### ISSUE THREAD

**Issue by Rock2000** [iTwin/iTwinUI#1429]
Pineapple code, which Civil relies on, has a case where they import something that is not exported. We should evaluate if these can be exported officially, or if these apps should change their code. We're trying to support iTwin Studio and these deep imports are not allowed in that platform.

In Pineapple's @bentley/itwin-common/src/component/colorpickerpopover/ColorPickerPopover.tsx there is:
    import { Popover } from "@itwin/itwinui-react/cjs/core/utils";

**Comment by mayank99** [comment]
Pineapple should get rid of that import. It is an internal utility not meant to be used publicly.
