### ISSUE TITLE
Evaluate exporting functionality from itwin that is currently being used

### ISSUE THREAD

**Issue by Rock2000** [iTwin/iTwinUI#1432]
Pineapple code (which Civil relies on) has a case where they import something that is not exported. We should evaluate if this can be exported officially, or if these apps should change their code. We're trying to support iTwin Studio and this deep import is not allowed in that platform.

In Pineapple's @bentley/itwin-common/src/component/colorpickerpopover/ColorPickerPopover.tsx there is:
  import { Popover } from "@itwin/itwinui-react/cjs/core/utils";

Can we export Popover?

**Comment by mayank99** [comment]
Please don't open duplicate issues. As I mentioned in #1429, `Popover` is an internal utility not meant to be used outside iTwinUI.

For now, you will need to bring your own Popover utility; you could use [`floating-ui`](https://floating-ui.com/docs/popover) or [`radix-ui`](https://www.radix-ui.com/docs/primitives/components/popover) or anything else you might find.

In the next major version, we will rewrite our `Popover` on top of `floating-ui` and expose it publicly. You can track this issue: https://github.com/iTwin/iTwinUI/issues/914.
