### ISSUE TITLE
ComboBox: inaccurate selected items count at small widths

### ISSUE THREAD

**Issue by mattl-bentley** [iTwin/iTwinUI#1438]
#### Describe the bug (actual behavior)

Multiselect combobox displays the wrong count under certain conditions. See repro details.

#### Expected behavior

Visible tags match selected items.

#### Reproduction
See [codesandbox](https://codesandbox.io/s/blue-glitter-mmlzfy?file=/src/App.tsx) for an example. Notice a single element is selected, but the tag says "+2 item(s)."

The order you select the items changes the display behavior. 

1. clear selected items
2. select "Lofts"
3. select "Townhomes".
Notice the inaccurate count.
4. clear selected items
5. select "Townhomes"
6. select "Lofts"
Notice only "Townhomes" is displayed.

**Comment by gretanausedaite** [comment]
Should be fixed in [2.12.13](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.13)
