### ISSUE TITLE
Popover component does not respect "arrow" prop value

### ISSUE THREAD

**Issue by manwadkaraksh** [iTwin/iTwinUI#1462]
#### Describe the bug (actual behavior)
The Popover component does not show popover with arrow even when the "arrow" prop is set to true.

![image](https://github.com/iTwin/iTwinUI/assets/97600048/b4d9afbc-0399-4758-991e-d6c75ff22faa)

#### Expected behavior
Popover component should respect arrow value passed through props and show the popover with/without arrow depending upon the value passed.

**Comment by mayank99** [comment]
this is working as intended, we do not support arrow and do not plan to add it, as it's not recommended from a UX standpoint.

in the next version, that prop will be removed to avoid confusion.
