### ISSUE TITLE
Table: Body scroll is misaligning body cell with header one

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#1503]
This is reproducible in Storybook too (on some machines and browsers)
https://itwin.github.io/iTwinUI/react/?path=/story/core-table--full-2

<img width="321" alt="image" src="https://github.com/iTwin/iTwinUI/assets/81580355/3a9b2cd4-82b1-48e7-8401-e5ebdbd24456">

**Comment by mayank99** [comment]
Fixed in [2.12.3](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.3)
