### ISSUE TITLE
Table is sorted on enter key when it should only be filtered

### ISSUE THREAD

**Issue by AAugustBentley** [iTwin/iTwinUI#1550]
When adding a filter to a column, if I am using enter key instead of "Apply" button, it filters the column **AND** sorts (as column header is focused, so table takes that the enter key means sorting as well)

![image](https://github.com/iTwin/iTwinUI/assets/129863171/d5bedac8-8ca9-47b1-a757-29830da319f1)
![image](https://github.com/iTwin/iTwinUI/assets/129863171/89cd594d-f96c-4226-afdf-5c83318a157f)

Would expect that when filter is active, sorting would not be triggered as well.

itwinui-react version: 2.12.6

**Comment by gretanausedaite** [comment]
Hi!
Thanks for reporting this issue. 

We are currently working on our next major release so won't have time for this.
The fastest way to have this fixes is contributing to our repo! [Our contributing guide](https://github.com/iTwin/iTwinUI/blob/main/CONTRIBUTING.md)

**Comment by mayank99** [comment]
Should be fixed in 3.0.7
