### ISSUE TITLE
ComboBox: lazy loading options

### ISSUE THREAD

**Issue by mattl-bentley** [iTwin/iTwinUI#1553]
#### Describe the bug (actual behavior)

Lazy loading ComboBox items using the onShow event provides inconsistent results. The first time they load fine, if the selected value exists in the new list all other options disappear except the selected option.

Link to codesandbox is below. Obviously it's not exactly how we're loading options but it shows the same results. 

If there's a better way to do this please let me know.

#### Expected behavior

Options passed in are visible.

#### Reproduction
Link to a minimal repro: 
https://codesandbox.io/s/dreamy-murdock-mcftnn

##### Steps to reproduce
1. Expand combobox
1. Select an item or click outside to collapse the items
1. Expand combobox again, notice only one option is available

**Comment by mayank99** [comment]
if you are changing `options` frequently, it might help to set a `key` on the `<ComboBox>` itself so that all state is reset when options change.

**Comment by mattl-bentley** [comment]
@mayank99 A static key or one that changes when the options change like [this](https://codesandbox.io/s/dreamy-murdock-mcftnn?file=/src/App.tsx:1608-1625)? Unfortunately neither one worked for me. Updating the key in onShow causes the popup to never appear. onHide has the same issue with showing only the selected option.

The only way I've found to make it work is to revert the options to only the selected option onHide then onShow will show the new list ([sandbox](https://codesandbox.io/s/dreamy-murdock-mcftnn?file=/src/App.tsx:1631-1778)).

**Comment by mayank99** [comment]
your key should probably be based on the thing that is changing the options.
See https://codesandbox.io/s/adoring-banzai-z33fqp?file=/src/App.tsx

https://github.com/iTwin/iTwinUI/assets/9084735/b46552fb-6a74-43cf-aad0-8a2d120a2958

**Comment by mattl-bentley** [comment]
Yeah, your sample works but it's set up a little differently. The initial options aren't lazy loaded. It seems like adding an onShow handler breaks the functionality. For example, move the load function call to onShow like below. Then select an option in the first box, then expand it again - notice only a single option is available.

`onShow={() => loadOptionsForCategory(category)}`

**Comment by mayank99** [comment]
Still works fine for me. https://codesandbox.io/s/combobox-key-z33fqp-forked-lwwrhp?file=/src/App.tsx

https://github.com/iTwin/iTwinUI/assets/9084735/d8a2dbf3-1cc5-4e0d-b1f4-8ac6297dac82

If you can create a clear repro with explanation, we can help you out.

**Comment by mattl-bentley** [comment]
Made some changes based on your last sandbox. Select an option in both ddl's then expand the child ddl again and wait for the promise to resolve. I'm seeing the options disappear except the selected option.

https://codesandbox.io/s/combobox-key-z33fqp-forked-mnhv8c?file=/src/App.tsx

**Comment by mayank99** [comment]
this is because you are passing a new instance of `options` every time the list is shown, which i think triggers a useEffect somewhere inside our component. (the dependencies are checked using `Object.is`).

generally the fix is to memoize your options, or better yet, create the options outside the component, so that you can be sure you get the same object on each render.

**Comment by mattl-bentley** [comment]
Typically if props or state change you'd expect the component to re-render. I'll look into changing my code so it uses the same instance instead.

Thanks.
