### ISSUE TITLE
Type test all files in `itwinui-react`

### ISSUE THREAD

**Issue by rohan-kadkol** [iTwin/iTwinUI#1561]
From https://github.com/iTwin/iTwinUI/pull/1514#discussion_r1322903047.
Related threads: https://github.com/iTwin/iTwinUI/pull/1514#discussion_r1323039029, https://github.com/iTwin/iTwinUI/pull/1514#discussion_r1316509275

Instead of having `tsc`  in `build` just type check the files that will be built, we should type check *all* files. By *all* files, I mean even the unit test files.

This is because unit tests currently pass even with type errors in them. So there is no way of detecting some very specific type error if it only occurs in the unit test files.

**Comment by mayank99** [comment]
Folding into #1571 for ease of tracking.
