### ISSUE TITLE
iTwin UI v2 `Toaster` and `Modal` not working with v1 [Incremental migration]

### ISSUE THREAD

**Issue by williamkbentley** [iTwin/iTwinUI#1582]
#### Describe the bug (actual behavior)
`Toaster` and `Model`s do not work well together during incremental migration.

#### Expected behavior
v1 `Toast` and `Modal`s and v2 `Toast` and `Modal`s can live in harmony together.

#### Reproduction
Link to a minimal repro: []()

https://stackblitz.com/edit/vitejs-vite-bhnkuh?file=src%2FV2.jsx,src%2FV1.jsx

##### Steps to reproduce
1. Click v2 Toast button (Toast appears v2 styled)
1. Click v1 Toast button (Toast appears v2 styled)
1. Click v2 Toast button (Nothing appears)
---

1. Click v2 Modal button (Nothing appears)
1. Click v1 Modal button (v1 Modal appears)
---

1. Click v1 Toast button (Toast appears v1 styled)
1. Click v2 Toast button (Toast appears v2 styled)
1. Click v1 Toast button (Nothing appears)

#### Additional information
Similar to #1128
Linked [stackblitz ](https://stackblitz.com/edit/vitejs-vite-bhnkuh?file=src%2FV2.jsx,package.json) is using v1: 1.48.3 and v2: 2.12.8

**Comment by mayank99** [comment]
This bug sounds valid and we should probably investigate it. Our portal logic might be broken.

For now, I would suggest using the v1 toaster (even within v2 parts) and using [`modalRootId`](https://stackblitz.com/edit/vitejs-vite-acigwk?file=src%2FV2.jsx%3AL39-L39) for bypassing the portal logic in Modal.

We can look into this further after we are done with our v3 work.

**Comment by williamkbentley** [comment]
I might suggest adding some of this info to the incremental upgrade docs (which are very thorough and very useful and very much appreciated)

**Comment by mayank99** [comment]
this should be fixed in 2.12.10
