### ISSUE TITLE
Tree: select density

### ISSUE THREAD

**Issue by michaalx** [iTwin/iTwinUI#1593]
#### Feature
In iTwin X we want to have a condensed Tree, i.e. with lower tree nodes. It would be great to have an option in Tree component to choose that. Perhaps it's reasonable to add a new property in Tree, let's say `spacing` or `density`. 
#### Examples
dense:
![image](https://github.com/iTwin/iTwinUI/assets/23118333/a7fac3e8-96e6-4019-bea5-3016c8735d6c)
normal:
![image](https://github.com/iTwin/iTwinUI/assets/23118333/de57a465-2d6e-4ad2-8c57-3fa4895b3036)

**Comment by mayank99** [comment]
i think this is something we could support.

there are some additional things we'll need to adjust in the smaller density tree:
- using `size="small" for the expander buttons
- making nested horizontal spacing tighter

**Comment by mayank99** [comment]
This is now available in [3.1.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.1.0)
