### ISSUE TITLE
Table: global filter is ignored if data is refreshed

### ISSUE THREAD

**Issue by AAugustBentley** [iTwin/iTwinUI#1599]
If there is a global filter set but the table data changes, the global filter is ignored (the table is not filtered but the value is still visible in input). Setting the global filter value again does not help until it is changed in some way.

sandbox: https://codesandbox.io/s/global-itwinui-filter-not-working-zktzys

**Comment by mayank99** [comment]
you can pass `autoResetGlobalFilter={false}` if you want the filters to persist after data changes.

see docs: https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/api/useGlobalFilter.md
