### ISSUE TITLE
Multiple toast messages cannot be closed in a single call

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#1604]
#### Describe the bug (actual behavior)

If multiple toast messages are open at the same time, and the returned "close" method is used for all of them, only the last "close" call will work, and only one toast message will actually go away. (Same behavior independent of the type being "persisting" or "temporary")

#### Expected behavior

I expect all the "close" call to close its related toast message, even if I want to close multiple (typically, "all") at the same time.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/agitated-burnell-6vz332?file=/src/App.tsx

##### Steps to reproduce
1. Click on Single (Single toast appear)
2. Click on Close beneath it (Sigle toast goes away)
3. Click on One (One toast appear)
4. Click on Two (Two toast appear)
5. Click on Three (Three toast appear)
6. Click on Close All (Only three will go away, Here I expect One, Two and Three to be gone)
7. Click on Close All (Only two will go away)
8. Click on Close All (One will go away)

#### Additional information

Note that the function is running the 3 close functions if they exists, in the same order, one, two, three, and the order of "disparition" is not related to the opening order, you can click Three, Two, One, and Close All, and Three will always go away first, and the others will remain.

**Comment by mayank99** [comment]
So this should work as intended in v3 (we did a rewrite), but in the meantime you can close each toast in separate macrotasks. (I'm assuming you're aware of `closeAll` and need finer control over each toast.)

```js
const forceClose = async ({ close }) => {
  await new Promise(resolve => setTimeout(() => {
    close();
    resolve(null);
  }))
}
await one.close();
await two.close();
await three.close();
```
https://codesandbox.io/s/vigorous-rain-z9fhj4?file=/src/App.tsx

**Comment by raplemie** [comment]
Even with those `forceClose`, the `onRemove` is called only for the last one.

**Comment by mayank99** [comment]
I think `onRemove` is unreliable in general. Since you are manually closing the toasts, you know exactly when it will be removed, so you can do this:

```js
const forceClose = async (toast, setToast) => {
  await new Promise(resolve => setTimeout(() => {
    toast.close();
    setToast(null)
    resolve(null);
  }))
};
await forceClose(one, setOne);
await forceClose(two, setTwo);
await forceClose(three, setThree);
```
