### ISSUE TITLE
FileInput: Support directory upload

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1611]
#### Feature
File Input should support exposing the file structure inside dropped directories. We'd like to migrate from [react-dropzone](https://github.com/react-dropzone/react-dropzone) to the iTwin implementation, but we cannot until we can support dropping a file structure inside a directory.

#### Examples

![Folder upload](https://github.com/iTwin/iTwinUI/assets/15036346/c5c2df04-d54b-45ae-b74f-8d3167538cfe)

**Comment by mayank99** [comment]
Hey @HaveSpacesuit, could you provide some more details about what you're looking for from `FileUpload`? It is designed as a generic wrapper without opinions on how you use it, so the directory use case might already be achievable.

**Comment by HaveSpacesuit** [comment]
@mayank99 I think it would be necessary to change [`onFileDropped`](https://github.com/iTwin/iTwinUI/blob/a2400dd93e9316a43b424e401d0faeec2f314329/packages/itwinui-react/src/core/FileUpload/FileUpload.tsx#L86C34-L86C34) from `e.dataTransfer?.files` to `e.dataTransfer?.items`.

We use this in our app. We can iterate through the list something like
```ts
const dataTransferItemList = event.dataTransfer?.items;

for (let i = 0; i < dataTransferItemList.length; i++) {
  const dataTransferItem = dataTansferItemList[i];
  const fileSystemEntry = dataTransferItem.webkitGetAsEntry();

  if (fileSystemEntry.isFile) {
    const file = dataTransferItem.getAsFile();
    files.push(file);
  } else {
    directories.push(fileSystemEntry)
  }    
}
```

You can use other methods in the [File API](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API) to recursively get all folders and files dropped.

**Comment by mayank99** [comment]
Would having access to `onDrop` be enough?

In v2, we are missing types for it, but you can still pass your own `onDrop` to override the internal handler. (In v3, there will be proper types too.)

https://github.com/iTwin/iTwinUI/blob/9cd9d8ebbf47bb6c4717b8bec2192b64ed12b546/packages/itwinui-react/src/core/FileUpload/FileUpload.tsx#L92-L94

**Comment by HaveSpacesuit** [comment]
Yes, using `onDrop` works, though it isn't exposed.

Here is a working example, though it could be nice if iTwin could provide some of this functionality.
https://codesandbox.io/s/folder-upload-m9fkrn?file=/src/App.tsx

![Nested drag and drop](https://github.com/iTwin/iTwinUI/assets/15036346/c1278f20-be36-4197-b7ee-580fa24911fb)

**Comment by mayank99** [comment]
This is now supported in [3.1.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.1.0). Basically, the `onFileDropped` prop now gets a second argument which you can use to get information about the directory structure.

```tsx
<FileUpload
  onFileDropped={async (_, event) => {
    const directoryStructure =
      await dataTransferItemListToDirectoryStructure(
        event.dataTransfer.items,
      );
    setDirectoryStructure(directoryStructure);
  }}
>
```
