### ISSUE TITLE
Nested submenus in dropdown is not being shown

### ISSUE THREAD

**Issue by IvanJK97** [iTwin/iTwinUI#1616]
#### Describe the bug (actual behavior)

Dropdown menu component's is not displaying nested submenus. It shows the first layer, but not subsequent layers.

#### Expected behavior

Should show nested submenus regardless of depth

#### Reproduction
Link to a minimal repro: 
Can be seen in Storybook demo: https://itwin.github.io/iTwinUI/react/?path=/story/core-dropdownmenu--submenu
Observe that Item 4's submenu items 7 and 8 are not showing.

##### Steps to reproduce
1.  Create a dropdown menu with a menu item with a submenu
1.  In the submenu, create another menu item with a submenu
1.  Items are not shown in the nested submenu

#### Additional information

Seems to be a fairly recent regression. Eric mentioned storybook was working last week.

**Comment by mayank99** [comment]
Should be fixed in 2.12.17

https://itwin.github.io/iTwinUI/legacy/v2/react/?path=/story/core-dropdownmenu--submenu
