### ISSUE TITLE
TabsPanel changes width upon first change of the tab

### ISSUE THREAD

**Issue by rohan-kadkol** [iTwin/iTwinUI#1627]
> May not be related to this PR, but just noticed some shift in the width of the tabs panel in the "Vertical Overflow" story
>
> [14.webm](https://github.com/iTwin/iTwinUI/assets/45748283/2bb1bd2a-facc-408b-bb07-a4b5e5ffbda0)

_Originally posted by @rohan-kadkol in https://github.com/iTwin/iTwinUI/pull/1548#discussion_r1355274285_

> I am on a Windows 11 + Edge 117. What I did was:
> * Press tab to focus the selected "Item 11`"
> * Press up or down

_Originally posted by @rohan-kadkol in https://github.com/iTwin/iTwinUI/pull/1548#discussion_r1355294539_

**Comment by mayank99** [comment]
I still cannot reproduce on Mac, so would be nice if @gretanausedaite can verify and add repro steps.

**Comment by gretanausedaite** [comment]
I can reproduce it.
It seems this visual bug is present only on first mount.

**Comment by rohan-kadkol** [comment]
I tried finding the cause for this width jump but unfortunately still couldn't find it. So I thought to share my observations to get others' ideas.

<details>
<summary>Detailed screen recordings of the issue</summary>

On Chrome/Edge, I noticed that in the Vertical Tabs, whenever a scroll bar is present (when vertical overflow), then there are some jumps in the width.

https://github.com/iTwin/iTwinUI/assets/45748283/64eaafa8-c5c9-41f7-85b0-1e5e0b38da94

0:00-0:13 = In the horizontal tabs, whenever there is a horizontal overflow, the scrollbar creates place between the tabs list and the tab content. This seems correct.
0:13-0:20 = In the vertical tabs, we first see the non-overflow state. So there is no scrollbar. We also see that the padding for the last very long item is correct. Again, everything looks correct so far.
0:20-0:29 = But when we trigger an overflow, there seems to be some issue with the padding.
0:29-0:38 = Doing the first click on any button creates an abrupt jump in the width. But after that first click, the padding issue gets fixed.
0:38-end = We now notice then whenever we toggle the "show all" button, regardless of whether the vertical tabs overflows or not, the initial render always seems to have some padding issue that is always fixed upon the first click

---

On Firefox, the horizontal tabs work the same way as Chrome.

https://github.com/iTwin/iTwinUI/assets/45748283/dfc1289a-043e-4fad-8817-008a60a0902a

The vertical tabs gives the same padding issue as Edge/Chrome. However, this time, clicking any button for the first time does not fix the padding issue.

</details>

Some thoughts/observations:

* This issue didn't originate from #1548 (v3). Since this issue can also be seen in the v2 storybook's [Tabs -> VerticalOverflow story](https://itwin.github.io/iTwinUI/legacy/v2/react/?path=/story/core-tabs--vertical-overflow).
* I guess this is a CSS issue since different browsers give different behaviors when trying to repro. Adding `scrollbar-gutter: stable` to the vertical tabs fixes the problem on all three browsers. However, the gap between the tabs-list and the tabs-content even when there is no scroll is not ideal.
* The issue appears even when the use of `useContainerWidth()` in Tabs is removed.

Some oberservations made jointly with @mayank99:
* The jumping in the width upon the first click of any tab appears only some of the times and with some specific data (see repro below for one of those cases).
* `white-space: nowrap` may be contributing to the issue?
* The width jump is seen even when the very long tab item is not used.

https://github.com/iTwin/iTwinUI/commit/252c230d07cc6790a58ab8b4edd2e980140bed31: Contains a good repro (in the vite playground) along with some trial and error made jointly with @mayank99.

**Comment by mayank99** [comment]
I was able to stop the layout shift on click, by using this hack on first mount:
```js
const originalOverflow = tablist.style.overflow;
tablist.style.overflow = 'visible';
queueMicrotask(() => {
  tablist.style.overflow = originalOverflow;
});
```
but it's not great, because the content is still getting clipped on firefox (notice the absence of right border).

| chrome | firefox |
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/bcd7ac17-7ce5-4005-95d7-5522a55d6f26) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/ede59ec5-5d53-47e7-a27d-fb31063cc96e) |
