### ISSUE TITLE
Shift (with ctrl) unselection in table does not work

### ISSUE THREAD

**Issue by AAugustBentley** [iTwin/iTwinUI#1628]
#### Describe the bug (actual behavior)
When there are already some rows selected, unselecting one row (with ctrl or checkbox) and then using shift with ctrl does not unselect the rest of the rows.
![shift unselect](https://github.com/iTwin/iTwinUI/assets/129863171/866714a1-42f0-439c-a598-c7cc0000801f)

To make matters worse, the row that is considered `lastSelectedRowId` by the state is shown as unselected but `newState` considers it selected (row id 8 in the example)
![image](https://github.com/iTwin/iTwinUI/assets/129863171/e52be605-2367-4c71-bf8b-914d768e5e15)

#### Expected behavior
All the rows that were selected by shift from the first unselected `lastSelectedRowId` should be unselected.
![image](https://github.com/iTwin/iTwinUI/assets/129863171/e49e7694-45a2-40c0-96c1-8774893b27b2)

The same way it is in windows's file explorer:
![windows shift unselect](https://github.com/iTwin/iTwinUI/assets/129863171/8d5788df-f4e4-4497-aaa4-8284d1ab7cae)

##### Steps to reproduce
- Select multiple rows
- Click with ctrl or checkbox any row that was selected
- Use shift with ctrl to select any other row (doesn't have to be selected)

#### Additional information
Related issues: [#880](https://github.com/iTwin/iTwinUI-react/issues/880) and [#879](https://github.com/iTwin/iTwinUI-react/issues/879)

**Comment by rohan-kadkol** [comment]
As mentioned partially in our direct messages, I was able to reproduce both the issues. Like you said, the second one is a significant bug indeed.

I copied the Table -> Draggable Columns story into a [codesandbox](https://codesandbox.io/s/focused-darkness-p9sjdj?file=/src/App.tsx) to try to reproduce this.

**Comment by rohan-kadkol** [comment]
Will be fixed in 3.0.3 🎉

**Comment by AAugustBentley** [comment]
> Fixed in [v3.0.3](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.0.3) 🎉

Hey @rohan-kadkol, will this be added to v2? Not all will update to v3 soon, especially knowing that the last time my team updated from v1 to v2, it took half a year to fix all the stabilization problems.

**Comment by rohan-kadkol** [comment]
> > Fixed in [v3.0.3](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.0.3) 🎉
> 
> Hey @rohan-kadkol, will this be added to v2? Not all will update to v3 soon, especially knowing that the last time my team updated from v1 to v2, it took half a year to fix all the stabilization problems.

Sounds good, we backported it to v2 also. Should be fixed in [v2.12.16](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.16) 🎉

**Comment by mayank99** [comment]
Also would like to add: v2 will only get critical fixes for the next ~6 months. This particular fix was backported because the second part of this issue (mismatch between true and visual state) is indeed critical.
