### ISSUE TITLE
Spinner in Headerbutton is out of the icon area

### ISSUE THREAD

**Issue by rseydler** [iTwin/iTwinUI#1641]
#### Describe the bug (actual behavior)
When you put a spinner in a headerbutton icon it doesn't show in the icon space, rather half in and half out to the right. This only happens with the latest version of itwinui-react 2.12.11. If you go back to the previous version the behaviour is correct.
#### Expected behavior
Spinner should be inside the headerbutton icon area as per itwinui-react 2.7
#### Reproduction
Sandbox is here - https://codesandbox.io/s/exciting-christian-q7ml4c?file=/src/App.tsx / https://q7ml4c.csb.app/ added a button so you can toggle the spinner on an off.

##### Steps to reproduce
![image](https://github.com/iTwin/iTwinUI/assets/82630635/2bbfe10a-56e6-4dd8-bbc6-75e6f8787e44)
![image](https://github.com/iTwin/iTwinUI/assets/82630635/7e93f8e2-7c14-4ae9-ae98-5094a6259d8a)

Use a headerbutton with a starticon of progressradial

if you downgrade -
![image](https://github.com/iTwin/iTwinUI/assets/82630635/81f4083a-3ed9-4808-a02a-d57f2649fa27)
![image](https://github.com/iTwin/iTwinUI/assets/82630635/e09a3d84-bfa4-49f7-ba17-4feed408ab88)

**Comment by mayank99** [comment]
We have never officially supported passing spinners into buttons. If it worked in the past, that's an accident (a happy one?). I think in this case it should be a simple fix though; I'll create a PR.

**Comment by gretanausedaite** [comment]
Should be fixed in [v2.12.14](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.14).

**Comment by rseydler** [comment]
Thanks for the fix!
