### ISSUE TITLE
Table : Set row id

### ISSUE THREAD

**Issue by mathieu-fournier** [iTwin/iTwinUI#1647]
I would like to be able to set a custom id for my table rows. 
Ex: 
![image](https://github.com/iTwin/iTwinUI/assets/82905333/7c1d5b52-fb4c-4f26-acc2-ead375f0d45a)

Current workaround: 
Trick typescript by extanding the GetRowProps class manually.
![image](https://github.com/iTwin/iTwinUI/assets/82905333/7fb92c3d-69e3-4f38-bf69-be1ffad13168)

**Comment by rohan-kadkol** [comment]
You can use the `getRowId` prop to set the custom row ids.

```jsx
<Table
  ...
  getRowId={(row) => row.productId}
/>
```

You can find all other Table props on our [Table documentation page (WIP)](https://itwinui.bentley.com/docs/table#props).

**Comment by mathieu-fournier** [comment]
The ```getRowId``` prop is not working. 

I added a console log when ```getRowId``` is called : 
![image](https://github.com/iTwin/iTwinUI/assets/82905333/8b82fcbc-1a93-475c-b1be-517c28ecda16)
![image](https://github.com/iTwin/iTwinUI/assets/82905333/ad967871-a29c-4958-88ce-3e24950a56eb)

Still, the table row has no Id : 
![image](https://github.com/iTwin/iTwinUI/assets/82905333/7b135d37-3a13-47f5-b957-d5fc8f52be4b)

**Comment by rohan-kadkol** [comment]
Actually, upon testing it myself, I noticed no type error when trying to do this. I made a [codesandbox](https://codesandbox.io/s/recursing-pike-mttlt8?file=/src/App.tsx) for this.

In the sandbox, on L95, we are modifying the internal row id using `getRowId`. Then on L83, we are setting the HTML id to the internal row id that we set using `getRowId`.

After discussing over DMs, looks like there was some confusion between `getRowId` that modifies the internal data ids and `rowProps`'s id that sets the HTML div id. Our Table documentation page is WIP. We will document the difference between them when we work on that page. You can track our documentation progress in https://github.com/iTwin/iTwinUI/issues/961

**Comment by mathieu-fournier** [comment]
From a user perspective. 
```rowProps``` sets the html element properties.
I would also expect ```getRowId``` to set the html element id.

**Comment by mathieu-fournier** [comment]
@rohan-kadkol 
Also, I did not found a way to add an id to expander button : 
![image](https://github.com/iTwin/iTwinUI/assets/82905333/f4c6e6fc-b5be-4138-bf00-350559493ff8)

This makes writing tests less trivial. 
I suggest that the expander button sets it's own id based on the row id. 
Ex: 
id="<custom row id>-expander-button"

**Comment by mayank99** [comment]
you could use `aria-expanded` that gets set on the row expander button

**Comment by mathieu-fournier** [comment]
`aria-expanded` is present on every rows, it does not help to select and click a specific expander button.
Currently, I must do document traversal to get a specific expander button, which is flaky by nature. 
Pseudo-code Example : 
```
const myRow = $('#customRowId');
const myExpander = myRow.prev('.iui-table-row-expander');    // Jquery traversal to get a previous sibling.
```

**Comment by mayank99** [comment]
you can find the first instance of `aria-expanded` inside the row (since you already have the row id):
```js
$(`#${rowId} [aria-expanded]`)
```

![](https://github.com/iTwin/iTwinUI/assets/9084735/39c7d791-a1e0-40ea-af6e-e56f9c247f2c)

https://codesandbox.io/s/sparkling-water-683j53?file=/src/App.tsx

i don't think it makes sense to add ids to expander buttons by default, but we could theoretically support passing a custom id to the expander buttons if you have ideas on a comfortable API.

**Comment by mathieu-fournier** [comment]
I added a id to my cell, not the row. my bad.
