### ISSUE TITLE
`<IconButton>` within a vertical `<ButtonGroup>` tooltip obscures adjacent buttons

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#1652]
#### Feature
When `<IconButton>` is placed within `<ButtonGroup orientation='vertical'>` the tooltip appears above the hovered button covering up the button above it.  Ideally either the system is smart enough to place the tooltip in the correct position or allow the developer to define the tooltip placement location.

#### Examples

The 2nd button is hovered and it's tooltip is covering up the button above it.
![Screenshot 2023-10-24 at 10 27 01 AM](https://github.com/iTwin/iTwinUI/assets/849817/fb31c845-b6e3-4673-9054-c5eaa9a0a300)

**Comment by mayank99** [comment]
Current workaround:
```tsx
<Tooltip content="Edit" ariaStrategy="label">
  <IconButton><SvgEdit /></IconButton>
</Tooltip>
```
