### ISSUE TITLE
Have `ThemeProvider` theme `inherit` inherit the `highContrast` theme option as well.

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#1653]
#### Feature
Provide a simple way for `ThemeProviders` used in components to also use the same `highContrast` option value.

#### Examples
When theme is `inherit`, the `highContrast` option would be inherited as well. (Currently this is dropped, so High contrast application will have normal contrast component within them)

**Comment by mayank99** [comment]
fixed in 3.0.2 and 2.12.15

**Comment by raplemie** [comment]
Awesome, thanks!
