### ISSUE TITLE
`<Select>` will crash when used with react v17.x.x

### ISSUE THREAD

**Issue by mdastous-bentley** [iTwin/iTwinUI#1657]
#### Describe the bug (actual behavior)
![image](https://github.com/iTwin/iTwinUI/assets/8309609/8666f192-fae8-44cd-9964-080705ab6411)

#### Reproduction
[Link to a minimal repro](https://codesandbox.io/s/young-shadow-5lvddj?file=/src/App.tsx)

##### Steps to reproduce
Click to expand the `<Select> `component

Only occurs with `@itwin\itwinui-react` 3.0.0

**Comment by mayank99** [comment]
spent some time looking into this; i've traced the problem to this line getting called on every render, thus causing even more re-renders:

https://github.com/iTwin/iTwinUI/blob/7d313a2b21fcbaa45b92e75e3a7e7de7eef4c538/packages/itwinui-react/src/core/Select/Select.tsx#L445

**Comment by mayank99** [comment]
fixed in 3.0.1
