### ISSUE TITLE
Table component throws bad setState warning

### ISSUE THREAD

**Issue by amonigor** [iTwin/iTwinUI#1658]
#### Describe the bug (actual behavior)
When using the Table component, if you pass a setState as a onSelect prop, the React will throw this error:
![image](https://github.com/iTwin/iTwinUI/assets/48227869/1a6ec197-a25e-4a48-a7cf-403f31d96dc3)
Even if you wrap the setState inside a useCallback, the error will continue the same.

#### Reproduction
Link to a minimal repro: [codesandbox](https://codesandbox.io/s/xenodochial-surf-zsqfqv?file=/src/App.tsx)

#### Additional information
It only occurs in the first click.

**Comment by rohan-kadkol** [comment]
After looking at it briefly, looks like this happens even in `v2.12.14` ([forked sandbox](https://codesandbox.io/s/still-fire-rsmwxy?file=/src/App.tsx)). We will investigate this further.

**Comment by mayank99** [comment]
This is a known issue that happens because `onSelect` is called inside a reducer and should not contain any other immediate state updates.

You can fix this by moving your state update into a micro-task so that it waits for the render to finish.
```js
onSelect={(s) => {
  queueMicrotask(() => setFake(s));
}}
```
