### ISSUE TITLE
Chevron icon placement issue in Expandable subrows in Table

### ISSUE THREAD

**Issue by Pooja17-bentley** [iTwin/iTwinUI#1671]
The chevron icon used in [expandable subrows](https://itwin.github.io/iTwinUI/legacy/v2/react/?path=/story/core-table--expandable-subrows) is currently displayed within same cell as other content. I believe it should be displayed in a separate cell , similar to how it is displayed in [expandable ](https://itwin.github.io/iTwinUI/legacy/v2/react/?path=/story/core-table--expandable) view .

When using expandable subrows , the current layout is not as intended. I would like to achieve layout similar to below image.
![image](https://github.com/iTwin/iTwinUI/assets/148448690/3a11351f-60a0-43c0-b69d-915854e8394c)

I tried by adding blank column but ended up creating incorrect layout.
Is there any way to align the chevron with the requirement?

**Comment by mayank99** [comment]
thanks for the issue

this is done on purpose; expandable subrows can be nested infinite levels deep, so it would get very complicated to use two different columns for the expander icon button and the other content while preserving alignment.

maybe in the future we could make the expandable content button also use a single cell, but for now this is considered working as-intended, so i'll close this.
