### ISSUE TITLE
`Select` menu is offset when opened for 2nd time

### ISSUE THREAD

**Issue by Woyken** [iTwin/iTwinUI#1679]
#### Describe the bug (actual behavior)

`<Select popoverProps={{ placement: 'bottom-end' }} />`
1. Click once, menu opens properly
2. Close menu
3. Click, menu opens with offset

Similar bug is visible in storybook too.
<https://itwin.github.io/iTwinUI/react/?story=input--select--basic>
If you open it for seconds time, big empty space appears below it

#### Expected behavior

Menu opens in same position every time

#### Reproduction
Link to a minimal repro: 
<https://stackblitz.com/edit/stackblitz-starters-ywppax>

##### Steps to reproduce
`<Select popoverProps={{ placement: 'bottom-end' }} />`
1. Click once, menu opens properly
2. Close menu
3. Click, menu opens with offset

#### Additional information

![itwinuibug](https://github.com/iTwin/iTwinUI/assets/13166802/3a530b57-6775-4b90-b78f-702cf5fa7cc8)

**Comment by mayank99** [comment]
Hey @Woyken, thanks for the issue.

There is definitely a bug here, but I'm curious what your use case is for `'bottom-end'` and how you expect it to look. Generally, `Select` menus should use `'bottom-start'`.

**Comment by Woyken** [comment]
I'm replacing existing components and this one is located on the right side
![image](https://github.com/iTwin/iTwinUI/assets/13166802/369ee9bb-06c5-44b7-905a-393859644dab)
Due to this bug, it looked like this:
![image](https://github.com/iTwin/iTwinUI/assets/13166802/69399c85-37d6-4eaf-b666-d211df4d7e6e)
It wouldn't fit on the page, that's why I tried `bottom-end` and it was even worse.
(I was using React 17, this bug reproduced every time, only when using React 18 it appears on 2nd try)

**Comment by mayank99** [comment]
seems like this is a regression introduced in #1661 where we fixed a react 17 specific bug. still looking into it.

in the meantime you may want to use `@itwin/itwinui-react@3.0.0` if you're on react 18.

**Comment by mayank99** [comment]
Should be fixed in [v3.0.4](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.0.4)
