### ISSUE TITLE
error - 'Dialog' is not exported from '@itwin/itwinui-react' - When building from grouping and mapping 

### ISSUE THREAD

**Issue by StuartKeelingWSP** [iTwin/iTwinUI#1694]
#### Describe the bug (actual behavior)
When attempting to build from the repo grouping and mapping, candcconsulting (Glen Worral), I recieve the error 'Dialog' is not exported from '@itwin/itwinui-react'

#### Expected behavior
Previously this had not been a problem until earlier in 2023, even if I attempt to use a earlier commit I experience this problem, however Glen does not and so we are scratching our heads as to what the problem is

#### Reproduction
Link to a minimal repro: https://github.com/candcconsulting/GroupingandMapping/tree/WSP_2022_Commit

##### Steps to reproduce
1. open in vs code
2. yarn build from GroupingandMapping\packages\app>

**Comment by mayank99** [comment]
This is happening because you are force resolving to a _very_ old version of `@itwin/itwinui-react` which does not have Dialog. https://github.com/candcconsulting/GroupingandMapping/blob/WSP_2022_Commit/package.json#L72

Try upgrading to the latest v1 patch (`1.48.3`) or better yet, v2 or v3

**Comment by StuartKeelingWSP** [comment]
Hi Mayank,

Thanks for your response, I have tried the latest v1 patch however I receive another error:

Failed to compile.

.***@***.***\itwinui-react\esm\core\Backdrop\Backdrop.js
Cannot find module: ***@***.***/itwinui-css/css/backdrop.css'. Make sure this package is installed.

Do you have any ideas for this?

Thanks for your help

Stuart
[WSP Logo]<https://www.wsp.com/en-GB/>


Stuart Keeling
Digital Technician – Rail Stations






Confidential
This message, including any document or file attached, is intended only for the addressee and may contain privileged and/or confidential information. Any other person is strictly prohibited from reading, using, disclosing or copying this message. If you have received this message in error, please notify the sender and delete the message. Thank you. WSP UK Limited, a limited company registered in England & Wales with registered number 01383511. Registered office: WSP House, 70 Chancery Lane, London, WC2A 1AF.

**Comment by mayank99** [comment]
This might be because you have an older, incompatible version of itwinui-css. Try force resolving that too.

> ```
> "@itwin/itwinui-css": "^0.63.3",
> "@itwin/itwinui-react": "^1.48.3"
> ```

**Comment by StuartKeelingWSP** [comment]
HI Mayank,


After re-installing with ***@***.***/itwinui-css": "^0.63.3” , and checking the version with npm list @itwin/itwinui-css, I receive the following:

***@***.***

If I try and build I still get the same error

.***@***.***\itwinui-react\esm\core\Backdrop\Backdrop.js
Cannot find module: ***@***.***/itwinui-css/css/backdrop.css'. Make sure this package is installed.

Thanks for your support

Stuart
[WSP Logo]<https://www.wsp.com/en-GB/>


Stuart Keeling
Digital Technician – Rail Stations






Confidential
This message, including any document or file attached, is intended only for the addressee and may contain privileged and/or confidential information. Any other person is strictly prohibited from reading, using, disclosing or copying this message. If you have received this message in error, please notify the sender and delete the message. Thank you. WSP UK Limited, a limited company registered in England & Wales with registered number 01383511. Registered office: WSP House, 70 Chancery Lane, London, WC2A 1AF.

**Comment by mayank99** [comment]
It looks like some of the information is not making through to GitHub. Could you try commenting on the website instead of replying to the email? Also it would be useful to have an updated repo link.
