### ISSUE TITLE
Toast: Toast can re-appear when triggered by a different toast

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1719]
This one takes some weird configuration, but it was a bug in our production app.

**Steps**
- Open a toast with `{ type: 'persisting' }`
- Immediately use the handle to close the toast
- Open a second non-persisting toast
- (The first toast is closed before has a chance to show on screen, the second toast is visible)

- Open a different toast with `{ type: 'persisting' }`
- After some time, close it with the handle
- Open another non-persisting toast

- At this point the very original toast re-appears along with the final toast

Here is a code sandbox reproduction.
https://codesandbox.io/p/sandbox/replace-toast-55xp79

![Toast appears in immediate action](https://github.com/iTwin/iTwinUI/assets/15036346/bc923496-a516-4a03-a2ea-1345e35db75a)

A temporary workaround we are using is to wrap the second toast in `setTimeout` to allow the first toast time to render and then be removed.

**Comment by mayank99** [comment]
Because of the way react works, you can't rely on multiple sequential state updates to be processed reliably, especially when doing async work.

Could you try wrapping the first toaster call in [`flushSync`](https://react.dev/reference/react-dom/flushSync)?
