### ISSUE TITLE
V2/V3 Theme synchronisation

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#1730]
#### Describe the bug (actual behavior)

V3 ThemeProvider do not sync with V2 ThemeProvider when the theme changes

#### Expected behavior

Every component that inherit theme should have the same theme than its container.

#### Reproduction
Link to a minimal repro: 
https://stackblitz.com/edit/vitejs-vite-do9c8e?file=src%2FV2.jsx

##### Steps to reproduce
1. Application will start in dark mode and everything is synched
1. Use the "Theme" dropdown and switch to light
1. V2 section will be in light theme, V3 will stay in dark theme

**Comment by mayank99** [comment]
This is now fixed and released in 3.1.0
