### ISSUE TITLE
Combobox style input props overrides padding-left in multiselect

### ISSUE THREAD

**Issue by luizfe00** [iTwin/iTwinUI#1759]
#### Description

When I pass a style to input props in combobox component, even if I don't override the padding-left property (it can even be an empty object for the style property) I lose the inline style for padding-left and the text pointer is stuck at the beginning of the input, because of that, when I have selected options I cannot see what I type into the field when trying to search for a value inside my options.

#### Expected behavior

That the styles passed inside styleProps are merged with the styles needed in the control, and not completely overridden. 

#### Reproduction
Link to a minimal repro: [sandbox](https://codesandbox.io/p/sandbox/currying-meadow-ww29c8?file=%2Fsrc%2FApp.tsx%3A34%2C40)

##### Steps to reproduce
1. Click on the combobox
1. Type anything
1. See that the text is behind the selected options

**Comment by mayank99** [comment]
fixed in 3.2.1

**Comment by jfisher-bentley** [comment]
> fixed in 3.2.1

Could this be pushed back to v2.x as well?

**Comment by mayank99** [comment]
backported to 2.12.20
