### ISSUE TITLE
Test types across all pertinent parts of the repo

### ISSUE THREAD

**Issue by rohan-kadkol** [iTwin/iTwinUI#1781]
Post merge TODO from #1514

Tasks:
* Need to test types for all components files, and not just files for a few components like `Table` (#1514), `Select` & `LabeledSelect` (#1774)
* Also test any other pertinent places
* Update/Shorten the `tsconfig.test.json` accordingly (https://github.com/iTwin/iTwinUI/pull/1780#discussion_r1449253904)

**Comment by mayank99** [comment]
Duplicate of #1561, which is already tracked in #1571 along with any other non-user facing tasks.
