### ISSUE TITLE
Dialog becomes off-center when browser window is resized

### ISSUE THREAD

**Issue by ajmiam** [iTwin/iTwinUI#1789]
#### Describe the bug (actual behavior)
Using v2's Dialog component (not full-page), when I resize the browser window, the dialog becomes off-center and sometimes partially moves off the top or left side of the screen.  It's especially noticeable with horizontal resizing, but also subtly occurs with vertical resizing.

Normal appearance:
![image](https://github.com/iTwin/iTwinUI/assets/25464058/a7e1983d-d4f4-4e1f-96e9-9592b62cfb55)

Appearance after resizing window:
![image](https://github.com/iTwin/iTwinUI/assets/25464058/fc8d205c-a257-4454-a1c1-6cfc6e320751)

#### Expected behavior
The dialog should stay centered, with about the same proportion of space on each of the 4 sides as it had when it was initially displayed.

#### Reproduction
Link to a minimal repro: [Example](https://stackblitz.com/edit/github-xmpyql?file=package.json,src%2Fmain.tsx)

Note: You'll need to click "Open in new tab" and then "Link to project" to get the preview into its own window so you can better see the effects of resizing.

![image](https://github.com/iTwin/iTwinUI/assets/25464058/165dccaa-35a9-4d3e-bc5a-077346404c01)

##### Steps to reproduce
1. Create a `Dialog` component with some content
2. View the page in the browser
3. Press the Restore/Maximize button in the browser, and/or drag the window resizing handles horizontally and/or vertically to see the dialog box become off-centered

#### Additional information
An inline `transform` style with specific pixel translations automatically gets added to the component, in addition to the `transform` style (with percent translations) already set for its class in CSS.  If I disable the inline style and keep the style in CSS, the dialog stays centered after a resize, as expected:  (Here, the "good" style is circled in green, and the "bad" style is circled in red.)

![image](https://github.com/iTwin/iTwinUI/assets/25464058/37e8f959-4c5d-463b-ad0e-29eb48a907c1)

**Comment by rohan-kadkol** [comment]
Thanks for the issue. Another user had reported this recently. When we investigated it a short while back, we realized that the issue might have started since #1693. We will investigate this further.

**Comment by mayank99** [comment]
This also happens in v3. #1693 was done to fix #1551, which we get a lot more complaints about.

(Thinking out loud here) The proper fix to both issues might involve reworking the CSS to avoid percentages, so that we don't need any rounding in JS. We were talking about refactoring the dialog to use flex positioning in v3, which might avoid the issue altogether. #1770 is another related issue with these rounded transforms.

I think we can look into this after we are done with our current tasks. If the fix is simple enough, we'll backport it to v2.

**Comment by ajmiam** [comment]
Ah, I do see the blurriness problem when I disable the inline transform.  It doesn't affect label text, but it does affect text values inside inputs and text in a table.

It seems like the root problem of this particular issue is that the inline transform style (which I assume is the rounded value) doesn't get updated as the window resizes.  Adding a listener for that might be enough to fix this for modals that are laid out relative to the whole window.  However, if a modal can be laid out relative to a chosen containing element and not the whole window, then reacting to a resize of that container might be trickier if it can change size for reasons other than the whole window being resized....

Using flex styles does seem like a good long-term plan.

**Comment by Juliakas** [comment]
We are also experiencing this issue, but in addition to that - whenever the size of the Modal changes (lets say table data is fetched so it stretched), it doesn't get centered properly as inline `transform: translate` does not get updated. We worked around it and overrided it with
```css
{
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) !important;
}
```
but then the blurry text issue persists, so I am currently trying to work around and use flex layouts for such cases. Is there any good reason not to use flex based centering for dialogs?

**Comment by mayank99** [comment]
I'm thinking of reverting #1693. I was looking into #1551 again, and found that setting `overflow: visible` on the dialog element might be enough to fix the blurring; no rounded transform needed.

I will need some help confirming this though. Could you leave a 👍 on this comment if this works in your application? (or 👎 if it doesn't). Try just adding `overflow: visible` as an inline style on the dialog element and unchecking the rounded inline `transform` style.

![image](https://github.com/iTwin/iTwinUI/assets/9084735/b79c67b8-48b5-45ca-803e-ffe4bd33ef8e)

/cc @ajmiam @Juliakas @AAugustBentley @HaveSpacesuit @mattl-bentley 

---

For more context, the `overflow: hidden` was added mainly to avoid content floating outside when the dialog is resized to be too small. This isn't a concern for non-resizable dialogs, and also shouldn't be a problem when using `Dialog.Content` (or `ModalContent`), which is a requirement in v3 anyway.

**Comment by mathieu-fournier** [comment]
> @Juliakas You should probably set a fixed height on your table so that it doesn't grow when data is fetched. Generally it's good to minimize content shift.
> 
> The intended centering is supposed to be not in the middle of the screen but slightly above it, which becomes complicated with flex. We are looking into it though.

To move the dialog up just a bit, we could put a empty div with some height below the dialog in the flex-column. ?

**Comment by mayank99** [comment]
In #1795, we have removed `overflow: hidden` (fixing #1551) and the inline `transform` (fixing this issue). It's now released in 2.12.21 and 3.3.1

**Comment by Juliakas** [comment]
> @Juliakas You should probably set a fixed height on your table so that it doesn't grow when data is fetched. Generally it's good to minimize content shift.
> 
> The intended centering is supposed to be not in the middle of the screen but slightly above it, which becomes complicated with flex. We are looking into it though.

Generally yes, we should be using fixed height tables, there are some rare cases for us where jumping UI is unavoidable.

And new version solves both of our issues, we still have to make some styling changes to fully adopt it, but thanks for fixing this :)

**Comment by ajmiam** [comment]
Thank you!  2.12.21 fixed the resizing problem for me.
