### ISSUE TITLE
Badge remove transform text uppercase automatically. 

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI#180]
https://github.com/iTwin/iTwinUI/blob/c68f2508dbaf301255542ae19bbae2f73d824eec/src/badge/badge.scss#L13

Text should not have a force uppercase transformation. Should be decide within the code, not by the CSS.

**Comment by mayank99** [comment]
You can override it on your side, so I don't see the problem.

**Comment by veekeys** [comment]
This is our standard, which is applied:
![image](https://user-images.githubusercontent.com/81580355/125035941-1746ca00-e09b-11eb-9fb2-3d9307a11906.png)

Badges are meant to have uppercased text, so we expect users to use it that way. We do not plan to change that. If you have some specific use case, there is a high chance you should not use badges there... but in case you still need it, you can override it easily as Mayank suggested by adding your class or just overriding style.
Let us know if it is not possible or not working.
I am closing this issue for now.

**Comment by maxime4000** [comment]
I talk with @FlyersPh9 and the standard will be change in 2 weeks and then he will submit a PR changing this.
