### ISSUE TITLE
Scrollbar regression on Chrome and Edge

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1814]
The styling added to scrollbars seems to have reverted with newer versions of Chrome and Edge.

https://itwin.github.io/iTwinUI/react/?story=table--basic

**Chrome**
![image](https://github.com/iTwin/iTwinUI/assets/15036346/ab3484d7-0753-4673-ae17-74efcd24ff8f)

**Edge**
![image](https://github.com/iTwin/iTwinUI/assets/15036346/e0ba8203-b3d4-475c-a9f4-aea0e9d58730)

**Firefox**
![image](https://github.com/iTwin/iTwinUI/assets/15036346/d0bc1a36-1916-47d3-b84a-94bda3d66aba)

Disabling the `scrollbar-color` and `scrollbar-width` added by iTwin fixes the issue.

**Comment by HaveSpacesuit** [comment]
Looks like this is a [known regression in Chrome 121](https://syntackle.com/blog/changes-to-scrollbar-styling-in-chrome-121/). (Or maybe not a regression, but a change which causes us problems.)

**Comment by mayank99** [comment]
Not a regression, this is just how scrollbars will look from Chrome 121 onwards.

**Comment by mayank99** [comment]
Actually there is one part we should address: the table header should not display the track buttons, because there will never be a scrollbar there.
![image](https://github.com/iTwin/iTwinUI/assets/9084735/a4ab28e6-aede-43a1-88d3-c0378423e36e)

**Comment by mayank99** [comment]
@HaveSpacesuit I cannot reproduce this issue on Windows. Where/how are you seeing scrollbar tracks in the table header? It looks fine for me:

![image](https://github.com/iTwin/iTwinUI/assets/9084735/648d2cc6-4d38-410d-abb1-20def66a529c)![image](https://github.com/iTwin/iTwinUI/assets/9084735/ba5d8207-7ca3-4b00-bfc1-2695f80d8527)

**Comment by mayank99** [comment]
Now fixed in [3.3.4](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.3.4) 🎉 Thanks for reporting this.


| Before | After |
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/8ad3c538-4a13-49f2-9886-aeefe7f24d20) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/ad454fb4-9267-4ca5-bfd3-4eccfc6a6f7c) |

**Comment by HaveSpacesuit** [comment]
Can we put a fix on v2 as well?

**Comment by mayank99** [comment]
Backported to 2.12.22 👍
