### ISSUE TITLE
SearchBox has double outline when using iTwinUI v2 inside v3

### ISSUE THREAD

**Issue by saskliutas** [iTwin/iTwinUI#1849]
### Describe the bug (current behavior)

SearchBox component from iTwinUI v2 has double outline when used inside iTwinUI v3 app.

![image](https://github.com/iTwin/iTwinUI/assets/24278440/831be2b1-1270-4d3b-970c-85ea44d30fa2)

### Expected Behavior

There should not be inner outline around `input` element.

### Link to minimal repro

https://stackblitz.com/edit/vitejs-vite-kdcj3z?file=src%2FApp.tsx&terminal=dev

### Steps To Reproduce

1. Open sandbox
1. Focus SearchBox

**Comment by mayank99** [comment]
🚀 Fixed in [2.12.23](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.23). Thanks for reporting this.
