### ISSUE TITLE
Add a possibility to remove "All Files" filter from FileUploadCardInput component

### ISSUE THREAD

**Issue by AAugustBentley** [iTwin/iTwinUI#1883]
### Feature

FileUploadCardInput component opens file explorer where users can choose what files they want to select. We can pass accepted file types that are added to filters but can not remove the `All Files` filter selection.
![image](https://github.com/iTwin/iTwinUI/assets/129863171/4a71daa3-d4c2-4ea0-97a8-584723ab4af1)

One possibility would be to use a [File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API) where it is possible to pass an option `excludeAcceptAllOption: true` to exclude all files filter.

### Examples

`<FileUploadCard.Input accept=".xml" excludeAcceptAllOption={true} onChange={() => {}} />`

**Comment by mayank99** [comment]
`excludeAcceptAllOption` only exists in the [`showOpenFilePicker` method](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker), which is an experimental technology and not available across all browsers. Until that is available across all browsers, there is nothing we can do.

Even if there was a way to stop it from appearing, it's not sufficient from a security perspective. Your application should have additional validation logic (both frontend and backend) that displays an error when the wrong file type is uploaded.
