### ISSUE TITLE
Table initial state not setting column order properly.

### ISSUE THREAD

**Issue by lima300** [iTwin/iTwinUI#1899]
### Describe the bug (current behavior)

When setting up the columnOrder prop in table's initial state it's being ignored, and table is rendering columns in the order of the columns array.

### Expected Behavior

Table render columns in the order provided to initial state.

### Link to minimal repro

https://stackblitz.com/edit/github-y5zcvc?file=src%2FDraggableColumns.tsx

### Anything else?

```"@itwin/itwinui-react": "2.12.24"```

**Comment by mayank99** [comment]
Codesandbox link is 404. Could you check and fix the link? You can always fork our [Stackblitz template](https://stackblitz.com/github/iTwin/iTwinUI/tree/main/minimal-sandbox?file=src/App.tsx) too.

**Comment by lima300** [comment]
> Codesandbox link is 404. Could you check and fix the link? You can always fork our [Stackblitz template](https://stackblitz.com/github/iTwin/iTwinUI/tree/main/minimal-sandbox?file=src/App.tsx) too.

Updated

**Comment by rohan-kadkol** [comment]
The issue might be coming from here:

https://github.com/iTwin/iTwinUI/blob/4bd531d5a115f49dd34ce843822db6a371a61714/packages/itwinui-react/src/core/Table/Table.tsx#L716-L724

Because commenting this out fixes the issue. But more investigation might be needed.

**Comment by mayank99** [comment]
This now fixed in [2.12.25](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.25) 🎉
