### ISSUE TITLE
Modal: Title should overflow or wrap

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1904]
### Describe the bug (current behavior)

A modal with a long title gets cut off.

![image](https://github.com/iTwin/iTwinUI/assets/15036346/48d93dc4-c170-45e9-a2e6-2bfb8402db09)

### Expected Behavior

I would expect the title to wrap or be truncated with ellipses by default. The `.iui3-dialog-title` class is set up with `text-overflow: ellipsis`, but as it is using `display: flex`, the ellipses do not work as expected.

(Changing display to `"block"`)
![image](https://github.com/iTwin/iTwinUI/assets/15036346/23167198-6052-4f74-9c3e-685e262dfb02)

### Link to minimal repro

https://stackblitz.com/edit/github-x64mhk

### Steps To Reproduce

* Create a dialog with a long title
* If needed, add a "max-width" class to the dialog to limit the amount the title is allowed to expand

### Anything else?

Using @itwin/itwinui-react 3.5.0

**Comment by mayank99** [comment]
Fixed in [3.6.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.6.0), thanks for reporting 🤘
