### ISSUE TITLE
Allow overriding Slider styles

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#191]
iTwin.js team needs the ability to use an SVG either for the slider thumb or inside of the slider thumb.  Screenshot of one of the reasons for it below:
![Screen Shot 2021-07-15 at 10 53 47 AM](https://user-images.githubusercontent.com/849817/125809229-e9c3f43c-0a32-423e-a51e-440aa9ffe7ec.png)

**Comment by mayank99** [comment]
> the ability to use an SVG either for the slider thumb or **_inside of the slider thumb_**

This is already possible. But I think we need to reduce specificity of `iui-slider-thumb` styles (from 0-2-0 to 0-1-0) to allow easy overrides.

![image](https://user-images.githubusercontent.com/9084735/125855695-0088ef89-e08b-4031-8c9d-bc9782abc1a1.png)

**Comment by mayank99** [comment]
Fixed in 0.24.2
