### ISSUE TITLE
Popover `shift+tab` focus issue

### ISSUE THREAD

**Issue by GerardasB** [iTwin/iTwinUI#1922]
### Describe the bug (current behavior)

`Shift + Tab` is not handling focus correctly when inside a visible popover. Focus is moved to the last focusable item before the popover.
This is not consistent with `Esc` or `Tab` behavior both of which move the focus back to the target element of the popover.

### Expected Behavior

In the attached example `Shift + Tab` should probably move the focus back to the target element.

### Link to minimal repro

https://stackblitz.com/edit/github-wpzlue?file=src%2FApp.tsx

### Steps To Reproduce

1. Open the attached repro
2. Click on button `2`
3. Press `Shift + Tab`
4. Observe that the focus is moved to the button `4`

**Comment by mayank99** [comment]
This one is interesting. I think that Popover should also close when you <kbd>shift</kbd>+<kbd>tab</kbd>? Currently it closes when you <kbd>tab</kbd> out of it or click outside of it.

**Comment by GerardasB** [comment]
> This one is interesting. I think that Popover should also close when you shift+tab? Currently it closes when you tab out of it or click outside of it.

Yes, I think it makes sense. Unless we want to match the behavior w/ `DropdownMenu`. I.e. `Tab` moves to next sibling, `Shift + Tab` moves focus to previous sibling, `Esc` moves focus to target.

**Comment by mayank99** [comment]
This will be fixed in [3.10.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.10.0), via #2009
