### ISSUE TITLE
`ButtonGroup` overflow logic is running w/o `overflowButton` prop

### ISSUE THREAD

**Issue by GerardasB** [iTwin/iTwinUI#1923]
### Describe the bug (current behavior)

`ButtonGroup` will re-render multiple times based on visible nodes returned by the `useOverflow` even when `overflowButton` prop is not provided. This complicates a use-case where a custom overflow logic is needed.

### Expected Behavior

`ButtonGroup` should always render provided children as is when `overflowButton` is not specified.

### Link to minimal repro

https://stackblitz.com/edit/github-fywssb?file=src%2FApp.tsx

### Steps To Reproduce

1. Open console of the repro
2. Click `Calculate overflow` (simulates conditional rendering of overflow button)
3. Observe that the overflow button is toggled correctly (render is fine)
4. Observe the console - when the overflow button is rendered it logs HTMLCollection w/ 2 elements.

### Anything else?

Final render is fine due to later re-renders.

**Comment by Ben-Pusey-Bentley** [comment]
Thanks for submitting this issue. I can confirm that I am able to reproduce it using the steps that you have provided. I would like to add that the elements in the HTMLCollection are the 1 and 2 buttons, and the 3 button is missing, along with the overflow button. @mayank99 Do you know of a way that we could avoid this re-render?

**Comment by mayank99** [comment]
This is strange. I actually noticed that all elements are correctly present in the `HTMLCollection`, even though the `length` is incorrect.

![](https://github.com/iTwin/iTwinUI/assets/9084735/73924d46-f6e1-47b2-9089-4dc648cd96e9)

**Comment by mayank99** [comment]
Fixed in [3.7.2](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.7.2)

**Comment by HaveSpacesuit** [comment]
@Ben-Pusey-Bentley Do you know if this would fix #1118?

**Comment by Ben-Pusey-Bentley** [comment]
> @Ben-Pusey-Bentley Do you know if this would fix #1118?

Did some testing with the linked stackblitz, and this change does not seem to have fixed that issue.

**Comment by mayank99** [comment]
#1118 is technically unrelated, and can be worked around by not using `overflowButton`. But it does present an interesting question: why is `overflowButton` so difficult to use in practice? Maybe we need to rethink how we've implemented [`useOverflow`](https://github.com/iTwin/iTwinUI/blob/main/packages/itwinui-react/src/core/utils/hooks/useOverflow.tsx).
