### ISSUE TITLE
Disabled `MenuItem` should not display `subMenuItems`?

### ISSUE THREAD

**Issue by GerardasB** [iTwin/iTwinUI#1925]
### Describe the bug (current behavior)

Currently a `disabled` menu item will show it's `subMenuItems`. Does it make sense to change this behavior?
I.e. a disabled `MenuItem` will not call it's `onClick` handler.

### Expected Behavior

A disabled menu item should not show `subMenuItems` when hovered.

### Link to minimal repro

https://stackblitz.com/edit/github-cpdu8r?file=src%2FApp.tsx

### Steps To Reproduce

- Click `Menu`
- Hover `Item 1_2` (note: this item is disabled)
- Observe that the submenu is opened.

### Anything else?

This can be handled conditionally at the consumer level, i.e.:
`<MenuItem disabled={disabled} subMenuItems={disabled ? undefined : subMenuItems} />`

**Comment by mayank99** [comment]
I think it kinda makes sense. Click and hover/focus are different actions. Disabled only disables clicks by default.

If we ever support #879, I think disabling `subMenuItems` makes sense.

Since this issue has a pretty simple workaround, I will close this issue.

**Comment by mayank99** [comment]
This is fixed / made consistent in [3.10.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.10.0) 🚀
