### ISSUE TITLE
`IconButton` label is displayed after button is clicked

### ISSUE THREAD

**Issue by GerardasB** [iTwin/iTwinUI#1931]
### Describe the bug (current behavior)

Clicking an `IconButton` and moving the cursor away keeps the button label visible.

### Expected Behavior

Button label should not be visible (unless button is explicitly focused).

### Link to minimal repro

https://itwin.github.io/iTwinUI/react/?story=iconbutton--add

### Steps To Reproduce

1. Click on `+` button
2. Move cursor away
3. Observe that the label stays open

### Anything else?

Label is hidden again after entering/leaving button with a cursor.

**Comment by Ben-Pusey-Bentley** [comment]
Thanks for submitting this issue. I can reproduce this issue with both the `IconButton` and other components that use tooltips, like `SideNavigation`. As a result, I am certain that this issue stems from a problem with the `Tooltip` component. I will raise this issue with the rest of the team.

**Comment by rohan-kadkol** [comment]
@GerardasB Fixed in [v3.7.4](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.7.4) 🚀
