### ISSUE TITLE
Table, when enabling/disabling columns, view scrolls down to table

### ISSUE THREAD

**Issue by Woyken** [iTwin/iTwinUI#1945]
### Describe the bug (current behavior)

Resize some column
![image](https://github.com/iTwin/iTwinUI/assets/13166802/79495b96-198d-4684-8ee6-18ee9c5baed5)
Disable or enable some column
![image](https://github.com/iTwin/iTwinUI/assets/13166802/1c3755e5-bbe2-4381-9a52-691f1805e5f7)
View scrolls down to table
![image](https://github.com/iTwin/iTwinUI/assets/13166802/f1c8194d-91ea-4a7d-943b-4fe3ba31350f)

### Expected Behavior

After enabling/disabling column, view should not scroll down
![image](https://github.com/iTwin/iTwinUI/assets/13166802/f1d835a8-0174-4d14-88b0-0112222110a8)

### Link to minimal repro

https://stackblitz.com/edit/github-dhyxgj

### Steps To Reproduce

1. Add Content above <Table/>, <Table isResizable enableColumnReordering/> with rows until page scrolls
2. Resize column
3. Disable column
4. Page scrolls down

**Comment by mayank99** [comment]
Is this fix also needed in v2?

**Comment by Woyken** [comment]
All good, for our product, we only need it in v3

**Comment by rohan-kadkol** [comment]
Released in [v3.7.3](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.7.3) 🚀
