### ISSUE TITLE
Table crashed

### ISSUE THREAD

**Issue by 1122334rr** [iTwin/iTwinUI#1951]
### Describe the bug (current behavior)

when I update @itwin/itwinui-react (1.42.0--->2.12.22), my table component crashed when reload. 
![屏幕截图 2024-03-26 145849](https://github.com/iTwin/iTwinUI/assets/52186100/ce2c212c-50ab-42de-bc53-a290d20c83b6)

**Comment by mayank99** [comment]
It's impossible for us to help you with just a screenshot of the error. Can you provide more details?

My only guess is that your Table columns contain loose JSX nodes, in which case you can try to use a function instead.

```diff
- Header: <MyComponent />
+ Header: () => <MyComponent />
```
