### ISSUE TITLE
Draggable `Dialog` does not automatically resize well

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1961]
### Describe the bug (current behavior)

Using a dialog with `isDraggable`, an input element with a validation error causes a scrollbar to appear. Non-draggable dialogs resize to accommodate the status message, but a draggable dialog does not adjust its vertical height.

![Draggable dialog height](https://github.com/iTwin/iTwinUI/assets/15036346/47c0aa56-b7a9-4aef-9881-a13e3d7999de)

### Expected Behavior

Would be nice to have draggable dialogs adjust their height when their contents change, same as other dialogs.

### Link to minimal repro

https://stackblitz.com/edit/github-xnmtqx?file=src%2FApp.tsx

### Steps To Reproduce

* Create a dialog with `isDraggable`
* Add an input with a validation message
* Invalidate the input to get the message to appear

### Anything else?

Using 3.5.0

**Comment by mayank99** [comment]
It looks like we measure the initial size of the dialog and duplicate it into inline `style`s.
- We should not set the inline `style` until the user attempts to resize the dialog.
- For non-resizable draggable dialogs, we should not set width/height in the inline `style` at all. Only positioning/`transform` is necessary.

**Comment by mayank99** [comment]
fixed in [3.9.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.9.0) 🚀
