### ISSUE TITLE
`Table` layout regression in 3.6

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1965]
### Describe the bug (current behavior)

Table cells which composed multiple elements would align horizontally prior to iTwinUI-React 3.6. After updating to 3.6 or 3.7, they are now aligning vertically.

**3.5 table**
https://stackblitz.com/edit/github-qken3j-ykcnfs?file=src%2FmyTable.tsx
![image](https://github.com/iTwin/iTwinUI/assets/15036346/653fe0f6-4bd2-4f64-9eef-8e3d39ad00bc)

**3.7 table**
https://stackblitz.com/edit/github-qken3j?file=src%2FmyTable.tsx
![image](https://github.com/iTwin/iTwinUI/assets/15036346/aaf8d823-3840-443f-83dd-f2c3115b9c2f)

### Expected Behavior

The layout should remain the same as 3.5 and before, with a horizontal alignment.

### Link to minimal repro

https://stackblitz.com/edit/github-qken3j?file=src%2FmyTable.tsx

### Steps To Reproduce

* Use itwinui-react 3.5
* Create a table with a Cell formatter which returns several components
* Notice the components are aligned horizontally
* Update to 3.6 or 3.6
* Notice the components are now aligned vertically

**Comment by mayank99** [comment]
We'll fix the regression, but you should be using `cellRenderer`+`DefaultCell` for this use case. https://stackblitz.com/edit/github-qken3j-ehgxs1?file=src%2FmyTable.tsx%3AL15

**Comment by mayank99** [comment]
This is fixed in [3.8.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.8.0) 🥳
