### ISSUE TITLE
Add year selection option to DateRangeFilter and DatePickerInput

### ISSUE THREAD

**Issue by wilmaier** [iTwin/iTwinUI#1984]
### Feature

The DateRangeFilter and DatePickerInput components do not provide the showYearSelection prop to enable for the DatePicker.  Could this prop get added to DateRangeFilterOptions, DateRangeFilterProps and DatePickerInputProps?  Or maybe just hard-coded to true on DatePicker if it seems like everyone would need that?

**Comment by mayank99** [comment]
We'll support this in `DateRangeFilter` 👍 

It's also worth noting that `DatePickerInput` is an implementation detail of `DateRangeFilter`, and you shouldn't need to know which props it has or even that it exists at all.

**Comment by mayank99** [comment]
This is now available in [3.9.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.9.0) 🚀

```js
tableFilters.DateRangeFilter({ showYearSelection: true })
```
