### ISSUE TITLE
<Tooltip> Performance problems in <Table>

### ISSUE THREAD

**Issue by Woyken** [iTwin/iTwinUI#2002]
### Describe the bug (current behavior)

Using \<Tooltip\> components in \<Table\> is causing MAJOR performance problems.
Scrolling becomes jumpy, laggy.
Mostly visible in Chromium browsers. Firefox works a bit better (not perfect)

There are cases where we want to add a Tooltip on icon in table cell

### Expected Behavior

\<Tooltip\> Should not impact scrolling performance

### Link to minimal repro

https://stackblitz.com/edit/github-1zi5p3?file=src%2FApp.tsx

### Steps To Reproduce

1. Create table with 100 rows. Render rows with \<Tooltip\>
2. Try scrolling the table

### Anything else?

Using version: `@itwin/itwinui-react`: `3*`
![scrolling broken](https://github.com/iTwin/iTwinUI/assets/13166802/47edc841-86c9-4822-86a9-803bb310c426)

**Comment by Woyken** [comment]
Tested on Mac, looks like it handles scroll better, elements disappear for a while.
On windows Chrome scrolling is terrible

**Comment by mayank99** [comment]
Fixed in [3.9.1](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.9.1) 🚀
