### ISSUE TITLE
Table filter alignment issue for popup window on 3.x

### ISSUE THREAD

**Issue by sandiphudekar** [iTwin/iTwinUI#2006]
### Describe the bug (current behavior)

We are experiencing problems with filter alignment when upgrading from 2.x to 3.x in a popup window that has a table component.

![image](https://github.com/iTwin/iTwinUI/assets/39688507/2355394d-8802-4e80-bd40-02f28a15a4ef)

### Expected Behavior

Popover to table filter should be align 

### Link to minimal repro

https://codesandbox.io/p/sandbox/popout-window-table-5gw8sc?file=%2Fsrc%2FApp.tsx

**Comment by mayank99** [comment]
@sandiphudekar This is fixed in [3.10.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.10.0) 🚀

You also don't need to pass `portalContainer` anymore. This code will work correctly:

```jsx
{popoutDocumentBody &&
  ReactDOM.createPortal(
    <ThemeProvider>
      <Table
        columns={columns}
        data={data}
        emptyTableContent={"No Data"}
      />
    </ThemeProvider>,
    popoutDocumentBody
  )
}
```
