### ISSUE TITLE
Empty table state's elements are not centered

### ISSUE THREAD

**Issue by JeaNugroho** [iTwin/iTwinUI#2037]
### Describe the bug (current behavior)

When a table is empty, the greyed-out elements (describing the empty table state) are not centered horizontally. This bug is seen clearer if the table's width is smaller

### Expected Behavior

When a table is empty, the greyed-out elements (describing the empty table state) should be centered horizontally

### Link to minimal repro

https://stackblitz.com/edit/github-girbn1-d2ghuj

### Steps To Reproduce

1. Simply open the code sandbox link provided, and it should display the empty table state to the right of the red box.
2. If the greyed-out elements appear to be centered, try to play with the sandbox's browser pane to minimize the table, that way the greyed-out elements could appear less centered.

![Screenshot (10)](https://github.com/iTwin/iTwinUI/assets/35510082/3ecef5b4-561a-4d47-a920-724df7cd55d8)

**Comment by mayank99** [comment]
This has been fixed in [3.11.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.11.0), thanks for reporting this! @JeaNugroho
