### ISSUE TITLE
Inline `LabeledInput` has an unnecessary row gap

### ISSUE THREAD

**Issue by ignas-k** [iTwin/iTwinUI#2051]
### Describe the bug (current behavior)

`LabeledInput` and `LabeledSelect` with `displayStyle="inline"` have a row gap at the bottom (visible when inspecting in [docs](https://itwinui.bentley.com/docs/input#inline)). I suppose it is there because of a message that can be displayed below the input but the gap is also there when there is no message. This makes the input off-center.

### Expected Behavior

Inline `LabeledInput` and `LabeledSelect` should not have a row gap at the bottom if there is no message. It should be just like non-inline `LabeledInput` and `LabeledSelect` which do not have a gap at the bottom when message does not exist.

**Comment by mayank99** [comment]
This has been fixed in [3.11.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.11.0)
