### ISSUE TITLE
Tree: onKeyDown callback not working

### ISSUE THREAD

**Issue by jasdom** [iTwin/iTwinUI#2109]
### Describe the bug (current behavior)

The `TreeNode` component now allows passing additional `nodeProps`, however, the `onNodeDown` callback does not seem to be invoked when focusing on a node and then pressing a key. The issue seems to occur because the `nodeProps` are passed to the inner node element, but the outer element is focused when navigating using a keyboard.

Providing a `tabindex` through `nodeProps` and focusing on the inner element using the tab key fixes the issue but does not work with key navigation.

### Expected Behavior

`onKeyDown` is called when a node is focused and a key is pressed.

### Link to minimal repro

https://stackblitz.com/edit/github-wwhdww?file=src%2FApp.tsx

### Steps To Reproduce

1. Open a console window.
2. Click on the first node in the first tree and use the arrow up or down keys to focus on a node.
3. Notice that clicking the node calls the `onClick` callback (logs "Clicked" in console) but pressing a keyboard key does not do anything.
4. When a node is focused in the second tree and tab is pressed to focus on the inner element, pressing a keyboard key invokes the `onKeyDown` callback (logs "Key pressed")

**Comment by mayank99** [comment]
Hey @jasdom, thanks for the issue. The `nodeProps` prop is a little confusing, but is working correctly. The actual problem is that `TreeNode` doesn't allow passing a `onKeyDown` prop directly. We can fix this.

Just out of curiosity, what is your use-case for wanting to pass `onKeyDown`?

**Comment by jasdom** [comment]
> Hey @jasdom, thanks for the issue. The `nodeProps` prop is a little confusing, but it's working correctly. It's only meant for applying props to the inner node, not the outer one.
> 
> The actual problem is that `TreeNode` doesn't allow passing a `onKeyDown` prop directly. We can fix this!
> 
> Just out of curiosity, what is your use-case for wanting to pass `onKeyDown`?

I had previously asked regarding selection mode support: https://github.com/iTwin/iTwinUI/discussions/2027. Since this is a critical feature for us, we decided to use our own implementation for the time being. The `onClick` and `onKeyDown` are used to handle different types of selections when `shift` or `ctrl` keys are pressed.

**Comment by mayank99** [comment]
In the next version (3.12.0; not yet released), we're fixing `TreeNode` so that you can pass `onKeyDown` to it directly.

**Comment by mayank99** [comment]
🚀 [3.12.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin/itwinui-react%403.12.0) is now released with the ability to pass top-level props to `TreeNode`. Pass your `onKeyDown`, `onClick`, etc directly to it. You also don't need to set `tabIndex` anywhere.

```jsx
<TreeNode
  {...props}
  onKeyDown={() => {}}
/>
```
