### ISSUE TITLE
`Dialog` and `Modal` contents have different text styling

### ISSUE THREAD

**Issue by ignas-k** [iTwin/iTwinUI#2110]
### Describe the bug (current behavior)

Seems like `Dialog` and `Modal` contents have different text formatting/styling. In the screenshots I have used both `Modal` and `Dialog` with the same props and with the same text content but the height of the dialogs are different (`Dialog` height is 258px and `Modal` height is 276px). The only difference is spacing between text lines so I guess they have different line-height values.

### **Dialog:**

![image](https://github.com/iTwin/iTwinUI/assets/138560995/a1697fcf-2740-4423-9a1c-b4ce16b2639c)

### **Modal:**

![image](https://github.com/iTwin/iTwinUI/assets/138560995/4ce574ef-2c9b-43f5-a132-d9ea571a0479)

### Expected Behavior

`Modal` and `Dialog` should have the same styling/formatting.

**Comment by mayank99** [comment]
Can you provide your code for reproducing this? When used correctly, they should look identical.

**Comment by ignas-k** [comment]
Apparently this is some issue with css layers because we use iTwinUI v3 and support v2 as well. One component prioritizes layer from v3 and the other prioritizes a layer from v2 (you can see that by searching for `line-height`). Here's a simple [reproduction](https://codesandbox.io/p/sandbox/dialog-modal-fz3gzy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxnjnt6a00063j6kpjxtwiv1%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxnjnt6a00023j6kfog9kizp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxnjnt6a00033j6kiyevog31%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxnjnt6a00053j6k50oooht9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxnjnt6a00023j6kfog9kizp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxnjnt6a00013j6knqpocu5j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clxnjnt6a00023j6kfog9kizp%2522%252C%2522activeTabId%2522%253A%2522clxnjnt6a00013j6knqpocu5j%2522%257D%252C%2522clxnjnt6a00053j6k50oooht9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxnjnt6a00043j6kkimpc3x7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxnjnt6a00053j6k50oooht9%2522%252C%2522activeTabId%2522%253A%2522clxnjnt6a00043j6kkimpc3x7%2522%257D%252C%2522clxnjnt6a00033j6kiyevog31%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxnjnt6a00033j6kiyevog31%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by mayank99** [comment]
This has nothing to do with layers or cascade prioritized. `line-height` is an inherited property, so the closest DOM ancestor that sets `line-height` will be used.

In your case, `<ThemeProviderV2>` is the closest ancestor of `<Dialog>` that sets `line-height`. `<Modal>` is behaving differently because it gets portaled out into `<ThemeProvider>` (v3) by default. You can match this behavior by using `<Dialog portal={true}>`.

**Comment by ignas-k** [comment]
I see, I got it working now, thank you!
