### ISSUE TITLE
Table: poor performance/css issues

### ISSUE THREAD

**Issue by piatrashkakanstantinass** [iTwin/iTwinUI#2114]
### Describe the bug (current behavior)

Check: https://github.com/piatrashkakanstantinass/itwin-table-performance-test ([Live URL](https://piatrashkakanstantinass.github.io/itwin-table-performance-test/))

Hi!

We use Table component in our project and have noticed performance issues when we lazy load the data. I have created a separate project to attempt to reproduce some performance issues that we have.

Issues:

- Items at the end do not show up after page loaded and virtualization is enabled (if you toggle virtualization via button or use a timer with useEffect it works)
- If you disable and reenable virtualization, rows will load, but performance feels slightly sluggish (Chrome).
- When devtools are opened, performance is generally a bit worse
- When react devtool "Highlight updates when components render." is enabled, rows are updated later than expect (virtualization enabled) (I guess that is expected to some degree)
- (Our project only) (When react highlight devtool is enabled, rows flicker)
- Performance devtool suggests that Forced reflow is a possible performance bottleneck

**Comment by piatrashkakanstantinass** [comment]
https://github.com/iTwin/iTwinUI/assets/115642938/f2f8a791-37c0-40aa-b85d-ee9c716541ff

Sample table inside our project

**Comment by piatrashkakanstantinass** [comment]
I am trying to optimize Table performance in our project. We don't use virtualization and the onBottomReached loads only 25 new items, but performance is sluggish. (slowdowns when new items are added, you can see same behavior with demo project that I linked). Scrolling gets stuck.

https://github.com/iTwin/iTwinUI/assets/115642938/451aa6f9-ec5a-4dcc-8b63-3ecad6d2fa5c
https://github.com/iTwin/iTwinUI/assets/115642938/4c5fdbbc-ede2-4c96-a0f2-d71b01fd7f50

**Comment by piatrashkakanstantinass** [comment]
An update: I have tried running demo project without virtualization on another machine (m1 pro macbook, latest chrome) and performance impact is not as bad (even with 6x-20x cpu throttling). Firefox on any machine behaves properly as well. For comparison:
- Firefox performance: 
https://github.com/iTwin/iTwinUI/assets/115642938/43f4662f-8a40-4673-a4b4-3dd3a6447f99
- Chrome performance (Notice substantial slowdown at the end):
https://github.com/iTwin/iTwinUI/assets/115642938/0a537e82-bf81-4223-9576-81095ff1a1e9

**Comment by mayank99** [comment]
I was looking into this issue some more, and found that `content-visibility` doesn't help and React 18 transitions also don't seem to help. Here's the sandbox I was playing with: https://stackblitz.com/edit/github-qeydr6-nhhabw?file=src%2FApp.tsx

**Comment by mayank99** [comment]
Updated repro for 3.13.0 which includes a refactored virtualization implementation: https://stackblitz.com/edit/github-qeydr6-ssdqdr?file=package.json,src%2FApp.tsx

Performance is still sluggish, mainly during the time loading spinner is shown.

**Comment by piatrashkakanstantinass** [comment]
@mayank99 stackblitz table is still sluggish for me

https://github.com/user-attachments/assets/5cd35ca7-8816-493c-a586-2031ec5510b1

**Comment by mayank99** [comment]
Yeah there's still a bit of layout thrashing we still need to fix. Lets track that in #888; you can optionally leave a brief comment there to bump it up.

In this issue, the biggest blocker was that rows were literally not showing up when using lazy-loading and using virtualization. This seems to have been definitely fixed.
