### ISSUE TITLE
Select: Does not work with latest `@floating-ui/react` version

### ISSUE THREAD

**Issue by saskliutas** [iTwin/iTwinUI#2115]
### Describe the bug (current behavior)

`TypeError: Cannot read properties of undefined (reading 'current')` is thrown in `Select` component when `@floating-ui/react@0.26.18` is used. Adding `"@floating-ui/react": "0.26.17"` to package.json resolves this issue.

### Expected Behavior

`Select` component should not throw error.

### Link to minimal repro

https://stackblitz.com/edit/vitejs-vite-ptf6fg?file=src%2FApp.tsx

### Steps To Reproduce

1. Open sandbox.
2. Open dev tools console and observer uncaught error.

**Comment by mayank99** [comment]
Thanks for reporting this; this seems to be caused by our recent `Menu`-related refactors.

**Comment by mayank99** [comment]
🚀 [3.12.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin/itwinui-react%403.12.0) is now available with the fix.
