### ISSUE TITLE
Dialog title overflow will not break without spaces

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#2126]
### Describe the bug (current behavior)

A dialog with a long title (without spaces) will overrun the contents of the title bar

![image](https://github.com/iTwin/iTwinUI/assets/15036346/6f0c5ed8-fb34-44cc-9826-5ad86fc01394)

### Expected Behavior

The dialog title should wrap and stay within the container.

### Link to minimal repro

https://stackblitz.com/edit/github-lpys6q-y6kwbg?file=src%2FApp.tsx

### Steps To Reproduce

Create a dialog with a title that does not have spaces. The wrapping strategy does not take this situation into consideration.

**Comment by mayank99** [comment]
Thanks for reporting this; it should be fixed in [3.12.2](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.12.2) 🚀
