### ISSUE TITLE
Popovers shift elements

### ISSUE THREAD

**Issue by GerardasB** [iTwin/iTwinUI#2155]
### Describe the bug (current behavior)

Nested popovers shift the page or target element. 

![Screenshot 2024-07-23 at 12 56 27](https://github.com/user-attachments/assets/9e2fe9f7-1528-4775-9935-715643907f1c)

### Expected Behavior

Popover components should render near the target and should never shift/reposition other elements.

### Link to minimal repro

https://stackblitz.com/edit/github-xa43bc-jca2d1?file=src%2FApp.tsx

### Steps To Reproduce

- Click "Popover" button
- Click "Option 1" multiple times to open/close/open the select menu
- Observe that the application is shifted (scrollbar appears)

Variant where a target (button) is shifted:
- Uncomment CSS in styles.css
- Observe that the "Popover" button is shifted now, instead of the whole page

### Anything else?

`@itwin/itwinui-react`: `^3.0.0`
It looks like this happens in Chrome but not in Firefox.

**Comment by Ben-Pusey-Bentley** [comment]
I was able to test and confirm that this bug happens in Chrome and does not happen in Firefox. I also confirmed that this bug appears in Edge, so this bug may stem from something in Chromium.

**Comment by mayank99** [comment]
There was another user report which I think boils down to the same underlying issue. A `Select` component near the edge of the screen can sometimes cause scrollbars to appear. See [minimal repro](https://stackblitz.com/edit/github-jbl8qz-xepxzg?file=src%2FApp.tsx) (try selecting the last item).

![](https://github.com/user-attachments/assets/d61094c5-4318-44ea-b9b5-4119498472ea)

#2162 might also be related.

(There is no `Popover` in either of the issues I mentioned, so it's possible that these might unrelated.)

**Comment by mayank99** [comment]
This has been fixed in [3.14.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.14.0) 🚀
