### ISSUE TITLE
columnManager tooltip adds vertical and horizontal scroll to the screen

### ISSUE THREAD

**Issue by JonasDov** [iTwin/iTwinUI#2162]
### Describe the bug (current behavior)

When columnManager button is added to itwinui-react table (version 3.13.2) and is hovered on, it shows a tooltip that adds a vertical and horizontal scroll to the layout.

### Expected Behavior

Tooltip should not add vertical and horizontal scroll to the page.

### Link to minimal repro

https://stackblitz.com/edit/github-vqhq4x-cnhv3t?file=src%2FApp.tsx

### Steps To Reproduce

1. Create a table component
2. Add columnManager to the table
3. Hover on the column manager button

**Comment by mayank99** [comment]
Hey, can you double-check your repro? I'm not seeing a scrollbar appear on Chrome/Firefox/Safari.

https://github.com/user-attachments/assets/172f1072-144d-4848-92c3-172752997f79

**Comment by JonasDov** [comment]
It depends on the screen size:

https://github.com/user-attachments/assets/669125f1-da25-44d9-8f73-a74298d7fbd0

**Comment by mayank99** [comment]
I was not able to reproduce this one regardless of (emulated) screen size or zoom level. The tooltip correctly adjusts its position based on the available space.

![](https://github.com/user-attachments/assets/cc7f2d29-2865-4e92-8967-a96b505abf21)


@Ben-Pusey-Bentley Are you able to reproduce this one on Windows?

**Comment by Ben-Pusey-Bentley** [comment]
I am able to reproduce a really bad version of this on Chrome with 150% browser zoom where the scroll bars flicker in and out rapidly. For some reason, the screen recording only shows some of the flicker, but it was much worse for me on my monitor.


https://github.com/user-attachments/assets/5f5eb9ba-5518-4d29-a0c3-0321e1c03285

**Comment by mayank99** [comment]
This has been fixed in [3.14.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.14.0) 🚀
