### ISSUE TITLE
Provide a color-picker control 

### ISSUE THREAD

**Issue by ayarbee** [iTwin/iTwinUI#217]
#### Feature
AWMDS is a map configuration tool that needs to allow users to define map layers. When defining a layer, aspects of the layer presentation are detailed. Those details include setting the colors of items drawn on the map. As a result there is a need for the user to be able to pick colors. Setting color by RGB value is not user friendly, a color picker capability would be very useful.

###### Possible components on github
https://uiwjs.github.io/react-color/
https://casesandberg.github.io/react-color/

###### How a color picker would be used in AWMDS
The user is editing/creating a layer, and whist defining the **Symbology** they click the **Color** control and a suitably styled color picker control appears to allow alteration of the value:

![Color-Picker-Layer-Map-Config](https://user-images.githubusercontent.com/12095069/127649181-bef4f081-5bba-48ab-a007-b1c3a3830a41.png)

**Comment by FlyersPh9** [comment]
We should be able to use the `@mixin iui-dropdown` to apply the correct background and drop shadow styling.

**Comment by saaaaaally** [comment]
@ayarbee We have standards for a basic and advanced color picker, which is what we are thinking of implementing but they are simpler than the screen shot you provided, will these still fulfill your needs? 

**Basic:**
![image](https://user-images.githubusercontent.com/88331924/129764501-af834cfd-e92f-4f28-92ce-210fb66f037d.png)

**Advanced:**
![image](https://user-images.githubusercontent.com/88331924/129764541-1e9e81c5-c99e-4ad6-9cb2-e288ca59c448.png)

**Comment by ayarbee** [comment]
@saaaaaally  I would agree that the advanced version of the color picker as shown would suit our needs. Thanks!
