### ISSUE TITLE
Table: Expandable content does not work when using `enableVirtualization`

### ISSUE THREAD

**Issue by smmr-dn** [iTwin/iTwinUI#2171]
### Describe the bug (current behavior)

The `enableVirtualization` property in `Table` has caused some abnormal behaviors in the output data such as:
- Odd behavior of expandable rows (expandable content overlaps with other rows).
- ~~Data is only shown up to the width of current available viewport.~~
- Data is not shown when scrolling at faster pace.

With `enableVirtualization`
![with_virtualization_enabled](https://github.com/user-attachments/assets/fd9455d9-9062-4ea8-97cd-cb46fa272f56)

Without `enableVirtualization`
![image](https://github.com/user-attachments/assets/15adba96-8137-48a9-851f-d91cb80b1eff)
![image](https://github.com/user-attachments/assets/538ae026-ff08-4b25-8f42-eff8be1c8b54)

### Expected Behavior

Virtualizes large amount of data in table and only shows certain rows in viewport.

### Link to minimal repro

https://stackblitz.com/edit/github-gevv11-u36ywv?file=src%2FApp.tsx,src%2Fmain.tsx

### Anything else?

Package version: @itwin/itwinui-react version ~~3.12.0~~ 3.13.3

**Comment by mayank99** [comment]
Please provide a minimal repro using the latest version (3.13.3). This bug report is not actionable in its current state.

**Comment by mayank99** [comment]
Actually, I'm pretty sure this was fixed in 3.13.3, so I'll close this issue until there is more info.

**Comment by smmr-dn** [comment]
Added the link to an example monorepo as the horizontal scroll was fixed in 3.13.3 but the expandable rows are still broken.

**Comment by mayank99** [comment]
This is fixed and released in [3.15.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.15.0).

@smmr-dn You might want to inform the iModel Console team if this is still relevant for them.
