### ISSUE TITLE
Preview popout reparent: iTwinUI ProgressRadial shows "Loading" text when popped out

### ISSUE THREAD

**Issue by Juliakas** [iTwin/iTwinUI#2230]
### Describe the bug

When `ProgressRadial` is popped out, it's shadow dom loses it's styling and "Loading" text is being displayed even though it was supposed to be hidden:
![image](https://github.com/iTwin/iTwinUI/assets/36437897/8f59dade-82dd-42dc-bbf7-57afa5772f17)

This doesn't happen when component is rendered initially in new window, only when transition from main to new window is happening and widget dom is being moved.

I reproduced everything on appui storybook (on release/4.15.0 tag) by changing widget content to `ProgressRadial` in `ReparentPopoutWidgets.tsx` file.

### To Reproduce

1. Have a widget with `ProgressRadial` spinner.
2. Pop out widget.
3. Notice "Loading" text being shown inside spinner. 

### Expected Behavior

Expected for loading text to remain hidden when transitioning.

### Screenshots

![image](https://github.com/iTwin/iTwinUI/assets/36437897/8f59dade-82dd-42dc-bbf7-57afa5772f17)

### Desktop (please complete the applicable information)

**OS:** Windows 11
**Browser:** Microsoft Edge
**Browser version:** Version 126.0.2592.68 (Official build) (64-bit)
**Appui version:** 4.15.0 (reproduced on source)

### Additional context

Would need this fixed before our Modeler's release, our feature freeze is at beggining of next month. At worst we would need a workaround or to opt out of iTwinUI's accessibility shadow dom usage

**Comment by mayank99** [comment]
Reopening this in iTwinUI since there is some work left to be done. AppUI now exposes a `appui:reparent` DOM event which iTwinUI can listen to and re-add shadow DOM stylesheets.

**Comment by mayank99** [comment]
This been fixed by iTwinUI in [3.15.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.15.0) 🚀
