### ISSUE TITLE
Combobox / Select inside a Popover

### ISSUE THREAD

**Issue by FelixGirard** [iTwin/iTwinUI#2245]
### Describe the bug (current behavior)

Hi! I have a popover for customizable line styles. I want a ComboBox for the selection of the line style (like dashed): 
![image](https://github.com/user-attachments/assets/c141acee-908d-4bc1-8a8a-1d024c04208f)
When I select an option, the popover close.

### Expected Behavior

I would expect the option to be selected but the popover to stay open until I click outside of it.

### Link to minimal repro

https://stackblitz.com/edit/github-6vfacf?file=src%2FApp.tsx

### Steps To Reproduce

1. Click on the button to open the popover.
2. Select an item
3. Notice you wont have the value selected.

### Package Version

- [X] I'm using the latest version of iTwinUI.

**Comment by mayank99** [comment]
Thanks for reporting this! I think this might be a regression related to recent changes (#2209). We'll take a look and try to find a proper fix.

**Comment by mayank99** [comment]
We're still looking into this. In the meantime, you can work around it in two ways:

1. By adding a `<ThemeProvider>` with [`portalContainer`](https://itwinui.bentley.com/docs/themeprovider#portals) in your `Popover`. See [stackblitz](https://stackblitz.com/edit/github-6vfacf-nks43o?file=src%2FApp.tsx).
2. (Starting with [3.15.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.15.0)) By changing the `portal` prop individually for `Select` or `ComboBox`.

**Comment by FelixGirard** [comment]
I tested and it works with #1 for now, thanks!
