### ISSUE TITLE
Muted Icon Color in SplitButton

### ISSUE THREAD

**Issue by morganadrales** [iTwin/iTwinUI#2254]
### Describe the bug (current behavior)

When using the SplitButton and providing an icon, the icon color is muted making the button look disabled.

### Expected Behavior

Icon color should be the default icon color.

### Link to minimal repro

https://stackblitz.com/edit/github-9fgyga?file=src%2FApp.tsx,package.json,package-lock.json,tsconfig.json

### Steps To Reproduce

1. Click repro link
2. Toggle light mode (if dark mode applied by default)
3. Notice the icon color is muted

### Package Version

- [X] I'm using the latest version of iTwinUI.

**Comment by mayank99** [comment]
Hey, thanks for opening this issue. In short, this is not a bug. The `SplitButton` (and also the base `Button`) wasn't designed to be used without text, so what you're seeing is the default (static) color of the icon. iTwinUI does provide a `IconButton` for cases where it makes sense, but it's not compatible with `SplitButton`.

Can you share more details about your use-case? Is there a reason you're not able to use the regular `SplitButton` with the text "Save"?

**Comment by morganadrales** [comment]
Thanks for the quick reply! I was wondering if perhaps this component wasn't intended to be used with icons since the example doesn't use one.

We're looking at using the `SplitButton` for a "Save/Save As" workflow in our query builder where the default behavior of the button (the left side click) would save the changes to the existing query, and the menu item "Save As" would prompt the user for a new name for the query and save the changes under a new name.

Right now our save button is a high-visibility `IconButton` without a label but we are working on polishing our UI with Dan Abney in which case our new `SplitButton` would look something like this

![image](https://github.com/user-attachments/assets/121a0e65-7de2-49d1-a79c-884ced9e3b79)

If we can just pass the `startIcon` like suggested and get the correct styling and then also provide the label inside the `SplitButton`, that should be enough for our purposes to achieve the result in the mockup.

Thanks again for your replies!
