### ISSUE TITLE
Add InfoPanel

### ISSUE THREAD

**Issue by jawariawaseem1** [iTwin/iTwinUI#226]
#### Feature
Add InfoPanel component that exists in the bwc-react library as we can't find any alternative to it inside the itwinui-react.
**bwc-react/innersource/InfoPanel**

![image](https://user-images.githubusercontent.com/9084735/128352661-abb2bb42-ff57-43da-9674-1288d8d7448e.png)

**Comment by mayank99** [comment]
Hi @jawariawaseem1 👋  Thanks for the feature request. Since this component has a few different moving parts, do you have an initial feature set that's essential to you?

**Comment by jawariawaseem1** [comment]
It should be re-sizable, slides in from the right side and must have a closing button.

**Comment by maxime4000** [comment]
Hi, would be nice if the info panel could be one of the two type : 
1. The info panel is displayed like a floating component. 
2. The info panel is displayed like it was part of the table. (Table get resize when the info panel is displayed)

**Comment by FlyersPh9** [comment]
Hey @maxime4000, I just saw your comment after merging the PR, sorry about that.
1. Can you explain what you mean by "displayed like a floating component"?
2. I made the decision for v1 to only support overlaying the content.  Pushing the content is something we can consider looking into. If you need that, [submit a feature request](https://github.com/iTwin/iTwinUI/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) and we'll investigate.

**Comment by maxime4000** [comment]
- Floating is like this : 
  - ![image](https://user-images.githubusercontent.com/849817/130088000-7f92a733-7a58-435f-b617-8a7a0f28b7ff.gif)
- While being part of the table is like this :
  - ![InfoPanelPushingTable](https://user-images.githubusercontent.com/4070713/133470463-61eac6c1-e18d-4f94-b96a-e8f3108239de.gif)

**Comment by FlyersPh9** [comment]
Ah, ok, I misunderstood your initial comment then.  We have delivered on 1 & will investigate option 2.
