### ISSUE TITLE
Regression with nested popovers

### ISSUE THREAD

**Issue by GerardasB** [iTwin/iTwinUI#2291]
### Describe the bug (current behavior)

Rendering a `DropdownButton` or `LabeledSelect` component inside of `Popover` will auto-close the popover. I have not tested other use cases, i.e. nesting Popover components within other popovers or using any other "expandable" components.

Related issue: https://github.com/iTwin/appui/issues/1052

### Expected Behavior

It should be possible to expand `LabeledSelect` from within a popover.

### Link to minimal repro

https://stackblitz.com/edit/github-jy2mym?file=src%2FApp.tsx

### Steps To Reproduce

Workflow 1:
1. Click `Overflow` button to open the popover
2. Click the select component (with `Select` label)
3. Observe that the popover is closed
4. Expected: the select component should open and display available values

Workflow 2:
1. Click `Overflow` button to open the popover
2. Click the dropdown component (with `Dropdown` label)
3. Nested dropdown popover opens correctly
4. Hover the nested popover
5. Observe that both popovers close
6. Expected: it should be possible to click on a value from the dropdown menu

### Package Version

- [x] I'm using the latest version of iTwinUI.

### Anything else?

This is a regression. The last known version with correct behavior is: `@itwin/itwinui-react: 3.11.2`
To test the correct behavior open the sandbox, lock the version in `package.json`, delete the lock file and reload the page.

**Comment by GerardasB** [comment]
Related/duplicate of #2245

**Comment by mayank99** [comment]
Let's track this together with #2245.

The same [workaround](https://github.com/iTwin/iTwinUI/issues/2245#issuecomment-2371733763) applies here. https://stackblitz.com/edit/github-jy2mym-1utmjx?file=src%2FApp.tsx
