### ISSUE TITLE
svg webcomponents break in many places

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#230]
Because we are targeting first-level svg selectors in many places, we cannot use webcomponents there (webcomponents wrap the svg with a custom element name).

<details>

![image](https://user-images.githubusercontent.com/9084735/128733241-22dcc412-adbb-4150-8838-edaaadec46c3.png)
</details>

### Workaround

In [itwinui-icons-elements@0.1.0-dev.0](https://www.npmjs.com/package/@itwin/itwinui-icons-elements/v/0.1.0-dev.0), I'm doing this:
```js
customElements.define('svg-placeholder', class extends HTMLElement {
  connectedCallback() {
    const innerHtml = '<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m0 0v16h16v-16zm14.85714 1.94286v12.11428l-6.05714-6.05714zm-6.85714 5.25714-6.05714-6.05714h12.11428zm-.8.8-6.05714 6.05714v-12.11428zm.8.8 6.05714 6.05714h-12.11428z"/></svg>';
    this.parentElement.insertAdjacentHTML('beforeend', innerHtml);
    this.getAttributeNames().forEach((attribute) => {
      this.nextElementSibling.setAttribute(attribute, this.getAttribute(attribute));
    });
    this.remove();
  }
});
```

It renders as:
![image](https://user-images.githubusercontent.com/9084735/128782366-940d8322-8044-4e6e-93e9-156e05f29c94.png)

After this is fixed, I can change it back to this:
```js
customElements.define('svg-placeholder', class extends HTMLElement {
  connectedCallback() {
    this.innerHTML = '<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m0 0v16h16v-16zm14.85714 1.94286v12.11428l-6.05714-6.05714zm-6.85714 5.25714-6.05714-6.05714h12.11428zm-.8.8-6.05714 6.05714v-12.11428zm.8.8 6.05714 6.05714h-12.11428z"/></svg>';
  }
});
```

It will render as:
![image](https://user-images.githubusercontent.com/9084735/128782462-60fb428d-5b41-4d07-b0f8-1ee78a48a369.png)

**Comment by veekeys** [comment]
Why removing the element is bad? Did you find it as a bad practice or something?
I know I used it for user-icon and end result is nice, IMO. It even lowers the tree levels by not rendering the root web element.

**Comment by mayank99** [comment]
> Why removing the element is bad? Did you find it as a bad practice or something?

Since the original element is removed, every attribute/event that was applied on it needed to be copied to the child. I copied attributes, but events would not work.

I was looking at many webcomponent libraries and no one does this, so yeah I'd say it's a bad practice 😄

**Comment by mayank99** [comment]
I've found another problem: Because [web components default to `display: inline`](https://developers.google.com/web/fundamentals/web-components/best-practices#set-a-:host-display-style-e.g.-block,-inline-block,-flex-unless-you-prefer-the-default-of-inline.), we cannot set width/height from outside without targeting the svg.

The solution is to use shadow DOM and set `:host { display: inline-block; }` but then we cannot target `svg` from outside (and there is no prefix selector for element tag name).
