### ISSUE TITLE
Version 3.15.0 has broken table with custom expandable content

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#2300]
### Describe the bug (current behavior)

I have spent some time to even be able to reproduce this on isolated environment, but after updating to version 3.15.0 (and above), our Table has broken down.
Mainly we faced 2 issues:
- We got max depth reached error (which we managed to fix by getting rid of `getRowId` prop on Table, but that is a workaround..)
- After first fix, we were seeing expandable content on main rows rather than the main data rows..

In original code, we are using react-query to fetch some data asynchronously, where we do expect table to recalculate some stuff..
For reproduction, I have added just simple state which is updated after some time just to show what is enough to break the UI.

I have seen some changes done on expandable content code, so pretty sure some regressions was delivered there.

### Expected Behavior

Working same as with 3.14.x

### Link to minimal repro

https://stackblitz.com/edit/github-6vfacf-d3rg1m?file=src%2FApp.tsx

### Package Version

- [x] I'm using the latest version of iTwinUI.

**Comment by smmr-dn** [comment]
This now has been fixed in [3.15.5](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.15.5)
