### ISSUE TITLE
Add inline option for Select component

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#231]
Text field, text area, checkbox, radio all support `.iui-inline`.  The select component should also support `.iui-inline`.  This is what it looks like if you try to apply inline to select currently:
![Screen Shot 2021-08-09 at 12 34 01 PM](https://user-images.githubusercontent.com/849817/128741355-14e0f179-25a3-4911-89a6-60127bf729b8.png)

**Comment by veekeys** [comment]
Before doing this, might be useful to check in general our inputs and that possible refactoring to achieve more mixed states. Maybe we would not even go with inline anymore.
