### ISSUE TITLE
Table: `onSelect` value is duplicated when using `subComponent` with 3.15.5

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#2314]
### Describe the bug (current behavior)

Seems latest release has broken down `onSelect` callback as its giving duplicated same value on simple selection.
Here is repro. Check console log giving duplicated value when selecting a row.
![Image](https://github.com/user-attachments/assets/afec8020-3275-418c-a48d-c121f93bd5ac)

### Expected Behavior

`onSelect` giving correct value

### Link to minimal repro

https://stackblitz.com/edit/github-6vfacf-d3rg1m?file=src%2FApp.tsx

### Steps To Reproduce

1. Select a row
2. Check console log for given value

### Package Version

- [x] I'm using the latest version of iTwinUI.

**Comment by smmr-dn** [comment]
This now has been fixed in [3.16.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.16.0)!
