### ISSUE TITLE
Table: Issue in column order in table.

### ISSUE THREAD

**Issue by Charan-ts** [iTwin/iTwinUI#2328]
### Describe the bug (current behavior)

When we use the same table component across multiple tabs, passing different data, including different column orders, the table consistently retains the order from the previous table.

**Video of issue:**
![Image](https://github.com/user-attachments/assets/5fbcceaa-aa1b-490a-b178-0f395848113c)

### Expected Behavior

The table column order should update across all instances in multiple tabs, reflecting the latest data we provide based on any changes in the column order

### Link to minimal repro

https://codesandbox.io/p/sandbox/xf476l

### Steps To Reproduce

1. Create tabs that use the same table component, but with different column order configurations passed to each tab.
2. Reorder the columns in the table within one tab.
3. **Switch to another tab**: You'll notice that the column order in this other tab remains the same as in the first tab, even though different column order configurations are passed to each tab.

### Package Version

- [ ] I'm using the latest version of iTwinUI.

**Comment by mayank99** [comment]
This is not a bug. By default, React uses the position in the component tree to decide whether it's a unique component. You need to pass a `key` when you want to render a new Table. 

The `key` can be the same as the ones used in your tabs.

```jsx
<TableComponent
  key="apple" // or "orange"
  // …
/>
```

**Comment by Charan-ts** [comment]
@mayank99 Thanks, It solved the problem
