### ISSUE TITLE
[DataPicker] Allow for passing undefined `startDate`, `endDate` props when `enableRangeSelect` is set to `true`

### ISSUE THREAD

**Issue by Juliakas** [iTwin/iTwinUI#2333]
### Feature

Allow for passing undefined `startDate`, `endDate` props to DatePicker component when `enableRangeSelect` is set to `true`. This allows for not having any initial date range set.

That being said, if there is no initial range set then it would be nice to force calendar to navigate to somewhere else than "today", `DatePicker` could have `initialFocusedDay` prop or something like that.

### Examples

```tsx

interface DateRange {
  startDate: Date;
  endDate: Date;
}

const MyComponent = ({ limits }: { limits: DateRange }) => {

  const [dateRange, setDateRange] = useState<DateRange>();

  return <DatePicker 
    enableRangeSelect
    startDate={dateRange?.startDate}
    endDate={dateRange?.endDate}
    initialFocusedDay={limits.startDate}
    onChange={(startDate, endDate) => setDateRange({ startDate, endDate })}
    ....
  />
}
```

**Comment by mayank99** [comment]
I think we can support `undefined` in `startDate` and `endDate`, since it almost feels like a bug if `undefined` doesn't work.

However, I just want to note that date range selection is not recommended. For better UX, we instead recommend using two separate date fields for "Start date" and "End date". In the future, the `enableRangeSelect` prop might be deprecated.

**Comment by Juliakas** [comment]
> I think we can support `undefined` in `startDate` and `endDate`, since it almost feels like a bug if `undefined` doesn't work.
> 
> However, I just want to note that date range selection is not recommended. For better UX, we instead recommend using two separate date fields for "Start date" and "End date". In the future, the `enableRangeSelect` prop might be deprecated.

It looked like a good pattern tbh, another example could be how booking.com allows date range selecting which I find convenient and less clicks Also in linked example implementation is a bit more bulky, we have something like this going on right now: ![Image](https://github.com/user-attachments/assets/8a57edfa-5627-4305-a61c-54c352f68621)
