### ISSUE TITLE
`<ExpandableBlock />` component unreported breaking change when migrating from itwinui-v2 to v3

### ISSUE THREAD

**Issue by anmolshres98** [iTwin/iTwinUI#2355]
### Describe the bug (current behavior)

In this PR: https://github.com/iTwin/iTwinUI/pull/1354, the change "Expandable block animation now uses pure css instead of javascript for transitioning." was made. This changes how the content of and expandable block is loaded in but this behavior is not noted in the migration guide.

Because of this change, in v3 the content of expandable block is loaded and inserted in the DOM (even when the block is collapsed/not expanded) and is hidden using css while previously, in v2, the content was being lazy-loaded using js only when the block is expanded. This greatly changes the initial DOM state of an app and what content the DOM has based on which version of itwinui we are using. Check screenshots below from minimal repo while inspecting html elements (while block is not expanded):

on iTwinUi v2:
![Image](https://github.com/user-attachments/assets/8df5fe29-5211-4df6-a55c-44d078de0622)

on iTwinUi v3:
![Image](https://github.com/user-attachments/assets/7f9fc584-b65d-4081-a79e-a8acf6bc6067)

As is seen in the second image, the contents of the block (Permission 0, Permission 1,...) have been inserted but hidden.

This might not affect how the UI itself is shown in the app but does break tests that expect the DOM to be structured in a specific manner. Given this fact, this should be considered a breaking change and should have been reported in the migration guide. Please advise on how apps should deal with this new behavior, specially on tests?

Link to minimal repos:
repo using iTwinUI v2.12.26: https://stackblitz.com/edit/github-6vfacf-3ztsej?file=package.json
repo using iTwinUI v3.16.0: https://stackblitz.com/edit/github-6vfacf-k9weh7?file=package.json

### Link to minimal repro

https://stackblitz.com/edit/github-6vfacf-3ztsej?file=package.json https://stackblitz.com/edit/github-6vfacf-k9weh7?file=package.json

### Package Version

- [x] I'm using the latest version of iTwinUI.

**Comment by anmolshres98** [comment]
This is another instance where a change in v3 was breaking our tests: https://github.com/iTwin/itwinjs-internal/pull/269#discussion_r1855285675

**Comment by anmolshres98** [comment]
Yes, the ask here is documentation

**Comment by mayank99** [comment]
The `ExpandableBlock` change has now been documented in the [migration guide](https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v3-migration-guide#expandableblock). Thanks for reporting this!

The `scrollIntoView`/`scrollTo` calls (mentioned in the [later comment](https://github.com/iTwin/iTwinUI/issues/2355#issuecomment-2495682365)) are not new and do not need to be documented as breaking changes. These are well-supported standard features that we have been using in other components for a long time. While it is unfortunate that JSDOM doesn't provide built-in mocks for these functions, iTwinUI is a component library built for the web platform, not for JSDOM. Standard features like `scrollIntoView` may be added to iTwinUI at any point in any minor or patch release.
