### ISSUE TITLE
`Tree["nodeRenderer"]` has hidden requirement to forward ref to underlying `TreeNode`

### ISSUE THREAD

**Issue by saskliutas** [iTwin/iTwinUI#2357]
### Describe the bug (current behavior)

If `Tree["nodeRenderer"]` renders some component that wraps `TreeNode` there is an error logged in a console: `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()`.

Also in virtualized `small` `Tree` spacing between nodes are off.

There is no mention that component rendered in `Tree["nodeRenderer"]` should `forwardRef` to the wrapped `TreeNode` component.

### Expected Behavior

It should be documented that `ref` will be passed to the component rendered by `Tree["nodeRenderer"]` and if wrapper component is rendered it should forwarf ref to `TreeNode`.

### Link to minimal repro

https://stackblitz.com/edit/github-c2ek3e?file=src%2FApp.tsx

### Steps To Reproduce

1. Open sandbox.
2. Observe error in console
3. Observe too big spaces between tree nodes
4. Replacing `TreeNodeRenderer` with `FixedTreeNodeRenderer` on line 114 resolves these issues

### Package Version

- [x] I'm using the latest version of iTwinUI.

**Comment by smmr-dn** [comment]
This has been documented in the `Tree` JSDoc and documentation which is soon to be published 😄
