### ISSUE TITLE
Svg web component not visible in table header for blazor component

### ISSUE THREAD

**Issue by anandgaikwad** [iTwin/iTwinUI#274]
![image](https://user-images.githubusercontent.com/36064808/131104814-6133cc01-bc78-4e98-8ab1-00327a3580ec.png)

used as fowllowing:

![image](https://user-images.githubusercontent.com/36064808/131105209-04c92d74-e7bc-4cb6-aa75-3d09b400f0da.png)

**Comment by mayank99** [comment]
Update: When I said "we are working on a fix", I meant the alignment. We could not actually reproduce the "not visible" part. Can you verify that the icon shows up on hovering the cell?

And for "sorted columns", you actually need to apply the `iui-sorted` class in your cell.
![image](https://user-images.githubusercontent.com/9084735/131372712-744a1713-f34f-4bbf-8d69-d0f8d4a28afc.png)

That class adds this visibility rule:
![image](https://user-images.githubusercontent.com/9084735/131372545-242486f6-143b-4dc4-8a10-468b593b9532.png)
