### ISSUE TITLE
Spacing in small/large inputs between buttons are not correct

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#298]
Check up the sizes and spacing for small/large input of button

This is our input with `iui-small` and button with `iui-small`.
![image](https://user-images.githubusercontent.com/81580355/150818079-059eefb1-f331-4a68-833e-f50e3f0a6df1.png)

Notice the padding.
Need to review all sizes and check those details

**Comment by mayank99** [comment]
Looks like this is fixed in v1.

![](https://user-images.githubusercontent.com/9084735/201981482-b0879899-89fc-4421-af10-9e8112c2c920.png)
