### ISSUE TITLE
TimePicker: Allow overriding styles

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI#306]
#### Actual behavior
So I've been using the time picker from chrome a while now and it just feel more right than the one in iTwin. My complain is about everythings is too huge ! The scroll bar is taking place where you already know you can scroll there because you don't see all the hours/minutes/seconds. Each number is taking a huge space which result in less number shown.

#### Expected behavior
Not taking every style I edit in this gif as what it should be, but something close to that would be nice. 
![TimePickerSmaller](https://user-images.githubusercontent.com/4070713/134563130-2dae46a0-9f32-4f65-8c8f-becd7ba8d73a.gif)

**Comment by mayank99** [comment]
This is not really a "bug". The visuals are UX-approved.

At the same time, I believe you should be allowed some control over the look, but I think the high specificity of this component would make it hard to override the padding/margin/scrollbar values. So the real task here is to reduce the specificity. I'm converting this to a feature request.

**Comment by maxime4000** [comment]
IMO, iTwinUI's TimePicker is useful because Firefox does not have a TimePicker component. If chrome's TimePicker would work on every browser, this timepicker would not be that useful. Same for DatePicker with time. Again, this Date/TimePicker work without a input field, so it does not replace chrome's one, but I'm pretty sure 99% of the time, you need a input field anyway.

Just to said, I wish iTwinUI's TimePicker would lower its padding, remove the scrollbar which is already obvious it's a scrolling list and maybe remove the separators between hours/minutes/seconds. Maybe I'm just asking: Make it look like chrome's TimePicker with iTwinUI's color/theme and it would be perfect!

## Chrome vs iTwinUI
![image](https://user-images.githubusercontent.com/4070713/134568966-2d9491aa-a3cf-4eb1-927b-41de515c0222.png)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by maxime4000** [comment]
Just to report the firefox look which is broken :
![image](https://user-images.githubusercontent.com/4070713/134730616-a5ee4f84-37d4-4107-876f-7c690026ac98.png)

**Comment by mayank99** [comment]
In #309, we've changed the scrollbar to be overlay on Chrome and hidden on Firefox, and made the sizes consistent for dates vs times. Also reduced nesting a little to make it easier to override styles if you so desire.

This will be released in v0.33.0 soon.
