### ISSUE TITLE
Side navigation

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#31]
#### Feature
A side navigation component provided by iTwinUI (and iTwinUI-react) would be really useful given the number of interactions and animation such a component potentially have.

* Menu state: Colapsed (with tooltip), Expanded right, Expanded below. (Last one is used when intended for mobile)
* Menu opening behavior: Push content, Overlay.
* Menu Item distribution: Allow top and bottom items.
* Menu Item states: Normal, Active, Hover, Disabled.
* Menu Item behaviors: Link, Sub-Menu, Content panel.

#### Examples
https://itwin.bentley.com
https://construction.bentley.com
https://plantsight.bentley.com
https://projectwise365.bentley.com

**Comment by veekeys** [comment]
@raplemie, thank you for using iTwinUI! We will start working on this one probably next week.
@FlyersPh9
