### ISSUE TITLE
RadioTiles: review responsive design, border issues and group selector

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#322]
#321 mentions:

> We have bug now because of our borders (see picture below), so will create new item to change borders approach (outline or need to figure out something else...).
Also, border radius now looks weird...
> ![](https://user-images.githubusercontent.com/81580355/136207963-05b599e3-aa6d-4a5f-a1bc-b35f0a9198c3.png)

Also, if want to add tooltip, need to wrap in a div every RadioTile. Doing this, brakes selector of group. Need to update those.

**Comment by elephantcatdog** [comment]
![image](https://user-images.githubusercontent.com/37936169/174672379-f88393c0-3585-47a2-bb1a-8356e3df2ed5.png)
