### ISSUE TITLE
iui-text-block has no predefined color

### ISSUE THREAD

**Issue by irenajur** [iTwin/iTwinUI#368]
#### Describe the bug (actual behavior)

`<Text>Lorem Ipsum</Text>` has no predefined text color it uses inherited one. 

Output:
`<div class="iui-text-block">Lorem Ipsum</div>`

Computed color:
![image](https://user-images.githubusercontent.com/83585850/140548597-b69ef2b9-b170-40a4-b428-c5736f733a7c.png)

Result:
![image](https://user-images.githubusercontent.com/83585850/140548962-39175e13-b7b0-4ef2-9c55-dbe53ef6b7b2.png)

@veekeys might add additional info if needed.

**Comment by mayank99** [comment]
I would expect that the inherited color is correct in most cases. If we were to set a color, it would likely be `var(--iui-text-color)`.

I'm curious how you got `255, 255, 255, 0.85` on light theme. It is a dark theme value.

**Comment by irenajur** [comment]
This example is from header component and we use 2 themes for it: dark for the header itself, and light for all dropdowns.
```
.portal-header {
  //using dark theme colors for all header elements
  @include theme-variables('dark');

  .iui-menu {
    //based on mockups dropdown should be in light theme
    @include theme-variables('light');
  }
}
```
And in this case color of text in light theme dropdown is inherited from the header that is in a dark theme.

**Comment by mayank99** [comment]
> we use 2 themes for it: dark for the header itself, and light for all dropdowns.

That is some weird usage, but ok lets see what we can do.

I wonder if this is a scoping issue with the CSS variables. If you manually set the color on your side, does it work?

```scss
.iui-text-block {
  color: var(--iui-text-color);
}
```
