### ISSUE TITLE
Dots navigation component

### ISSUE THREAD

**Issue by alexfrompiter** [iTwin/iTwinUI#374]
#### Feature
Dot navigation component need to operate slideshows or to scroll to different page sections
This component used in ConstructSim project

#### Examples
![dotsNavigation](https://user-images.githubusercontent.com/5772950/140941846-d55a5218-5c51-4b49-beeb-34b6afb307f6.jpg)

**Comment by alexfrompiter** [comment]
Can I make PRs to ITwinUI and iTwinUI-react to move this component?

**Comment by FlyersPh9** [comment]
Hey @alexfrompiter, thanks for reaching out.  @gretanausedaite and I are actively working on a branch that implements something very similar.  Screenshots of what we currently have below:
![Screen Shot 2021-11-09 at 3 49 40 PM](https://user-images.githubusercontent.com/849817/141002470-9c3d65b2-0397-4d00-9bb6-0eddf0d3b12d.png)
![Screen Shot 2021-11-09 at 3 49 52 PM](https://user-images.githubusercontent.com/849817/141002489-239b8844-069b-4f66-a8b5-64ee94f44585.png)

Would something like this work for you?

**Comment by alexfrompiter** [comment]
Hey @FlyersPh9, I have implemented dots component based on this video:
https://user-images.githubusercontent.com/5772950/141108237-2504e185-b58b-4205-9624-2599743be912.mp4

If you are interested, I can share the code.

**Comment by FlyersPh9** [comment]
@alexfrompiter sure, I'll take a look at your code.

**Comment by mayank99** [comment]
@alexfrompiter This was released in `@itwin/itwinui-css@0.45.0` and will likely be available in next minor version of `@itwin/itwinui-react` (i.e. `1.30.0`) in a few days.

**Comment by veekeys** [comment]
Hey @alexfrompiter 

`Carousel` and `Dots` components are available in @itwin/itwinui-react@1.35.0

Check usage in here
https://itwin.github.io/iTwinUI-react/?path=/story/core-carousel--basic
