### ISSUE TITLE
Active Header action has no underline

### ISSUE THREAD

**Issue by irenajur** [iTwin/iTwinUI#376]
#### Describe the bug (actual behavior)
Both HeaderButton & IconButton components have no underline when `isActive={true}` is set. 

#### Expected behavior
Active item should be underlined same as it would be underlined using HeaderButton in breadcrumbs.

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/itwinui-react-active-header-element-highlight-issue-1024k

##### Steps to reproduce
1. Use HeaderButton/IconButton as Header actions.
1. Set any of them as active.

#### Additional information
Used this as a temp workaround:
```
.iui-button.iui-active,
.iui-header-button.iui-active {
  box-shadow: 0 2px 0 0 var(--iui-color-foreground-primary);
}
```

**Comment by mayank99** [comment]
This is now available in iTwinUI-css 0.39.0+ and iTwinUI-react 1.25.0+ 🎉

> Both HeaderButton & IconButton components have no underline when isActive={true} is set.

We decided to only handle HeaderButtons for now, because adding the underline to IconButton would cause other issues. But you should be able to emulate an IconButton using just HeaderButton.
