### ISSUE TITLE
ComboBox: icon is not visible with css resets

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#407]
Having by default everywhere applied border-box makes ComboBox icon not visible:

![image](https://user-images.githubusercontent.com/81580355/145197276-1fa05bb1-81bd-4db3-baa4-93ed7c0da8a1.png)

This fix helped
![image](https://user-images.githubusercontent.com/81580355/145197401-c94fe16e-a4ab-43ff-a7ae-2b94a3e64d9d.png)

Not sure its good solution though.. Cause if thats the case, we need to apply to all our icons this or there is something else wrong..

**Comment by mayank99** [comment]
We don't have ComboBox in this repo, but the icon is using the `iui-actionable` class.
https://github.com/iTwin/iTwinUI/blob/8f891600d44230dea67f42c1540fadd92ce45723/src/inputs/labeled-inputs.scss#L259-L263

The issue is probably happening because of the padding.
