### ISSUE TITLE
Cleanup user icon component

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#41]
- [x] Class name refactor.
- [x] Remove `z-index`.
- [x] When image is not an ideal square then it loses aspect ratio.

**Comment by FlyersPh9** [comment]
I am not encountering the aspect ratio issue mentioned.  I placed a 2316 × 3088 (vertical) & a 2848 × 1718 (horizontal) photo inside the user icon and did not have any aspect ratio issues.

**Comment by FlyersPh9** [comment]
@bentleyvk, I _think_ we fixed the aspect ratio issue before switching to GitHub.  I can not reproduce this issue, can you confirm it is solved?

**Comment by bentleyvk** [comment]
Oh, I see there is `object-fit` CSS rule. Then it should be fixed in all modern browsers.

**Comment by mayank99** [comment]
Then lets close this

**Comment by mayank99** [comment]
Wait we never merged #34 😆
