### ISSUE TITLE
NotificationMarker: applying class straight to SVG is not working

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI#411]
Applying `iui-notification-*` to `<svg>` in React does nothing because `:after` and `:before` on SVG are not supported. https://stackoverflow.com/a/58053278

Workaround in React is wrapping svg with div that has `iui-notification-*` class.

**Comment by FlyersPh9** [comment]
Where do you need to apply the notification marker to an SVG?  I would think that SVG is actionable / clickable so I would think you'd apply the class to the parent button.

**Comment by bentleyvk** [comment]
This is how it is in side navigation HTML:
![image](https://user-images.githubusercontent.com/36186912/148054552-c68b1e9d-2f07-43d6-9fa3-1712604a4704.png)
But in React we are using plain SVGs not WebComponents like in CSS test HTMLs.

**Comment by FlyersPh9** [comment]
Ok, I now understand the issue.  I'm searching online trying to find out why, but my theory is that you can't place a pseudo element within an SVG.
![Screen Shot 2022-02-10 at 7 02 04 PM](https://user-images.githubusercontent.com/849817/153517437-fa381fd6-86c1-4bff-b16a-faf8b7fb1de3.png)

Maybe if we could place the `::after` within [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) but I don't know how we could do that?

**Comment by FlyersPh9** [comment]
I tried applying the classes to a wrapper `<div>`.  It appears to work in the HTML / CSS demos but is not working on my local copy of iTwinUI-layouts.
