### ISSUE TITLE
Modal appears larger than phone display

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#425]
If a lot of text is present within a modal & the screen is small enough, it may be impossible to access the close icon or the buttons at the bottom.
![Screen Shot 2021-12-20 at 3 36 15 PM](https://user-images.githubusercontent.com/849817/147160145-d1378352-2b7e-4613-806f-2128a339b93e.png)

**Comment by mayank99** [comment]
@FlyersPh9 Can you check if this is still an issue after all the changes we made to dialog in the last few months? If not, we can close it.

**Comment by FlyersPh9** [comment]
It looks like the bug is still present on default & draggable dialog, full screen dialog is ok because the body area is scrollable.

**Default dialog:**
![Screenshot 2022-12-13 at 4 40 46 PM](https://user-images.githubusercontent.com/849817/207449704-cbbed8ec-90de-4680-a748-4aa4ccd0dd52.png)

**Full screen dialog:**
![Screenshot 2022-12-13 at 4 42 08 PM](https://user-images.githubusercontent.com/849817/207449993-6584b3f8-6838-472d-9800-8a70be932552.png)

**Draggable dialog:**
![Screenshot 2022-12-13 at 4 41 51 PM](https://user-images.githubusercontent.com/849817/207450053-aa22390a-1e68-4970-9bfe-3b5bb47b3fa3.png)

**Comment by FlyersPh9** [comment]
@mayank99 looks like I'm having the same issue, `svh` may be the fix.
![Screenshot 2023-02-10 at 12 33 11 PM](https://user-images.githubusercontent.com/849817/218157972-25123c78-58e1-44e5-8823-988206db80c5.png)
