### ISSUE TITLE
Tile: focus states

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#442]
1. Tile is currently missing a custom focus state, so it shows the default browser outline if `tabindex="0"` is added to `div.iui-tile`
<img src="https://user-images.githubusercontent.com/9084735/148981524-b5544826-2d66-41ef-8302-15ad1a7d3d4e.png" width="40%" />

2. The "more options" button is hidden unless hovered, so it cannot be tabbed into. This could be fixed using a "visually hidden" that keeps the content accessible to screen readers.

**Comment by FlyersPh9** [comment]
1. Adding this `@include iui-focus($offset: 0px);` to `.iui-tile` will work, but it does look dangerously close to our selected state.
![Screen Shot 2022-01-12 at 1 40 05 PM](https://user-images.githubusercontent.com/849817/149201855-eddd8f3b-f8f0-4723-b7bc-11bfbbf030cb.png)
2. I am able to tab to the more options button without hovering [using focus-within](https://github.com/iTwin/iTwinUI/blob/08b4aa30fd15ad4d3abd2be01bb25bee48d4fad7/src/tile/tile.scss#L257).

**Comment by mayank99** [comment]
> I am able to tab to the more options button without hovering using focus-within.

How? It only works if the more options button is already visible. Try it on a tile that doesn't have any other interactable element. Or try tabbing from one tile back to the previous tile; it will focus the action icon rather than the more options button.

**Comment by FlyersPh9** [comment]
Ah, that is a good point.  If we include `tabindex="0"` on the tile itself you can use that to get `focus-within` to show the "more options" button.  But without that & without any interior buttons the "more options" button does appear to not be accessible.
