### ISSUE TITLE
LabeledInput custom icon vanishes

### ISSUE THREAD

**Issue by S-Bra** [iTwin/iTwinUI#447]
#### Describe the bug (actual behavior)
When hosting a LabeledInput inside a ButtonGroup, the inputs custom icon vanishes as soon as the mouse pointer enters the input text area.

#### Expected behavior
Custom icon stays visible inside the control (is drawn on top).

#### Reproduction
https://codesandbox.io/s/itwinui-react-buttongroup-hosting-labeledinput-and-icon-vanished-on-hover-f152x

##### Steps to reproduce
1. Enter the input near the text "Test"
2. "Close" icon no longer displays

#### Additional information
Working in itwin/itwinui-react@1.27

**Comment by mayank99** [comment]
@S-Bra This was a tricky one hence the delay, but it should be fixed in iTwinUI-css 0.47.0 and iTwinUI-react v1.31.0

**Comment by S-Bra** [comment]
Thanks, the itwinui-react@1.31 fixed the problem
