### ISSUE TITLE
Skip to Content link

### ISSUE THREAD

**Issue by VirginieGaudreault** [iTwin/iTwinUI#450]
#### Feature
'Skip to content' link for users using tab navigation. Allows to bypass links in header/menus and land directly into a page's content. This is a basic accessibility feature we should highly consider.

#### Examples
[WebAIM recommendation](https://webaim.org/techniques/skipnav/)
[More info from Deque University](https://dequeuniversity.com/tips/add-skip-navigation-link)

CC @FlyersPh9

**Comment by mayank99** [comment]
While it is an essential accessibility feature, I wonder if we need UI for it (our main focus _is_ UI after all).

This is what Google's skip link looks like:
![image](https://user-images.githubusercontent.com/9084735/150014831-ba4f7b25-aa32-4dfa-ab44-e7e407f2d9af.png)

The hardest problem here is literally just deciding where exactly to position it so it's readable. I don't think we can make that decision in iTwinUI as every app is different.

**Comment by mayank99** [comment]
@VirginieGaudreault You might be interested in seeing how this turned out: https://itwin.github.io/iTwinUI/backstop/minified/skip-to-content.html

**Comment by VirginieGaudreault** [comment]
> @VirginieGaudreault You might be interested in seeing how this turned out: https://itwin.github.io/iTwinUI/backstop/minified/skip-to-content.html

Not bad at all! However I am a bit worried about discoverability if it's hidden until tabbed to. I need to do more research to see if that may cause confusion/friction. Do you have any info relating to my concerns?

**Comment by mayank99** [comment]
This is a pretty standard pattern. Even your own linked resources have some info on this: https://webaim.org/techniques/skipnav/#hidden

And this is what W3C says:
> [Success Criterion 2.4.1](http://www.w3.org/TR/2008/REC-WCAG20-20081211/#navigation-mechanisms-skip) does not require that they be visible when they do not have focus, and links that are visible only when they have focus can meet this success criterion.

(from https://www.w3.org/TR/WCAG20-TECHS/G1.html)

Here's some more info:
- First use in 1998: https://www.jimthatcher.com/skipnavold.htm
- a11y project writeup: https://www.a11yproject.com/posts/skip-nav-links/
- Smashing magazine 2021 guide to accessible components: https://www.smashingmagazine.com/2021/03/complete-guide-accessible-front-end-components/#accessible-skip-links

**Comment by VirginieGaudreault** [comment]
Thanks for the links! It's difficult to remember/keep track of all the new information I've been learning lately. 

I will be adding this new component to the documentation as soon as time allows.
