### ISSUE TITLE
ColorPicker: transparent swatch

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#482]
_Originally posted by @claudiaareneee in https://github.com/iTwin/itwinjs-core/issues/3197_

### Feature

Currently, if a transparent color is passed to our ColorSwatch, then it just shows the color of the background:
![image](https://user-images.githubusercontent.com/9084735/153671823-64e0a366-3dfe-465a-aa66-3113f9f3b9be.png)
![image](https://user-images.githubusercontent.com/9084735/153671843-69a9a6c7-3409-4aec-b4be-a08c7d86b41e.png)

Our UX standards have a diagonal line to indicate transparency, so we should handle styling for it.
![image](https://user-images.githubusercontent.com/9084735/153671987-c4c050af-81be-45e5-9420-5ff1e7d3d216.png)

### Example

I imagine we could add a modifier class (e.g. `iui-transparent`) on `iui-color-swatch`, and then in iTwinUI-react we can use our `ColorValue` util to check if a color is transparent and automatically apply this class.

**Comment by FlyersPh9** [comment]
Decided to go with the checkered background pattern used on the opacity slider for consistency sake.  I'll ask @VirginieGaudreault next week to update the documentation site.
