### ISSUE TITLE
Modal title is slightly cut on Safari if Open Sans font is used

### ISSUE THREAD

**Issue by irenajur** [iTwin/iTwinUI#485]
#### Describe the bug (actual behavior)

Modal title is being slightly cut at the bottom.

![image](https://user-images.githubusercontent.com/83585850/153846327-f0b69253-73d9-4938-a924-46730a83a660.png)

Bug is reproducible only on Safari with Open Sans font used (tried to reproduce same issue in storybook, but due to font differences everything looks good).

#### Expected behavior
Text should fit to height on all browsers.

**Comment by FlyersPh9** [comment]
@irenajur @veekeys where can I get that modal to appear within developer.bentley.com?

**Comment by FlyersPh9** [comment]
Seems like applying `.iui-title-bar { align-items: stretch; }` seems to do the trick.

**Comment by irenajur** [comment]
> @irenajur @veekeys where can I get that modal to appear within developer.bentley.com?

You can see Client Secret modal after creating Service type application or Confirmation dialog while trying to re-generate Client Secret on app edit page.
