### ISSUE TITLE
Add InputDatePicker component as a controlled DatePicking Input field. 

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI#53]
#### Feature
So DatePicker is allowing user to pick a date. Though, DatePicker is the whole component when I would expect DatePicker to be a floating component attach to something else. I would expect a DatePicker to be an input field where when click on it, show up a floating component that help choosing a date. I wasn't expecting that DatePicker would be the body of the floating component. 

It can make sense to keep the DatePicker like this for custom/advance feature, but I think 95% of the case, people will need an Input like component with the DatePicker built-in. So I'm requesting an new component called InputDatePicker which handle date picking in a form. 

#### Examples
```tsx
<PanelProperty 
  editMode={true} 
  editInput={ <DatePicker date={editedObject.Date} onChange={(value) => setObject({...editedObject, Date: value,})} /> }
/>
```

That's what I would be expecting from a DatePicker :
![image](https://user-images.githubusercontent.com/4070713/116915116-9b9f4b80-ac19-11eb-88b3-e03224d32b88.png)
That what I got : 
![image](https://user-images.githubusercontent.com/4070713/116915642-46b00500-ac1a-11eb-85a7-73d322400d50.png)

**Comment by mayank99** [comment]
Out of curiosity, could you try testing the interaction between `DatePicker` and `input type='date'`?

<details>
<summary>Starter code</summary>

react (inside component):
```jsx
  const [isOpen, setIsOpen] = React.useState(false);

  return (
    <>
      <span style={{ display: "inline-flex"}}>
        <Input type='date' />
        <IconButton onClick={() => setIsOpen(open => !open)}><SvgCalendar /></IconButton>
      </span>
      {isOpen && <div><DatePicker /></div>}
    </>
  );
```
scss (to hide default browser date picker):
```scss
input[type='date'] {
    &::input-placeholder { 
        visibility: hidden !important;
    }
    &::-webkit-calendar-picker-indicator {
        display: none;
    }
}
```
</details>

If you can add the state management/validation for date values and test if it works ok, then this component's implementation would become a lot simpler (without the need for much SCSS).
