### ISSUE TITLE
CI/CD workflows need to be improved or reworked

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#545]
### Requirements

1. CI should run on every PR
   - it should run build/tests as usual --- ✔️ 
   - it should upload failed test results (backstop html report) and provide a convenient clickable link to open the report --- ✔️ 
   - it should not leave behind any red ❌ if re-running a job results in success --- ✔️ (#560 )
   - it should not affect any files in the `gh-pages` branch that are unrelated to the PR ⚠💀 --- ✔️ (#556 )

2. After a PR is merged into main branch,
   - it should run build/tests as usual (again, on main branch) --- ✔️ 
   - it should clean up any leftover files (e.g. test results) from completed/abandoned PRs ⚠ --- ✔️ (#556 )
   - it should deploy a _new_ (fresh) set of files for viewing at https://itwin.github.io/iTwinUI. ⚠ --- ✔️ (#556, #553  )  
     - This includes `index.html`, the compiled `all.css` file, the minified `.html` files, as well as any assets (`demo.css`, `userIcon.js`, etc). ⚠💀
   - If the PR changes the package version, then it should automatically trigger npm publish. --- ✔️

### Current situation / additional information

Out of the requirements above, we have most of the things working in some form, but the ones that are problematic/broken are marked with ⚠ above.

The ones marked with 💀 are the most serious. Currently we have some files that either only live in the `gh-pages` branch (e.g. `index.html`) or they don't get updated from main branch (e.g. `theme.js`, `userIcon.js`). These files sometimes get accidentally removed or become outdated and then need to be manually uploaded again to fix things. It would be nice to have a reliable automated deployment process for this.

### Nice to have

Something like a "deploy preview" (see [netlify](https://docs.netlify.com/site-deploys/overview/)/[vercel](https://vercel.com/features/previews)) would also help with reviewing faster without pulling changes locally.

### UPDATE
I have marked with green checks parts which are already fixed, imo

**Comment by veekeys** [comment]
@mayank99 I think I have tackled all your mentioned points and issues.
From what I have tested, it should be much more stable and hopefully without critical issues.
Feel free to review it yourself.

Last thing mentioned in this issue is NTH part. Not sure about it, maybe will play around with gh-pages and have something similar like test results

**Comment by veekeys** [comment]
I am closing this as automated publishing worked fine.
