### ISSUE TITLE
Header button left & right paddings are different

### ISSUE THREAD

**Issue by irenajur** [iTwin/iTwinUI#574]
#### Environment
- __Package version(s)__: 0.53.2

#### Code Sandbox
Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/itwinui-react-example-son74)): 
- Version with 0.38.0 version, where right & left paddings  for header button were same: https://codesandbox.io/s/itwinui-react-active-header-element-highlight-issue-1024k
- Version with 0.53.2 (latest for now) version, where right & left paddings for header button are different: https://codesandbox.io/s/itwinui-react-active-header-element-highlight-issue-forked-latest-packages-fyx6l7

#### Actual behavior
In current package version header button right & left button paddings are different.
![image](https://user-images.githubusercontent.com/83585850/161719024-8c33c831-3120-47e6-bce9-e9c2b7681da2.png)

#### Expected behavior
In previous package version those paddings were identical. 
![image](https://user-images.githubusercontent.com/83585850/161718884-7e5e8767-6765-4bbb-bc0f-7b42ee2e592b.png)

**Comment by FlyersPh9** [comment]
The `.iui-header-button` is really specific to these types of buttons:
![Screen Shot 2022-04-06 at 12 38 31 PM](https://user-images.githubusercontent.com/849817/162024490-f0c77e2e-ca2d-4a32-a8c8-9c277e6e82fd.png)

You can achieve what you're looking for if you remove the `.iui-header-button` modifier class:
![Screen Shot 2022-04-06 at 12 36 42 PM](https://user-images.githubusercontent.com/849817/162024318-27646615-92aa-40f7-9c8d-7856e64002b1.png)
![Screen Shot 2022-04-06 at 12 36 55 PM](https://user-images.githubusercontent.com/849817/162024320-3414e080-0cff-4856-b1c8-b78a2c7bf3d4.png)

Although you will lose the active stripe at the bottom (both buttons in the image below are active):
![Screen Shot 2022-04-06 at 12 38 23 PM](https://user-images.githubusercontent.com/849817/162024555-416c6fe9-d49e-4ea3-8956-dd61291a8218.png)

If you need that active stripe, I think we could handle that.

**Comment by veekeys** [comment]
@FlyersPh9 I think we should review this...
There shouldnt be a huge difference between split and dropdown buttons.

**Comment by veekeys** [comment]
Hey @irenajur 
This should be fixed with the latest react release [v1.37.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.37.0)
