### ISSUE TITLE
[V1] Icon refactor

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#606]
- [x] Move to helpers instead of components and restructure the variables.  

- [ ] Mayank wants to do something with web components and custom selector in there, so we could target those directly instead of first level element. 

- [x] Remove color from icon sizes mixins. 

- [ ] Use current color maybe.

**Comment by mayank99** [comment]
To expand, I was thinking three things:
1. All our svgs in `@itwin/itwinui-icons` should come with `width`, `height`, and `fill` attributes. This would mean we have to write less CSS.
2. All the icons in `@itwin/itwinui-icons-elements` should have a way to target them with a common selector. This could be a data attribute, e.g. `data-iui-icon=true`, or even add the name of the icon: `data-iui-icon=calendar`
3. Assuming those changes are made in the icons packages, in `@itwin/itwinui-css` we could target all web components with `[data-iui-icon]` and apply any special styles, e.g. `display: flex`.
