### ISSUE TITLE
Add listbox / transfer list component

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#634]
We should add a [listbox](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-rearrangeable.html) / [transfer list](https://mui.com/material-ui/react-transfer-list/) like component.  I think we should be able to use the styling present in `menu.scss` for the list boxes & our buttons for the left / right buttons.

Requested by Vikram More / SYNCHRO.

**Comment by FlyersPh9** [comment]
Old branch that also refactored `menu` to reuse mixins: https://github.com/iTwin/iTwinUI/tree/jon/menu-refactor-and-add-listbox

**Comment by FlyersPh9** [comment]
This component has been brought up 3 times by 3 different UX members in the past 2 weeks.  This was ranked as one of the higher priorities by UX leads & this could help our devs achieve their own custom implementation of a more advanced column manager.  Moving this one up in priority due to the demand.

**Comment by gretanausedaite** [comment]
Adding mockup: 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/83585998/218491304-b45fb032-d93d-4e3d-80f0-5d36281e9cc8.png">

**Comment by mayank99** [comment]
I think we should create a `List` component (#843) before we create a `Listbox`.

**Comment by gretanausedaite** [comment]
Screenshot with desired functionality from UX team: 
![image](https://user-images.githubusercontent.com/83585998/221892838-dd2f0728-6440-4812-8d64-7f86bf2cb422.png)
