### ISSUE TITLE
Layered Drop Down Menu

### ISSUE THREAD

**Issue by jjbeckman13** [iTwin/iTwinUI#653]
#### Feature
Layered Drop Down Menu

- context menu that can navigate to additional sub context menus
- each context menu could have an optional header that is fixed at the top of the menu that would allow navigating back to previous menu
- each context menu should be scrollable
- the main context menu should be able to display the selected choice of a sub-context menu
- context menu could have (see images below)
    - one or many settings that could be a toggle
    - selection
    -  count of sub menu settings enabled 
- [Miro Example of Navigation Paths of Existing Component](https://miro.com/app/board/uXjVOyOhU9c=/)

#### Examples

![image](https://user-images.githubusercontent.com/47185728/170059958-0ba021dd-5f03-45bd-a19e-a79b912d652a.png)

![image](https://user-images.githubusercontent.com/47185728/170058652-c8aef3bb-a9af-457b-9266-aee2fa5dd22c.png)

![image](https://user-images.githubusercontent.com/47185728/170058682-36486698-8b91-4b15-9f28-f4cd2bb2837b.png)

![image](https://user-images.githubusercontent.com/47185728/170060072-7daea872-3df0-4376-aa08-63e51506fdba.png)

**Comment by FlyersPh9** [comment]
Another user today requested this swiping forward / backward option but in the information panel.  Could also be used in side navigation submenu.

**Comment by jjbeckman13** [comment]
@elephantcatdog, Is there an ETA on when this component will be available?

**Comment by elephantcatdog** [comment]
I'm going to say sometime in February. There's not much time to work on it until next year.

**Comment by jjbeckman13** [comment]
https://bentleycs.visualstudio.com/beconnect/_git/OpenConstructionPlanner?path=%2Fsynchro-mono%2Fmodules%2Fsynchro-schedule%2Fsrc%2Fcomponents%2Ftoolbar%2FScheduleSettingsMenu.tsx&_a=contents&version=GBmaster 

![image](https://github.com/iTwin/iTwinUI/assets/47185728/80638be3-58ce-48ba-bf37-8bb4ea8bab71)


Updated Implementation @FlyersPh9
