### ISSUE TITLE
Dev server experience could be improved

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#657]
Currently we rely on asking every contributor to use a vscode extension like Live Preview to manually open the minified HTML file. This is a tedious and error-prone process (might forget to run `build:watch` or might open the unminified HTML file). Plus the auto-reload experience feels really messy, with the extension reloading multiple times.

It would be nice to offer a command like `yarn dev` that automatically serves a proper reliable dev server, similar to the `vite` playground in iTwinUI-react.

**Comment by gretanausedaite** [comment]
This also could be useful in using npm packages in css demo pages (eg. fontsource for fonts).
