### ISSUE TITLE
Codeblock button is missing a gap between icon and text

### ISSUE THREAD

**Issue by JonasDov** [iTwin/iTwinUI#663]
#### Environment
- __Package version(s)__: 1.17.1
- __Operating System__: Windows 10
- __Browser name and version__: Microsoft Edge (101.0.1210.53)

#### Actual behavior
Codeblock button does not have a gap between icon and text if a standard [ iTwinUI button component](https://itwin.github.io/iTwinUI-react/?path=/story/buttons-button--with-icon) is used. This is the HTML of standard component usage:
![image](https://user-images.githubusercontent.com/100586436/171155060-f8cdb9e8-9463-4741-baf6-65f33d93fd9e.png)
This is how it looks:
![image](https://user-images.githubusercontent.com/100586436/171155295-a90a49e7-f77f-49ec-9382-99e464c00ca6.png)
This is the HTML of [sample codeblock](https://itwin.github.io/iTwinUI/backstop/minified/code.html):
![image](https://user-images.githubusercontent.com/100586436/171155170-70ca2572-a07c-4362-a6a0-0c4ddda74af9.png)
This is how it looks in the sample:
![image](https://user-images.githubusercontent.com/100586436/171155334-94b8ee33-e079-4946-9a30-4434a87e8eb0.png)

#### Expected behavior
There should be a gap between the icon and the text of the button.

**Comment by FlyersPh9** [comment]
If you right click & inspect the `<svg-copy>` element, the demo page is showing a left & right `margin` of `3px`.
![Screen Shot 2022-06-03 at 11 29 04 AM](https://user-images.githubusercontent.com/849817/171884922-6fcb57e8-787c-46d2-b87d-5da68d881457.png) ![Screen Shot 2022-06-03 at 11 29 16 AM](https://user-images.githubusercontent.com/849817/171884952-d7016d67-b230-4153-a037-0ffeb5415f3e.png)

Do you see anything overriding that on your side?

**Comment by mayank99** [comment]
> Package version(s): 1.17.1

@JonasDov Looks like this is the version of `@itwin/itwinui-react`, not `@itwin/itwinui-css`. Could you run `npm ls @itwin/itwinui-react` and `npm ls @itwin/itwinui-css` in your app and share the output with us?

**Comment by mayank99** [comment]
Actually nevermind, it looks fine on normal buttons but in codeblock we are removing the gap for some reason. We should fix this.

https://github.com/iTwin/iTwinUI/blob/cd8c64f103815a1bb96a94e66433bb8226242b2d/packages/itwinui-css/src/code/codeblock.scss#L29-L30

**Comment by veekeys** [comment]
This is included in [@itwin/itwinui-react@1.40.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.40.0)
