### ISSUE TITLE
Menu item text color is not set

### ISSUE THREAD

**Issue by JonasDov** [iTwin/iTwinUI#683]
After updating iTwinUI react from 1.23.2 to 1.37.1 menu item text color is not explicitly set. As we were wraping menu item with anchor, now we need to explicitly override anchor text color. Before: 
![image](https://user-images.githubusercontent.com/100586436/172830479-c6a31f12-dfec-4b21-859a-35f68d8e4a56.png)
After:
![image](https://user-images.githubusercontent.com/100586436/172830570-b315276a-b2a5-4b72-a2ad-d18b6c1b8eff.png)

**Comment by mayank99** [comment]
Hey @JonasDov, thanks for creating this issue.

Your DOM structure seems invalid. `<a>` should not be a parent of `<li>`, it should be a child, and that's where our styles are defined too.

So this does not look like a bug in itwinui-css. If it worked in a prior version, it was an unintended side effect and not a feature.

**Comment by mayank99** [comment]
> we do not provide ability to use menu item as anchor (they have no other way to make whole menu item clickable as anchor)

This is a separate issue (a valid one!) that should be opened in [iTwinUI-react](https://github.com/iTwin/iTwinUI-react/issues).

> broken if there is anchor in any inner elements.

Anchor comes with its own styling so this is expected. I do not think this part has even changed between itwinui-react v1.23.2 and v1.37.1.

And I don't consider this "broken". To me it makes sense that the user needs to unset/override the color and text-decoration of `<a>` if those styles are undesirable.

**Comment by veekeys** [comment]
I know this change and I am saying, we might need to rethink the idea.
From recent learning, I think all elements with text should have their color set explicitly. In this case, there is no situation we want our text to appear in different color in menu item unless user explicitly overrides it with css.
Another example would be also connected with multiple themes:
Imagine your whole page uses light theme, but you want your header to be dark. We change variables values to dark themes ones. Our typography elements do not have text color set explicitly (we expect those to be inherited). In this situation happens, that they inherit text color from body and body's text color is the light theme one even though in header context we do have other values assigned to the css variables.
My question is, do we have the case, that having color on our elements with text would break something?

**Comment by FlyersPh9** [comment]
@mayank99 can this be addressed in #718?  Or should this be addressed sooner than iTwinUI-CSS 1.0?

**Comment by mayank99** [comment]
i don't think this will be affected by the new variables or 1.0 at all, it's a problem confined to our component

**Comment by FlyersPh9** [comment]
I meant with our changing of hover (shades of gray) and active (shades of blue) in #718, but I don't think that this fix needs to be tied with that change in 718.  I'll submit a fix to main now.

**Comment by FlyersPh9** [comment]
Fixed in #741.
