### ISSUE TITLE
Carousel: dots are not centered

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI#685]
When there are only few dots they are not centered:
![image](https://user-images.githubusercontent.com/36186912/173356623-a400062d-9bf4-498f-b65b-13ff9f5934dd.png)

**Comment by FlyersPh9** [comment]
Deleting [line 56 in `carousel.scss`](https://github.com/iTwin/iTwinUI/blob/main/packages/itwinui-css/src/carousel/carousel.scss#L56) seems to fix the centered dots issue.  However it does introduce a bug where the dots appear at an incorrect size on the top example in the attached video.

https://user-images.githubusercontent.com/849817/184234668-a3946f5b-1f9d-42a6-b3b8-7c896766a4fa.mov
