### ISSUE TITLE
Warning status for the Progress Linear component

### ISSUE THREAD

**Issue by andriusgv** [iTwin/iTwinUI#732]
#### Feature
Requesting a warning status for the Progress Linear component.

#### Examples
Example:
![image](https://user-images.githubusercontent.com/110670781/183071956-98ac0cc4-b3aa-4957-a53b-e132636f6482.png)

**Comment by FlyersPh9** [comment]
I spoke with the UX team and the UX members assigned to this project have decided to go a different direction, therefore we will not be adding a warning progress indicator status.

**Comment by andriusgv** [comment]
Ok, but then how we should implement this mockup made by Chrissy?
![image](https://user-images.githubusercontent.com/110670781/184898573-903e0297-5148-41ac-a40b-a8aec8be0712.png)

**Comment by Juliakas** [comment]
@FlyersPh9 Not sure if this the right place as I'm commenting on this very old issue, but are there still no considerations for adding this status? At least imo a good use case for this is to indicate "succeeded with warnings" kind of status - neither happy green that indicates 0 failure, nor angry red that means a process completely failed.

**Comment by mayank99** [comment]
@Juliakas We've added the warning status in [3.4.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.4.0) 🎉
