### ISSUE TITLE
`index.html` includes itself in the list

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#744]
https://itwin.github.io/iTwinUI/

> I noticed local & live both list **index** as a demo page & it just refreshes the homepage.  Not sure when this got introduced.
>
> ![Screen Shot 2022-08-12 at 10 56 43 AM](https://user-images.githubusercontent.com/849817/184382372-4c0fad11-73f6-4ed3-8b6a-5f43961b7bb1.png)

_Originally posted by **FlyersPh9** in https://github.com/iTwin/iTwinUI/issues/718#issuecomment-1213206314_

**Comment by rohan-kadkol** [comment]
Reopening since we reverted #853 with #865
