### ISSUE TITLE
`yarn approve` should be a top-level script

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#748]
Currently, `approve` only exists in the `@itwin/itwinui-css` package.
https://github.com/iTwin/iTwinUI/blob/3b9b327ed8cf84db87dc1d61d356445cd5b051ba/packages/itwinui-css/package.json#L57

This means that we need to either `cd` into that workspace or use `yarn workspace @itwin/itwinui-css approve`, which is not very nice. We should create an alias in the root package.json to approve test images.

**Comment by rohan-kadkol** [comment]
Closed with #778
