### ISSUE TITLE
Dialog CSS needs updates

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#759]
Between draggable dialog and dialog wrapper, there are a bunch of incorrect/redundant styles that need to be changed in itwinui-css.

Two main changes:
- dialog-wrapper should have `position: fixed` or `position: absolute`. Currently it has `position: relative`.
- draggable dialog should not have any position or sizing styles, because position will be set in JS and size should come from the default dialog.

![](https://user-images.githubusercontent.com/9084735/188235152-0429903e-4797-430d-a6c2-e932b2d914cc.png)

_Originally posted in https://github.com/iTwin/iTwinUI-react/pull/771#discussion_r962015453_

**Comment by bentleyvk** [comment]
Also need to remove `overflow: hidden` from `iui-dialog` https://github.com/iTwin/iTwinUI-react/pull/823#discussion_r968440623
