### ISSUE TITLE
Make colons (:) on input fields optional

### ISSUE THREAD

**Issue by AroSaneD** [iTwin/iTwinUI#76]
#### Feature
Currently colons get automatically appended to labels of inputs. This seems to clash with certain UX standards and can make it look awkwardly when using a required marker. 

#### Examples
![image](https://user-images.githubusercontent.com/7044709/118114229-fa21b200-b3ef-11eb-9443-279d6302a518.png)

Of course it can be overridden via css, but that seems like going against the grain. Perhaps it would be better if the colon would be optional addition, or left for consumers to manually add them when needed?

**Comment by mayank99** [comment]
This is available in [v0.15.0](https://github.com/iTwin/iTwinUI/releases/tag/v0.15.0) and will be reflected in the next iTwinUI-react release (1.5.0)
