### ISSUE TITLE
Allow for right aligned content placed within tabs row

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#770]
#### Feature
A user has requested the ability to place non-tab content right aligned within the tab row.  Original request was shared in iTwinUI-React repo but I believe may need to be resolved in iTwinUI-CSS first: https://github.com/iTwin/iTwinUI-react/discussions/806

#### Examples
![image](https://user-images.githubusercontent.com/849817/192629677-b2434e3f-506f-4864-b9a2-211564278f40.png)
![image](https://user-images.githubusercontent.com/849817/192629705-e277405f-bd25-453f-b518-eb2765930f90.png)
![image](https://user-images.githubusercontent.com/849817/192629707-c60d7103-db13-4243-8613-a1ca731d4a5a.png)

**Comment by FlyersPh9** [comment]
I've got the [feature request working in this branch](https://github.com/iTwin/iTwinUI/tree/jon/tabs-inline-content). A couple of things that crossed my mind while thinking about this:
1. The right aligned content is wrapped within a `<li>`.  The parent `<ul>` has `role="tabpanel"` which makes me believe this content should be placed outside of the `<ul>` since it is not a tab.
2. This option will only work with default tabs & borderless tabs.  Pill tabs can not work with this.
3. When tabs are in vertical orientation, I assume we bottom align the content?
4. Overflow might be tricky.

**Comment by bentleyvk** [comment]
Is it ok that nothing is aligned here? For me it is against UI principles.
![image](https://user-images.githubusercontent.com/36186912/192712364-4ec464ec-0175-4c7f-a60d-35318af554c3.png)

**Comment by veekeys** [comment]
> Is it ok that nothing is aligned here? For me it is against UI principles. ![image](https://user-images.githubusercontent.com/36186912/192712364-4ec464ec-0175-4c7f-a60d-35318af554c3.png)

right, but putting buttons on the bottom line looks kinda weird, imo :/

**Comment by mayank99** [comment]
> Is it ok that nothing is aligned here? For me it is against UI principles.

I believe that screenshot was from the user so it wouldn't look exactly like that.

If you look at [synchronization-report](https://stackblitz.com/github/iTwin/synchronization-report-react), we had to use the `small` version of input to avoid it from touching the bottom line.
![](https://user-images.githubusercontent.com/9084735/192789021-47271561-23ea-4496-bcc9-99c3dc3de39f.png)

In the v1 branch, we've updated component heights so that the tabs are slightly taller than buttons/inputs, so we might be able to align them better while using default sizes.

**Comment by FlyersPh9** [comment]
> > Is it ok that nothing is aligned here? For me it is against UI principles.
> 
> I believe that screenshot was from the user so it wouldn't look exactly like that.

That is correct, the first screenshot was from the original requestor.

> If you look at [synchronization-report](https://stackblitz.com/github/iTwin/synchronization-report-react), we had to use the `small` version of input to avoid it from touching the bottom line. ![](https://user-images.githubusercontent.com/9084735/192789021-47271561-23ea-4496-bcc9-99c3dc3de39f.png)
> 
> In the v1 branch, we've updated component heights so that the tabs are slightly taller than buttons/inputs, so we might be able to align them better while using default sizes.

Here is a screenshot showing from top to bottom small input, default input, & default input.  The default input is a little too close to the bottom line in the middle example for my liking.
![Screen Shot 2022-09-28 at 11 02 56 AM](https://user-images.githubusercontent.com/849817/192814541-9619f6c5-cf88-4f3f-abc2-a57120ca0e37.png)

**Comment by mayank99** [comment]
> The default input is a little too close to the bottom line in the middle example for my liking

What about in borderless tabs? That seems to be the more common use case.

If that is still too close, maybe we could increase the min-height for borderless tabs? I don't think we'd want to do that for default tabs though, since they are meant for use in App UI.

**Comment by FlyersPh9** [comment]
> > The default input is a little too close to the bottom line in the middle example for my liking
> 
> What about in borderless tabs? That seems to be the more common use case.

Here is what the borderless tabs look like with small, default, & default sized inputs.
![Screen Shot 2022-09-28 at 12 34 42 PM](https://user-images.githubusercontent.com/849817/192837215-50f685a7-2060-4411-81cf-c0faf09eede2.png)

**Comment by FlyersPh9** [comment]
The right aligned content should not be within the `<ul>` or `<ol>`. If this requires a major release, we will move this task back to To Do.

**Comment by rohan-kadkol** [comment]
> The right aligned content should not be within the `<ul>` or `<ol>`. If this requires a major release, we will move this task back to To Do.

I created PR #860 that uses `display: grid` to add `.iui-tabs-actions` (right content) outside of the `<ul>` without causing any breaking changes.

**Comment by rohan-kadkol** [comment]
The implementation will be complete after the merge of the React PR (#1002) too.
