### ISSUE TITLE
Table view options - Default/Condensed/Extra Condensed

### ISSUE THREAD

**Issue by DineshBodewar** [iTwin/iTwinUI#784]
Provide a component to manage the table view so more rows can be fit into available space

1] User clicks on configure icon provided on top of table
![image](https://user-images.githubusercontent.com/115967995/196095700-268b1826-afdf-4f3d-9741-4e18f4997ee6.png)

2] User click on it and he gets dropdown with options like below
![image](https://user-images.githubusercontent.com/115967995/196097759-ad51d3ae-7923-44f4-8bd1-f4eefa3a5dcb.png)

3] Each view sets the different row height in table so user can see more rows in available space as shown below
(You can decided on the row height on each view and below are the suggestions from our side :) )
main goal here is to have a options for user to adjust the row height 

![image](https://user-images.githubusercontent.com/115967995/196096065-f353fa21-cffe-4c32-a260-bb65a2ed2a9b.png)

**Comment by mayank99** [comment]
Closing this because it's already supported in our Table through the `density` prop.
https://codesandbox.io/s/itwinui-react-table-density-toggle-qxws22?file=/src/App.tsx

**Comment by FlyersPh9** [comment]
@DineshBodewar, Mayank's link demos the ability to switch table densities from within the UI which I believe is the core of what you are requesting.  Elements nested within the table such as buttons or avatars may also need to be resized.  This is also possible & fairly easy, but the demo does not demonstrate resizing nested elements.
