### ISSUE TITLE
ProgressRadial: Need additional sizes

### ISSUE THREAD

**Issue by DanEastBentley** [iTwin/iTwinUI#79]
Feature:
The iModel.js UI team is now consuming iTwinUI and is deprecating its own Spinner & ProgressSpinner components in favor of the ProgressRadial component in iTwinUI-react. The iModel.js spinner components support 16px, 32px and 64px sizes. The ProgressRadial supports two sizes: small (24px) and unspecified (32px). We are asking for support of all sizes (16px, 24px, 32px and 64px) in the ProgressRadial component.

Examples:
&lt;ProgressRadial size="tiny" /&gt;
&lt;ProgressRadial size="small" /&gt;
&lt;ProgressRadial size="medium" /&gt; is same as &lt;ProgressRadial /&gt;
&lt;ProgressRadial size="large" /&gt;

**Comment by FlyersPh9** [comment]
@DanEastBentley and I chatted, we decided to provide a 48px as the largest option instead of 64px.  96px was not being used and will be excluded.
