### ISSUE TITLE
ComboBox and Select indicator overwrites border in AppUi dialog

### ISSUE THREAD

**Issue by NancyMcCallB** [iTwin/iTwinUI#794]
Link to repro: https://www.itwinjs.org/sandboxes/NancyMcCall/ComboBox%20in%20ModelessDialog

##### Steps to reproduce
1. Press Open Modeless Dialog buttons
2. Hover over/click dropdown arrow
3: ComboBox border is clipped around the arrow:
![image](https://user-images.githubusercontent.com/45079789/199279879-47fb31f3-f396-49f3-9f28-c6c924b840ec.png)

**Comment by mayank99** [comment]
This is fixed in #796 and will be available in itwinui-css v1 / itwinui-react v2.
