### ISSUE TITLE
LabeledInput: Need vertical spacing between multiple inputs

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#829]
Multiple LabeledInputs need some vertical spacing between them to correspond to the [iTwin UI layout standard](https://ux.bentley.com/itwin/components/text-field.html).

![image](https://user-images.githubusercontent.com/15036346/205342688-0feeee49-2704-4b89-bcef-a9835073ea9e.png)

**Comment by FlyersPh9** [comment]
Suggesting /util/ component called "flex" maybe that handles vertical & horizontal spacing. Sounds similar to #586.

**Comment by FlyersPh9** [comment]
I'm assuming this part has `align-items: center;`.
![Screenshot 2022-12-13 at 4 29 08 PM](https://user-images.githubusercontent.com/849817/207447762-c22c7041-4ead-40b3-aa42-e55841d7fe5c.png)

There may be an edge case where the user would want `align-items: flex-start;`.  I imagine we could make that a prop.
![Screenshot 2022-12-13 at 4 33 54 PM](https://user-images.githubusercontent.com/849817/207448545-6c26d6e5-90a4-4479-b2d4-859e997cafc0.png)

> We might want to add special aliases for vertical/horizontal spacing within forms so that the user doesn't need to guess.

I support this.
