### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by jzbuchalski** [iTwin/iTwinUI#842]
#### Feature
We could use a searchbox.  Some features:

Allow specifying a time (for the callback).
Allow a fixed size, or an expandable search.
Allow providing "content" (up/down navigation buttons below).
Allow specifying "saved" searches through a dropdown button.

#### Examples

Simple:
![image](https://user-images.githubusercontent.com/17307464/206552074-e12a62d6-1fe2-43ee-afe8-59e558ef11b5.png)

Expandable:
![image](https://user-images.githubusercontent.com/17307464/206552248-b9a03510-df7a-415e-a7d4-8f61e7321b98.png)
![image](https://user-images.githubusercontent.com/17307464/206552298-02bd48fe-8562-4ec7-8c42-17886f9aba0d.png)

Navigation:
![image](https://user-images.githubusercontent.com/17307464/206552897-8ff29d23-3be2-4313-a326-84e03acd1f5f.png)

**Comment by FlyersPh9** [comment]
For the initial PR we will focus on the first 2 examples in your request.  I will create a new issue for the 3rd part of this request to track separately.
