### ISSUE TITLE
List component

### ISSUE THREAD

**Issue by jzbuchalski** [iTwin/iTwinUI#843]
#### Feature
A simple list component (div or ul) with child list items (li or div) that will handle the background colors for hover, selected, disabled, etc?

For most of our list components, we'd rather avoid using variables, and have a base component handle the styling.  The less customization at our end, the better :-)

#### Examples

![image](https://user-images.githubusercontent.com/17307464/206556598-bb7a50fe-7d1c-4007-a101-95f3620416d2.png)

**Comment by mayank99** [comment]
I agree we should have a lower primitive for lists, but if you need it quick, `iui-menu-item` will do the job in the meantime:
```html
<ul>
  <li class="iui-menu-item">Item 1</li>
  <li class="iui-menu-item iui-active">Item 2 (active)</li>
  <li class="iui-menu-item iui-disabled">Item 2 (disabled)</li>
</ul>
<style>
  ul {
    /* these should probably be in your reset */
    padding: 0;
    margin: 0;
  }
</style>
```

**Comment by jzbuchalski** [comment]
LOL, we have been using iui-menu-item, but not overly intuitive :-)

**Comment by jzbuchalski** [comment]
As you can imagine:

<List>
    <ListItem>
       My content
    </ListItem>
</List>

**Comment by jzbuchalski** [comment]
I guess the selected state would be complicated because of single versus multiple selection.  Maybe that could be left out.

**Comment by FlyersPh9** [comment]
@jzbuchalski can you share more information on how this list component will be used?

**Comment by jzbuchalski** [comment]
In most (if not all) of our widgets, we display list of items.  The list is either a tree (coming from app ui, actually viewer components react), or a flat list.  For the flat lists, we are creating out own components, either a div or ul, with child divs (or li's).  The challenge is getting the different hover, disabled, selected states to match.  If we could get, say, a list item primitive, we would eliminate different groups having to track down how to handle the different item states.  I am open to discussion?

**Comment by mayank99** [comment]
So your list is supposed to have interactable elements inside it, like `<button>`/`<a>`? Because that somewhat complicates things - the list item padding would make the clickable portion smaller (detailed in #840).
