### ISSUE TITLE
Menu: multiline list items

### ISSUE THREAD

**Issue by danleydmello** [iTwin/iTwinUI#85]
#### Environment
- __Package version(s)__: 0.13.1

If you look at Itwin.bentley.com or plansight the typical header dropdown has multiline list items:
![image](https://user-images.githubusercontent.com/16119774/118290246-357db880-b4a4-11eb-9b99-ef4b921d3f94.png)

I  tried adding multiple divs inside the <span> but it shows only the first <div>:
  ```
<ul class="iui-menu">
            @if (_items != null)
            {
                foreach (var item in _items)
                {
                    <li @onclick="() => ItemClicked(item)">
                        <span class="iui-content">
                            **<div >
                                @item.ItemName
                            </div>
                            <div>
                                @item.ItemDescription
                            </div>**
                        </span>
                    </li>
```

**Comment by mayank99** [comment]
multi-line menu items are now available in 0.24.0 🎉
https://itwin.github.io/iTwinUI/backstop/minified/menu.html
