### ISSUE TITLE
Icon component

### ISSUE THREAD

**Issue by jzbuchalski** [iTwin/iTwinUI#851]
#### Feature
IconButton is very helpful for displaying an SVG (as a button), and handling theme.  Can we get something similar that isn't a button, that simply displays an SVG?  Current we add svg's to the dom, but unless additional styling is added, they are not themed.  Seems like a component that wraps an SVG and handles theme changes, would be helpful.  As mentioned previously, the less styling (CSS) at our end, the better.

#### Examples
Provide some examples, how you would like it to work.

**Comment by FlyersPh9** [comment]
Needed for #586.   Would be a `<span>` that wraps an `<svg>`, could include size & fill to be applied to the nested SVG. Will likely need `flex-shrink`.
