### ISSUE TITLE
Menu: adding seperator between the list items

### ISSUE THREAD

**Issue by danleydmello** [iTwin/iTwinUI#86]
#### Environment
- __Package version(s)__:0.13.1

In itwin.bentley.con or plansight , a typical header dropdown has seperator(s)  in the menu:
![image](https://user-images.githubusercontent.com/16119774/118290915-f734c900-b4a4-11eb-82fa-383eb0763244.png)

I couldn't find any styling for it in ITwinUI.

**Comment by mayank99** [comment]
`iui-menu-divider` is now available in 0.24.0 🎉
