### ISSUE TITLE
ComboBox: New option to make the input non-sensitive to diacritic-modified letters

### ISSUE THREAD

**Issue by SetropLeo** [iTwin/iTwinUI#872]
## FEATURE

Implement functionality that will make the input non-sensitive to diacritic-modified letters. 

The idea is to create a property in the component that, when set to true, will convert the diacritic-modified letters from the ComboBox input filter into their ASCII counterparts. 

<br>

#### EXAMPLE

As you can see in the image below, the user wrote "aero" and the dropdown still shows the options like "Aeróbics". 
![itwin-combobox](https://user-images.githubusercontent.com/77972979/208925847-d2c2453f-b678-4aab-af1a-22be53879b98.png)

<br>

#### HOW IS IT GOING TO WORK? 

When you write something in the input, the component will set the changes in the Input value State (which will show exactly what has been written) and in the Filter State (which can convert or not the diacritic-modified letters depending on the new property value). The user will see what he wrote and the dropdown options list will be listening to the new Filter state. 

1. First, we need to create a component property like "convertDiacritics" that will handle a boolean value. The default value is false. 

2. Now, we need to separate the ComboBox input value from the filter value. Each will have its own React state for controlling different values. (example for naming the states: inputValue and filterValue ). 

3. When changes are applied to the input, the input onChange method will call a function to handle the changes. 

4. Inside that function, you will apply the changes in the React states I've mentioned above. 

- The InputValue state will just receive the changes.

- Before applying the changes in the filterValue state, we need to verify the new property. 
   - If the property is set to true, convert the diacritic-modified letters into their ASCII counterparts using the 'replaceDiacritics' function and then set the converted value in the Filter State.  
   - If the property is set to false, just set the value in the Filter State. 

5. The input will be listening to the Input value State

6. The dropdown options will be listening to the Filter State

<br>

#### HOW TO IMPLEMENT THE DIACRITICS REPLACEMENT? 

1. Create a file with the function 'replaceDiacritics' and in the same file implement a constant that will contain all diacritics values. The function will make use of the constant.

![itwin-combobox2](https://user-images.githubusercontent.com/77972979/208934067-0201d99b-c6df-4208-8fdf-12fbf1b156e7.png)

```
const replaceDiacritics = (str: string): string => {
  let returnString = '';
  if(str) {
    for (var i = 0; i < str.length; i++) {
      if (diacritics[str[i]])
        returnString += diacritics[str[i]];
      else 
        returnString += str[i];
    }
  }
  return returnString;
}
```

2. Now that you have the function and the constant with all diacritic values, you just need to call the function 'replaceDiacritics' passing through parameters the value of the input change. After that, you can set the FilterValue with the result of function. 

<br>

#### SELECT2 DIACRITICS TRANSLITERATION DOCUMENT

https://github.com/select2/select2/blob/develop/src/js/select2/diacritics.js

**Comment by mayank99** [comment]
Hi @SetropLeo, are you aware of the `filterFunction` prop? You can implement your diacritics-aware filter logic there.

```tsx
<ComboBox
  options={options}
  filterFunction={(options, inputValue) => options} // do your custom filtering here
/>
```

**Comment by SetropLeo** [comment]
Hi @mayank99, 

Yeah, I'm aware of the `filterFunction`. In fact, I applied the needed logic with it as you can see below. 

<pre>filterFunction={(options, inputValue) =>
   options.filter((option) =>
     option.label
       .toLowerCase()
       .includes(replaceDiacritics(inputValue.toLowerCase()))
    )
}</pre>

But I still believe that this behavior could be part of the component itself. Other libraries already have this implementation as default or at least a simple parameter to configure that. Maybe it can be an idea to be taken to other components too.

The library react-select is a good example: https://react-select.com/home
You can test the behavior in the first input shown when you open the link.  

![itwin-combobox4](https://user-images.githubusercontent.com/77972979/208974872-928298fb-ed26-4fef-98c7-581d85f45011.png)

**Comment by mayank99** [comment]
this kinda bloats up the component, so i think if we were to add it to iTwinUI, it would be opt-in, so that combobox is still usable without it. something like this:

```tsx
import { ComboBox, diatricsAwareComboboxFilter } from '@itwin/itwinui-react';

export default function App() {
  <ComboBox
   options={options}
   filterFunction={diatricsAwareComboboxFilter}
  />
};
```

but since you know how to achieve this on your end, i will add a "has workaround" label.

i'm not sure what other components you would like to see this in. Table is the only one that comes to mind.

**Comment by SetropLeo** [comment]
Hmmm ok. Perhaps this could be a future implementation.

Table component also is the other component that I thought to apply this feature. xD

**Comment by SetropLeo** [comment]
@mayank99 May I implement the feature and create a PR? 

I'm sure that it will be take less code than you are expecting and the behavior will be amazing.

**Comment by mayank99** [comment]
> May I implement the feature and create a PR?
> 
> I'm sure that it will be take less code than you are expecting and the behavior will be amazing.

Oh sure, go for it! I would still like to see a modular approach so that we could reuse the main diacritic list in Table in the future, but we can discuss that in the PR review.

**Comment by mayank99** [comment]
@SetropLeo Have you given this any more thought? If it's no longer a requirement or if your use case is already solved within your product, then let us know and we can close this issue.

**Comment by SetropLeo** [comment]
@mayank99 Sorry for not replying to you. I don't know why, but I didn't receive any notification except the one saying that you had closed the issue. 

We didn't give any more thoughts on this. The workaround worked fine for what we needed. Thanks for your help, buddy!
