### ISSUE TITLE
Ability to override DropdownMenu submenu expand behavior (on click, instead of on hover)

### ISSUE THREAD

**Issue by Juliakas** [iTwin/iTwinUI#879]
#### Feature
Additional prop for `DropdownMenu` component (something like `submenuExpandBehavior` with values `onClick`, `onHover` - _default_) which as suggested would allow to override behavior on how submenu items should be expanded, retracted.

#### Examples
![image](https://user-images.githubusercontent.com/36437897/207004949-a321da10-bca4-4e32-b09b-c574a98e6ef9.png)
When setting `submenuExpandBehavior` to `onCLick`, submenu is only shown when user clicks on _Item \# 3_. `onHover` would be same behavior as it is now. 

Can contribute to this feature if needed.

**Comment by FlyersPh9** [comment]
@Juliakas can you explain why you want this feature?  I shared the issue with members of UX and they are curious as to why.

**Comment by Juliakas** [comment]
@mayank99 yes, can contribute.

@FlyersPh9 as for why we need it - in some cases the submenu list of items can become long with narrow entries - user has to be very precise with their mouse movement in order to not accidently hover away from the items. It also forces user to carefuly hover into submenu by moving mouse horizontally:
![image](https://user-images.githubusercontent.com/36437897/232762613-0625fe28-a1d9-4ef6-9c81-919a5288376c.png)
It would be nice to go straight to item 6 from item 3 by moving mouse diagonally.

Now that I think about it, there could even be a short delay before closing submenu (like 0.3 sec?) when hovering away from items which gives user a chance to go back to the list if they accidently unhovered it by a couple of pixels. Either way, need to test if it fixes the problem.

**Comment by mayank99** [comment]
> Now that I think about it, there could even be a short delay before closing submenu (like 0.3 sec?) when hovering away from items which gives user a chance to go back to the list if they accidently unhovered it by a couple of pixels. Either way, need to test if it fixes the problem.

I like this idea, it is much easier to implement than reworking the whole behavior. Do you want to try doing that for an initial version and then get feedback from your users? (Of course this change would only go in 2.x from our side, but you could patch node modules if you're still on 1.x)

Another option that we are currently working on is #653, which seems like a more robust solution with better UX.

**Comment by Juliakas** [comment]
#653 Looks interesting, think this could work, but have to make sure first.

Also, should we be able to use both 1.x and 2.x components with help of npm package aliases?

**Comment by mayank99** [comment]
> Also, should we be able to use both 1.x and 2.x components with help of npm package aliases?

You can as long as there is no v1 component inside a ["v2 boundary"](https://github.com/iTwin/iTwinUI/wiki/Version-conflicts#itwinui-1x-and-2x-coexisting-incremental-migration).

**Comment by mayank99** [comment]
fyi #1301 was recently fixed in v2.

we will look into the other solutions in v3 (customizing the trigger and layered menus)

**Comment by mayank99** [comment]
This is fixed in [3.10.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.10.0), by making click an _additional_ trigger to hover.
