### ISSUE TITLE
Table: Grouped Header support

### ISSUE THREAD

**Issue by adamhock** [iTwin/iTwinUI#887]
#### Feature
After iTwin/iTwinUI-react#153 was closed, `Table` now displays a header when a first-level `Header` is specified. However, support from grouped headers needs to be added

#### Examples
react-table Sandbox: https://codesandbox.io/s/github/tanstack/table/tree/main/examples/react/grouping?from-embed
iTwin/iTwinUI-react#153 Sandbox: https://codesandbox.io/s/shy-wind-1sp5q?file=/src/App.js

**Comment by mayank99** [comment]
This will not be possible to achieve after #1072 and no one has requested it so I will close this. We can revisit after the upgrade to tanstack/react-table v8.
