### ISSUE TITLE
LabeledInput cannot work with React.useMemo when typing Chinese.

### ISSUE THREAD

**Issue by YangMieEr** [iTwin/iTwinUI#890]
#### Describe the bug (actual behavior)

When LabeledInput is used with React.useMemo, the input box cannot enter Chinese 
#### Reproduction
Link to a minimal repro: 

##### Steps to reproduce
1. create LabeledInput used with React.useMemo
1. bind the props of value and "onChange" event  
1. typing Chinese to update the value of the labeledInput

**Comment by mayank99** [comment]
Closing this for lack of info. Will reopen when there is proper repro.
