### ISSUE TITLE
Table: columns become sticky right when added with column manager

### ISSUE THREAD

**Issue by medikornov** [iTwin/iTwinUI#892]
#### Describe the bug (actual behavior)
After reordering columns and selecting not visible columns in column manager, they become sticky right.
#### Expected behavior
Columns should not become sticky after reordering and selecting not visible columns in column manager..

#### Reproduction
https://codesandbox.io/s/itwinui-react-example-forked-g9xroe?file=/src/App.tsx

##### Steps to reproduce
1. Add `sticky: right` column manager and enable column reordering.
2. In column manager unselect a few columns
3. Reorder existing columns. For example, drag the first column onto the second
4. In column manager select any not selected column
5. Selected column becomes sticky right

#### Additional information

`"itwinui-react": 1.47.1`

https://user-images.githubusercontent.com/75395229/196682818-296306eb-6805-467f-8135-acd1525220e4.mp4

**Comment by GintV** [comment]
@adamhock any progress with this one?

**Comment by adamhock** [comment]
@GintV A PR for this issue has been merged and will be releasing soon
