### ISSUE TITLE
Extend globalFilter feature to filter subRows in Table expandable SubRows.

### ISSUE THREAD

**Issue by mrpathi** [iTwin/iTwinUI#896]
Global filter works better if we have flat list table. But It is not working if we apply global filter in expandable subrows.  Since our all the models are like tree structure it is very much required for tree kind of table. If you can extend this feature to expandable subrows very useful.

**Comment by elephantcatdog** [comment]
This has been requested by another user.

**Comment by mayank99** [comment]
Closing this issue, as I doubt we're going to going to support this feature. Another user asked for it recently and they were satisfied when we suggested them to use the `globalFilter` prop to implement their desired filter logic.

```jsx
globalFilterValue={globalFilterValue}
globalFilter={(rows, columnIds, filterValue) => {
  console.log(rows, columnIds, filterValue);
  return rows.filter(/* … */);
}}
```
