### ISSUE TITLE
Table column cannot be resized when the width is set as a percentage

### ISSUE THREAD

**Issue by medikornov** [iTwin/iTwinUI#897]
#### Describe the bug (actual behavior)
Table columns cannot be resized when the width is set as a percentage and the whole table is not resized. For example, if you shrink or expand the table, then columns will be resizable.

#### Expected behavior
Table columns should be resizable without shrinking or expanding the whole table.

#### Reproduction
[Link to a minimal repro: ](https://codesandbox.io/s/itwinui-react-example-forked-de2ejq?file=/src/App.tsx)

##### Steps to reproduce
`const columns = useMemo(
    () => [
      {
        Header: "Header",
        columns: [
          {
            id: "id1",
            accessor: "id1",
            Header: "id1",
            width: "20%"
          },
          {
            id: "id2",
            accessor: "id2",
            Header: "id2",
            width: "20%"
          },
          {
            id: "id3",
            accessor: "id3",
            Header: "id3",
            width: "60%"
          }
        ]
      }
    ],
    []
  );`

#### Additional information
`"@itwin/itwinui-react": "1.46.0"`

**Comment by GintV** [comment]
Has any work started on this? Is there any work item in the backlog linked with this issue?

**Comment by gretanausedaite** [comment]
Hi @GintV, the work has not been started yet (status of the issue is "planned"). 
You can look at our backlog and express you opinion on what we should prioritise next in iTwinUI-react biweekly community meeting (happening on Tuesdays).
We also highly encourage our users to contribute to this library! PRs are always welcome.

**Comment by mayank99** [comment]
This is finally fixed in [3.3.2](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.3.2)! See [migration guide](https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v3-migration-guide).
