### ISSUE TITLE
DatePicker: Integrate TimePicker with range support

### ISSUE THREAD

**Issue by elephantcatdog** [iTwin/iTwinUI#901]
Right now changing the time on the TimePicker while range is enabled on the DatePicker changes the time for both the start date and end date.  We might want to come up with a way to allow finer control of the time.

From https://github.com/iTwin/iTwinUI-react/pull/737

Requested by someone in React Tuesday call

**Comment by rohan-kadkol** [comment]
Lately, we started to move away from recommending the range `DatePicker` after some users shared that the range `DatePicker` was a bit confusing for them. Instead, we recommend having two separate `DatePicker`s, one for the start and the other for the end (https://github.com/iTwin/iTwinUI/issues/1297#issuecomment-1554798288).

As a result, after discussing with @FlyersPh9, we decided to close this issue and instead recommend users to use two separate `DatePicker`s to select a range of dates (along with times).
