### ISSUE TITLE
Table: MiddleTextTruncation causes virtualized table to jitter

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#903]
Using `<MiddleTextTruncation />` inside a virtualized table leads to jittery behavior when vertically scrolling the table. I cannot reproduce the behavior if I turn virtualization off, or if I remove the MiddleTextTruncation, but the combination of these two seems to have issues. I've stripped out most other elements from the table and can still reproduce.

https://codesandbox.io/s/itwinui-react-minimal-example-forked-wjwt0e?runonclick=1

![Table jitters with middle truncation](https://user-images.githubusercontent.com/15036346/190218728-60ef6b43-8845-448d-9082-117280e3e1db.gif)

**Comment by rohan-kadkol** [comment]
I tried going through your code sandbox link but it says that the code sandbox is not found. Could you please confirm the link?

**Comment by HaveSpacesuit** [comment]
@rohan-kadkol I believe it is restored now, thanks

**Comment by bentleyvk** [comment]
Hi, it seems to be fixed in React 18. Here is updated sandbox: https://codesandbox.io/s/itwinui-react-minimal-example-forked-y5s42n?file=/src/index.tsx
Seems this fix worked here too: https://github.com/iTwin/iTwinUI/issues/884#issuecomment-1381536256

**Comment by mayank99** [comment]
Can we close this issue then? It is a bit elusive (I can't even reliably repro on React 17) and we have already spent a few days looking into it.

Realistically speaking, we are planning to migrate to tanstack-table v8 in the next major, and will likely use tanstack-virtual for virtualization, so this issue might just go away.

If we hear from more users that they are blocked from upgrading to React 18, then we can spend some more time on it.

**Comment by HaveSpacesuit** [comment]
Sounds good to me.
