### ISSUE TITLE
DatePicker: disable some dates

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#905]
Related to iTwin/iTwinUI-react#606 

It would be nice to be able to pass a function to a datepicker to determine if a date is selectable or not. For example, if using two date pickers in a "from date to date" situation, you would not want to enable a to date earlier than the from date. or perhaps you need to select a date (e.g., birth date), and it would be impossible for the date to be after the current date.

**Comment by mayank99** [comment]
🚀 This is now possible in 2.7.0 through the new `isDateDisabled` prop
