### ISSUE TITLE
When decrease table header width the height of header looks wired 

### ISSUE THREAD

**Issue by mshafiqmk** [iTwin/iTwinUI#908]
#### Describe the bug (actual behavior)
When we try to decrease the width of the table header, when it reaches the state where the width is less than the width of the text, the height of the header column starts increasing and it affects the height of the table header.

#### Expected behavior

There should be minimum width set for each header based on the width of the header text

#### Reproduction
Link to a minimal repro: https://itwin.github.io/iTwinUI-react/?path=/story/core-table--full-2

##### Steps to reproduce
1. Open this example https://itwin.github.io/iTwinUI-react/?path=/story/core-table--full-2
1. decrease the width of any column e.g. price, quantity 

#### Additional information
![chrome_k368CHOF0c](https://user-images.githubusercontent.com/21343093/182794483-dbcd8b2a-bff1-4b49-9a59-7d9c005d07b1.gif)

**Comment by mayank99** [comment]
This is finally fixed in [3.7.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.7.0) 🥳

See [migration guide](https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v3-migration-guide) if you're still using an older version.
