### ISSUE TITLE
Tile: `isActionable` does not scale svg

### ISSUE THREAD

**Issue by JonasDov** [iTwin/iTwinUI#910]
When Tile has isActionable set, it does not scale svg type (iTwinUI v1.37.1)
![image](https://user-images.githubusercontent.com/100586436/173031435-f9a1965f-1341-4b0d-b63d-4349f4fa6c68.png)

**Comment by mayank99** [comment]
in #1110, we have improved the tile hover effect in a few different ways. the initial implementation was trying to scale the svgs but it was resulting in some unpleasant visuals, so the new effect will now rotate the svg by a few degrees and translate the whole tile by a few pixels.

https://user-images.githubusercontent.com/9084735/222790186-e900013f-78a1-49c8-bf81-468d424e7c85.mov
