### ISSUE TITLE
Tabs: inconsistent stripe width on first mount

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#911]
On the _first visit_ to a page that uses our borderless and pill tabs, I noticed an inconsistency in the stripe width. When I visit the page, the stripe width looks wrong. When I refresh it, it corrects itself.

In borderless and pill tabs, we rely on client-side JavaScript to set the width and position of tabs. There is no way around that, which is fine.

This also causes some flakiness in our react visual tests as the screenshot is taken before the transition completes.

![](https://user-images.githubusercontent.com/9084735/170126124-701ca786-940a-43d8-892c-f1c63e7685e1.png)
![](https://user-images.githubusercontent.com/9084735/170126207-f6bcd264-c05b-4f60-833f-6b2889f808a9.png)

This could possibly be because in our CSS we apply a transition on the `width` and `left` properties, which causes a bit of delay/content shift after the JavaScript runs.

https://github.com/iTwin/iTwinUI/blob/6c94ffbb7e93049dc6d1c81049ddf55e57418c68/src/tabs/tabs.scss#L202-L204

Further investigation is needed. This issue can be moved to iTwinUi-react if the fix is entirely JavaScript.

**Comment by LostABike** [comment]
@mayank99 How can we reproduce this? I tried in Storybook, vite and sandbox but I'm not seeing this bug o.o
https://codesandbox.io/s/fervent-shaw-w5w1u3?file=/src/App.tsx

**Comment by mayank99** [comment]
@LostABike it's a bit hard to repro. you can kinda see it when you open the story in a new tab and hard refresh (ctrl+shift+R) repeatedly 

https://user-images.githubusercontent.com/9084735/222519037-c6f6095d-31fc-48c6-a295-26735b048b52.mov

---

for a more practical repro, you can try adding it in the nextjs playground, then test the prod build using `yarn build --filter=next-playground && cd playgrounds/next && yarn start`. you will find that the initial html has no stripe because it is calculated by JS that loads later.

https://user-images.githubusercontent.com/9084735/222520837-deab190a-055e-4290-92fb-cfe2e9eedf02.mov
