### ISSUE TITLE
HeaderLogo hover state is applicable only when onClick is defined

### ISSUE THREAD

**Issue by irenajur** [iTwin/iTwinUI#920]
#### Describe the bug (actual behavior)
On our page we use links for navigation, so we have no point of defining onClick for HeaderLogo, but w/o it HeaderLogo has no hover indication. Maybe there might be another option having HeaderLogo hover indication w/o adding hacky/useless onClick? 

#### Reproduction
Link to a minimal repro: https://codesandbox.io/s/itwinui-react-header-logo-hover-state-issue-57yjb

@veekeys might add additional info if needed.

**Comment by mayank99** [comment]
a few years too late, but `as` prop has been added in #1109 😅 this means you can now render `HeaderLogo` as a link:
```jsx
<HeaderLogo as='a' href='/' logo={<svg>...</svg>}>Home</HeaderLogo>
```
