### ISSUE TITLE
Handle Alt key in keyboard navigation

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI#922]
Handle Alt key in keyboard navigation. Example: [howto-tabs](https://developers.google.com/web/fundamentals/web-components/examples/howto-tabs#:~:text=don%E2%80%99t%20handle%20modifier%20shortcuts%20typically%20used%20by%20assistive%20technology.)

**Comment by mayank99** [comment]
More detail on what this task entails:
1. Find components where we do custom keyboard handling (using `onKeyDown`).
2. Early return if <kbd>alt</kbd> key is pressed.
3. Possibly move the early return check into a utility that can be reused.
