### ISSUE TITLE
Overlay component

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#924]
We have css for it, lets add a react component.

**Comment by mayank99** [comment]
Adding updated links and screenshot.

Source code: https://github.com/iTwin/iTwinUI/blob/62a1eef90fd32932c327033ada2a956191025ce7/packages/itwinui-css/src/progress-indicator/overlay.scss

Preview (scroll to bottom): https://itwin.github.io/iTwinUI/dev/css/progress-indicator.html

![](https://github.com/iTwin/iTwinUI/assets/9084735/2cebeb08-82c4-46ea-9ca8-1e20b295514c)
