### ISSUE TITLE
Table: clicking on row's indeterminate checkbox makes it empty/false

### ISSUE THREAD

**Issue by bentleyvk** [iTwin/iTwinUI#928]
![table-subrows-filtered-selection-bug](https://user-images.githubusercontent.com/36186912/130052947-3e215b69-ceb7-420f-a6c4-2a395342780d.gif)

##### Steps to reproduce
1. Filter table that only part of sub-rows are visible.
1. Press on parent row's checkbox. It now has indeterminate state.
1. Press on the same checkbox. Checkbox is in empty/false state.

#### Additional information
The cause of this is `TableRowMemoized` which doesn't re-render because nothing really changed and checkbox does what it naturally should do - deselects.

### Possible fix
Either remove memoization or use virtual scroll.
Or there is a hack that makes checkbox to always rerender:
![image](https://user-images.githubusercontent.com/36186912/130053444-b8f73512-b019-4b20-97d6-c0a4705dce5c.png)

**Comment by mayank99** [comment]
This is finally fixed in [3.10.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.10.0) 🥳
