### ISSUE TITLE
ButtonToolbar component or add support for input and select in ButtonGroup

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI#93]
#### Feature
So I would like to have an Input or a Select beside a button or any horizontal component that could be interact with. Right now the closest things to that is the ButtonGroup, but it's Button exclusive... I would like it to be for anything that can be interact with. In my case, Select and Input handling in ButtonGroup is what I'm looking for. 

With Input type="datetime_local", there is a button already include in the input, but I need it to be able to erase it which isn't possible with native browser datetime input. So I'm adding a button to the right, but I would like to have preset style so I don't have to write the style. 

#### Examples
Something like this :
![image](https://user-images.githubusercontent.com/4070713/118688929-81966900-b7d4-11eb-9829-ade599bd57ff.png)
Right now adding Input in ButtonGroup look like this : 
![image](https://user-images.githubusercontent.com/4070713/118689711-4f393b80-b7d5-11eb-9d6d-ced529554a1c.png)

**Comment by mayank99** [comment]
We do [plan](https://github.com/iTwin/iTwinUI/projects/2#card-59850876) to add support for combining inputs and buttons. It will likely not be a part of `ButtonGroup`.

Also just to clarify, what do you mean by "I need it to be able to erase it"? Maybe you can add some details to #53

**Comment by maxime4000** [comment]
With native browser DateTime component, you can set a null date to a date, but you cannot unset a date to null... So the workaround is to set a button which allow to clear the input. If the iTwin DateTime component is decent, I would not be required to have that button, but because it's not implemented yet, this the workaround to unset date in a native input field.

**Comment by mayank99** [comment]
This is now available in iTwinUI-css v0.43.0 and iTwinUI-react v1.28.0
