### ISSUE TITLE
Tabs: Active stripe width does not resize when browser width changes 

### ISSUE THREAD

**Issue by rohan-kadkol** [iTwin/iTwinUI#947]
#### Describe the bug (actual behavior)
When resizing the browser horizontally, the active stripe width of the `borderless -> very long active tab` example does not change accordingly.

However, the active stripe width becomes correct when clicking on another tab.

[Video5.webm](https://user-images.githubusercontent.com/45748283/210456908-6d7e62ea-6713-4783-8599-ba61515a1cf7.webm)

#### Expected behavior
Active stripe width should be correct at all times, even when the browser width changes.

##### Steps to reproduce
1. Open `/tabs` HTML demo page
2. Scroll to the `borderless -> very long active tab` example
3. Change browser width
4. Notice that the active stripe width does not change
5. However, the width get corrected after clicking on a new tab

#### Additional information
Similar to #911, but this is in the CSS HTML demo pages and not in React/Storybook

**Comment by mayank99** [comment]
The CSS/HTML demos are not meant to fully demonstrate JS behavior, so bugs are expected. We don't deliver the JS code in those demos to users, so this is a non-issue.
