### ISSUE TITLE
Date picker with predefined date ranges

### ISSUE THREAD

**Issue by jzbuchalski** [iTwin/iTwinUI#948]
#### Feature
(from Dan Abney) _Since many of our apps revolve around schedules and managing them, having "relative to now" date ranges (vs users having to enter specific dates) is an improvement that likely everyone would probably want._

As Dan mentioned, many of our apps are filtering date based on given ranges, and entering a start & end date every time becomes cumbersome.

#### Examples
Here's an example from Media Indexing 
![image](https://user-images.githubusercontent.com/17307464/210577814-324bc15f-07e5-4fcc-ace4-8a2233521b73.png)

**Comment by mayank99** [comment]
@jzbuchalski Initially I thought this request was for `Table` but I see your issue title says "Date picker". And to me this just looks like a regular dropdown menu.

What do you expect to happen when clicking on one of those ranges? Maybe we could just provide a utility function (or suggest one) that does those calculations for you.

**Comment by mayank99** [comment]
Closing this for lack of info and because `<Select>` should work fine for predefined ranges.
