### ISSUE TITLE
Combobox : Improvement in dropdown menu width when enabledVirtulization is true

### ISSUE THREAD

**Issue by anjaligondsebentley** [iTwin/iTwinUI#955]
#### Feature
When combobox has enbled virtulization is true then dropdown menu width changes depending on the width of menu. This can be improved by setting dropdownmenu with to combobox width if virtualization is enabled.

#### Examples
You can see in below example dropdown width is changing.
![combobox](https://user-images.githubusercontent.com/113327714/210763337-eb28d54f-4289-4395-a579-c2d5aef63bca.gif)

**Comment by mayank99** [comment]
@anjaligondsebentley This is fixed in 2.2.1 🎉
https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.2.1
