### ISSUE TITLE
ComboBox: Items with duplicate labels are not filtered

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#960]
In a **`<ComboBox>`** with duplicate labels, the filter function does not filter out the duplicate labels when they do not match the filter. Additionally, the duplicate items are re-added every time the filter is cleared.

```ts
const values = [
  { value: "AK", label: "Arkansas" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "MO", label: "Missouri" },
  { value: "NE", label: "Missouri" },
  { value: "OH", label: "Missouri" },
  { value: "TN", label: "Tennessee" }
];
```

See this example:
https://codesandbox.io/s/itwin-combobox-duplicate-bug-59ko27

![Combobox multiples](https://user-images.githubusercontent.com/15036346/211037245-0c86abf7-b9eb-4c48-911b-bac18e6bfc54.gif)

**Comment by mayank99** [comment]
You can fix this by specifying your own `id` for the options.

```tsx
const prefix = React.useMemo(() => nanoid(), []);

return (
  <ComboBox
     options={[
      { label: 'Value1', value: 'value1', id: `${prefix}-value1` },
      { label: 'Value1', value: 'value2', id: `${prefix}-value2` },
      { label: 'Value1', value: 'value3', id: `${prefix}-value3` },
    ]}
  />
);
```

See more discussion in https://github.com/iTwin/iTwinUI-react/issues/863

**Comment by HaveSpacesuit** [comment]
Works great, thanks @mayank99!
