### ISSUE TITLE
v3: Tabs Composition API

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#970]
Here we need to rethink and improve the whole API.

- Split into separate components: TabsWrapper, TabPanel.
- Rename `labels` to `tabs` or even accept as children.

**Comment by mayank99** [comment]
The recent addition of `actions` could also be converted into a composition approach.

```jsx
<Tabs.Wrapper>
  <Tabs.Tablist>
    <Tabs.Tab>...</Tabs.Tab>
    <Tabs.Tab>...</Tabs.Tab>
    <Tabs.Tab>...</Tabs.Tab>
  </Tabs.Tablist>

  <Tabs.Actions>...</Tabs.Actions>

  <Tabs.Panel>...</Tabs.Panel>
  <Tabs.Panel>...</Tabs.Panel>
  <Tabs.Panel>...</Tabs.Panel>
</Tabs>
```

examples:
- https://www.radix-ui.com/docs/primitives/components/tabs
- https://reach.tech/tabs

**Comment by mayank99** [comment]
These hacks will need to be removed in the refactor:

https://github.com/iTwin/iTwinUI/blob/86a9acfcc0d305b8f7a832df2fd83885bccb1b3d/packages/itwinui-react/src/core/Tabs/Tabs.tsx#L246-L250

https://github.com/iTwin/iTwinUI/blob/86a9acfcc0d305b8f7a832df2fd83885bccb1b3d/packages/itwinui-react/src/core/Tabs/Tabs.tsx#L253-L258

There might be some more information in the PR where it was added: https://github.com/iTwin/iTwinUI-react/pull/181
