### ISSUE TITLE
LabeledInput: Need a way to display icons in both styles `inline` and `block` at the same time.

### ISSUE THREAD

**Issue by aurislt7** [iTwin/iTwinUI#983]
#### Feature
LabeledInput component needs a way to display icons inline and below at the same time to indicate status (warning/error etc.).
#### Examples
![image](https://user-images.githubusercontent.com/30312645/211559719-566fca1d-a1e0-4938-9ca1-5ec0321b62a8.png)

**Comment by mayank99** [comment]
I got pretty close by assembling a few different components: https://codesandbox.io/s/itwinui-react-minimal-example-forked-r017un?file=/src/App.tsx

Notes:
- `InputContainer` is currently marked "internal"
- `iui-end-icon` has some extra padding (fixable using `padding: 0` in your custom css)
- `Label` needs to be manually associated with the `Input` using id (recommended to use [`React.useId`](https://beta.reactjs.org/reference/react/useId))

This should be easier to achieve after #842 and #829 are worked on, but hopefully the sandbox will help you in the meantime. @aurislt7

**Comment by mayank99** [comment]
This is possible in v3 using a combination of [`InputWithDecorations`](https://dev-itwinui.bentley.com/docs/inputwithdecorations) and [`InputGrid`](https://dev-itwinui.bentley.com/docs/inputgrid). No internal components or CSS hacks necessary.

Note: the `Label` still needs to be manually associated with the `Input`'s id.
