### ISSUE TITLE
Table: Should scroll when dragging column to edge

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#993]
A table with a horizontal scroll and draggable columns should automatically scroll when attempting to drag column past the edge.

See this Code Sandbox reproduction:
https://codesandbox.io/s/draggable-column-scroll-10xibv

![Drag column](https://user-images.githubusercontent.com/15036346/211885876-a0512ddf-b182-4e37-89cd-14502cbbdbc9.gif)

**Comment by elephantcatdog** [comment]
@HaveSpacesuit Thank you for your contribution

**Comment by elephantcatdog** [comment]
Note to whoever works on this: a starting place to look is in `useColumnDragAndDrop.tsx`.

**Comment by rohan-kadkol** [comment]
This has been fixed and the overall horizontal scrolling experience has been improved in [v3.7.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.7.0) ! 🎉

See [migration guide](https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v3-migration-guide) if you're still using an older version.
